### ISSUE TITLE
Song, Artist, and Album Art Not Displaying

### ISSUE THREAD

**Issue by QuantumTunnel** [MarcoPixel/monstercat-visualizer#1]
Hi! Thanks for making this skin. I'm fairly new to rainmeter and I installed this and had it working with spotify for about an hour. Afterwards it would not display the track information or artist and I can't get it to work no matter what I do. Can you help? http://prntscr.com/cf1c3y This is what it looks like currently.

**Comment by MarcoPixel** [comment]
A update for Spotify (1.0.37.150) broke the Plugin used for the song informations. The current workaround is to downgrade to Spotify 1.0.36.124 (here's a guide for an older version, still works: http://www.wired.co.uk/article/how-to-downgrade-spotify)

I will label this as fixed when i get an update of the plugin.

**Comment by MarcoPixel** [comment]
As it seems there is no issue with the Spotify plugin, but more with Spotify itself i will close this issue because it can be fixed by reinstalling Spotify with the newest version.

If there is still any issues, please reopen this issue.
