### ISSUE TITLE
Changing Speaker to Headphone

### ISSUE THREAD

**Issue by jerryshaw12** [MarcoPixel/Monstercat-Visualizer#100]
everytimes i switch speaker to headphone, i need to refresh the skin, is there anyway to make it seamless? https://s1.postimg.org/455sfsr17z/speaker.png

**Comment by tjhrulz** [comment]
It should I guess be possible to use the Win7AudioPlugin to get the name of the default device and force a refresh when it has changed.

However both Marco and I have been a little busy lately so it may take us a while before we get around to it.

**Comment by MarcoPixel** [comment]
It should be possible to implement such thing as far as i know, but I haven't got that much time as i'm working on other projects right now as @tjhrulz already said.

I will definitely check it out and will keep you updated via comments on this issue.

**Comment by MarcoPixel** [comment]
I've added in the feature with 367dcee2e901dfc8ae0f5943d812670767aabff6, it will be in the next release.

If you already want to have the feature, check out the **Manual Installation** at the main github page.
