### ISSUE TITLE
Bass bars not being picked up correctly

### ISSUE THREAD

**Issue by raoo401** [MarcoPixel/Monstercat-Visualizer#102]
I recently re-downloaded the visualizer two days ago and worked perfectly fine. Now when I try to reinstall and remove any previous data it seems to pick up on the mids/highs like most visualizers. The bass is being picked up but the bars barely move any

**Comment by tjhrulz** [comment]
This is an issue likely caused by an equalizer on your computer and is out of our control.
I would recommend diabling any equalizers you have and if you use realtek uninstall their awful unneeded drivers.
