### ISSUE TITLE
Monstercat/Lano Flagging Antivirus?

### ISSUE THREAD

**Issue by ghallain** [MarcoPixel/Monstercat-Visualizer#104]
Both the Monstercat and Lano visualizer have been flagged by my antivirus, Webroot, as they apparently both contain Pua.Downloadmanager. Is this a known false flag, or something else?

**Comment by tjhrulz** [comment]
It's a false flag, probably caused by rainRGB

**Comment by MarcoPixel** [comment]
The antivirus flags RainRGB.exe as a virus, which is a false flag. We had issues with antivirus software detecting it before but the executable is coming from a developer of Rainmeter itself and it's only detected in a few antivirus softwares including Webroot. If you downloaded the skin from Github or the DeviantArt page you should be fine :)

Reddit post regarding false flag:
https://www.reddit.com/r/Rainmeter/comments/2cvj01/rainrgbexe_what_is_it_is_it_legit/

Virustotal: https://www.virustotal.com/de/file/e4814bac41a57772534536f484bf0d527a555a3c22b53f70c92e35ca664f1cfb/analysis/
