### ISSUE TITLE
Spotify shows no song information

### ISSUE THREAD

**Issue by R4min** [MarcoPixel/Monstercat-Visualizer#105]
Hey,
I have a problem. There is a bunch of error coming up every second and I am not able to get any song information displayed. I am not sure if it is one issue or two.

The error message:
`Chameleon: Could not get handle on C:\Users\******\Documents\Rainmeter\Skins\monstercat-visualizer\@Resources\images\coverSpotify.png`
![image](https://user-images.githubusercontent.com/16246664/32405114-2209721c-c15f-11e7-9985-92d547e5a9aa.png)

Rainmeter: 4.1.0 beta r2982 64-bit (Nov  3 2017)
Spotify: 1.0.66.478.g1296534d
Windows 10 Home 64-bit (build 15063)

The visualizer works but I don't get any song covers or the name of the song:
![image](https://user-images.githubusercontent.com/16246664/32405145-97c437f8-c15f-11e7-9063-5b7a23b11725.png)

**Comment by mads256c** [comment]
Update your spotify plugin by importing this skin: https://www.reddit.com/r/Rainmeter/comments/5zvz0r/update_spotify_plugin_updated_31717/

**Comment by tjhrulz** [comment]
Try looking at #40 and #77 for past issues like this and go through the debug steps listed there. @mads256c Unless he is on a really old version of Monstercat Visualizer we have had that version bundled for months now. If none of that works let me know and we can go through more steps.

**Comment by R4min** [comment]
Ahhh I had some spotify lines in my hosts. Thanks @tjhrulz for the info, now it works perfectly
