### ISSUE TITLE
Issue: Visualizer not refreshing for new songs

### ISSUE THREAD

**Issue by Jayceena** [MarcoPixel/Monstercat-Visualizer#106]
I have the visualizer connected to Itunes and it only pulls the song data when you change the visualizer from one to another. It still processes the visualization itself, but the color, artwork, title, artist, and progress bar don't change. I'm using 1.8.1 of the visualizer, 4.1 RC2 Release - r2982 of rainmeter, and iTunes V 12.7.1

**Comment by tjhrulz** [comment]
Given that you closed the issue I am guessing that you saw it but just in case you didn't see #95
