### ISSUE TITLE
iTunes album art and title/artist will not update when song is changed

### ISSUE THREAD

**Issue by Tech-Games** [MarcoPixel/Monstercat-Visualizer#107]
![image](https://user-images.githubusercontent.com/11528496/32417459-22816e9c-c228-11e7-8fa2-545ccee5d3d9.png)

**Comment by Tech-Games** [comment]
version: 1.8.1
 rainmeter: 4.1 beta
iTunes: 12.7

**Comment by tjhrulz** [comment]
Fixed as of Rainmeter 4.1 RC3, see #95.
