### ISSUE TITLE
Visual bars not working

### ISSUE THREAD

**Issue by nomercyjuno** [MarcoPixel/Monstercat-Visualizer#109]
I installed with default settings. The song/artist information works but the visual bars are not working. They don't move at all. What should I do?

**Comment by billathekilla** [comment]
I have the same problem i upgraded Rainmeter this morning to version 4.1. I'm getting a failed to initialize audio client looping in my logs. 
-THANKS

**Comment by tjhrulz** [comment]
I would check out #93 and the links listed in there.

Normally this is caused by either switching you audio device without doing a refresh all of the skins (Fixed if you do a manual install of the repo) or if you have realtek audio drivers installed (Which are safe to just remove and suck anyways)

**Comment by nomercyjuno** [comment]
Yeah! Removing realtek audio solve the problem. But it creates new problems for me. 1st is Windows always try to install Realtek again and 2nd is I cannot use my mic to talk. These 2 problems have been causing me trouble since Window 8 and I tried many ways but it still didnt work. How can I fix the 2 new problems?

**Comment by billathekilla** [comment]
My problem was bloatware that came on my Asus machine. I removed sonic studio and was good to go even with realtek drivers.

**Comment by nomercyjuno** [comment]
Oh thanks, I removed the sonic studio and it is working now with realtek!

**Comment by tjhrulz** [comment]
Thanks I'll keep that in mind in the future when people have audio visualizer issues
