### ISSUE TITLE
Support for multiple players?

### ISSUE THREAD

**Issue by askhavok** [marcopixel/Monstercat-Visualizer#111]
I would like to display Spotify when I'm playing using Spotify, as well as Foobar2000 when I'm listening with Foobar2000.

**Comment by tjhrulz** [comment]
This is something we have talked about doing but with the current way the plugins for players are it is not an easy process.

Our current stance is to wait until I get around to making a unified plugin to handle all the players and auto switch between them.

**Comment by marcopixel** [comment]
Merged with #280 .
