### ISSUE TITLE
Chromecast Integration?

### ISSUE THREAD

**Issue by shhuffman** [MarcoPixel/Monstercat-Visualizer#113]
Hey there!

First off, love the visualizer- it's awesome.

So I guess this would be more of a feature request than an actual issue, since I haven't encountered anything major otherwise.  

The issue happens in both the Google play music website and GPMDP.

I'm unfortunately one of the weirdos that will actually cast music from their computer to chromecast enabled devices. Everything works fine up until this point.

I think that when the casting process happens it's possible that it's hijacking the audio feed since the visualizer stops visually responding, despite still having more or less full control from the Cover Skin, and information still reporting back to the Song Information skin as well. Stopping the cast reverts the visualizer back to what's expected (after returning the audio levels back up to where it should be in the player.) 

Again, nothing show stopping but do you have any thoughts?  I'm savvy enough to attempt editing any files if you'd like me to try something.

Thanks!

**Comment by tjhrulz** [comment]
Unfortunately the way the visualizer works uses system sounds. While for other systems it might be possible in the future to install an app to monitor the sounds and send it back to Rainmeter it is not possible to ever do that on a Chromecast.
