### ISSUE TITLE
Bars stop working when audio output is changed

### ISSUE THREAD

**Issue by j4rp0** [MarcoPixel/Monstercat-Visualizer#114]
I think i've noticed an issue when multiple audio devices are available; at

monstercat/visualizer Settings -> General -> Change audio device -> Select Default

I assume that whatever the audio output is, the visualizer will work; but any time you switch your audio output from windows (from headset to speackers, for example) the bars stop.

The plugin still will show the information of the song, but the bars won't move until you select back the audio device that was set as default before. 

Not sure if it's a bug, but it's annoying to have to open the settings menu just to select the audio device any time i switch from headsets to speakers.

**Comment by MarcoPixel** [comment]
This was already fixed with #100.
Please follow the steps on the repo's main page for the **Manual Installation** to fix this issue.
