### ISSUE TITLE
Rainmeter crashes when I select iTunes as the main media player.

### ISSUE THREAD

**Issue by ScratchHacker1** [MarcoPixel/Monstercat-Visualizer#118]
So I am experiencing a new problem when I updated to Rainmeter version 4.1. So when I select iTunes as the main media player (So I can see the song ID and the album art) and as soon as I select iTunes Rainmeter crashes. Is this a bug thats got to do with me or is this an actual bug?

**Comment by ScratchHacker1** [comment]
So I found out that Rainmeter crashes when I have the cover.ini ans right.ini open (So the song ID and the cover art) but if I have just the visualizer running then it does not crash

**Comment by tjhrulz** [comment]
Update to the Rainmeter 4.2 beta, that will resolve the issue.
