### ISSUE TITLE
Song cover and information not working

### ISSUE THREAD

**Issue by Zemerald** [MarcoPixel/Monstercat-Visualizer#119]
The song cover and information don't appear on the visualizer whenever I play a song on spotify. Also these errors commonly show up in the logging file:

ERRO (09:10:51.936) monstercat-visualizer\Song Information\Cover\Cover.ini: ImageName: Unable to open: C:\Users\18410\Documents\Rainmeter\Skins\monstercat-visualizer\@Resources\images\coverSpotify.png
ERRO (09:10:38.083) : Chameleon: Could not get handle on C:\Users\18410\Documents\Rainmeter\Skins\monstercat-visualizer\@Resources\images\coverSpotify.png
ERRO (09:34:46.258) monstercat-visualizer\Song Information\Left.ini: !UpdateMeasure: [ScriptFactoryBars] not found
ERRO (09:34:46.265) monstercat-visualizer\Song Information\Left.ini: !UpdateMeasure: [ScriptFactoryShadowBars] not found
WARN (09:34:46.271) monstercat-visualizer\Song Information\Left.ini: !CommandMeasure: [ScriptFactoryBars] not found
WARN (09:34:46.276) monstercat-visualizer\Song Information\Left.ini: !CommandMeasure: [ScriptFactoryShadowBars] not found

I've looked at the files and for some reason there's a missing file that the error refers to, even though I've re-installed the visualizer a few times to get it back. I'm unsure of what to do to fix this. Can I please have some help?
<img width="960" alt="mcv_bug" src="https://user-images.githubusercontent.com/34044457/33293171-05aca9ee-d420-11e7-9456-f8d1d5f22fc7.PNG">

**Comment by tjhrulz** [comment]
What version of Rainmeter are you on? Try upgrading to the 4.2 beta and see if that helps.

**Comment by tjhrulz** [comment]
Closing since it is likely a duplicate issue of #120 and #115
