### ISSUE TITLE
Rainmeter crashing when playing certain songs from iTunes on 4.1, working on 4.2 but visualizer lags

### ISSUE THREAD

**Issue by maxgags** [MarcoPixel/Monstercat-Visualizer#120]
Hi, so ever since upgrading to 4.2 beta release, the songs can be played, but other songs with artwork have been causing the visualizer itself to lag with new release of iTunes

I suspect the artwork portion of the entire visualizer affects the visualizer performance in some sort of way - tested with multiple songs with and without artwork, both giving the same kind of results.

Artwork = laggy visualizer
No artwork = normal performance

**Comment by tjhrulz** [comment]
I'll investigate it here in an hour or so

**Comment by maxgags** [comment]
all right, thank you for the update. I'll try experimenting a bit more, if you're wondering about the songs that causes crashing in 4.1, I was attempting to play a few songs I downloaded off the League of Legends soundcloud page. Thanks!

**Comment by tjhrulz** [comment]
Yeah the 4.1 crash is a know issue fixed in 4.2

**Comment by tjhrulz** [comment]
All these issues should be resolved in Rainmeter 4.2 Beta Release - r3004. The only minor issue is that Rainmeter can lockup for a second or so when you close iTunes but that is Apple's fault.
