### ISSUE TITLE
Strange variations in CPU usage

### ISSUE THREAD

**Issue by classicalpunk** [MarcoPixel/Monstercat-Visualizer#121]
Hi everyone,

I noticed today that rainmeter was using almost 20% of my CPU even thought I only had a clock & weather widget and the Monstercat Visualizer hidden in the background (I use spotify and it was closed at the time). 

I fooled around and it seems like it's not related to an option like dynamic color or hiding when media player is closed, but when I turn on spotify, the cpu usage of rainmeter drop from 20-25% to almost 0-0.2%, and it get back up when I close it. 

With any another player selected in the settings, rainmeter CPU usage stabilize at about 7-8% (be it opened or closed) so I suspect it might have something to do with how spotify status is detected by the plugin.

I do not have the knowledge to go look under the hood so if someone could look into it it would be great. I really like the hiding when not running option, and having to keep spotify on to keep my CPU at bay is kinda contradictory.

Thanks !

**Comment by tjhrulz** [comment]
What version of the Spotify plugin are you running?

**Comment by classicalpunk** [comment]
Sorry for the late answer.
If the details of the file are OK, 1.3.0. I downloaded the visualiser on the 20th October and didn't changed anything in it.

**Comment by MarcoPixel** [comment]
It might be an issue how Spotify is detected by the skin, as it checks the running tasks in windows every second. Can you try and disable the auto-hide setting under the Settings skin?

**Comment by classicalpunk** [comment]
Like I said in my first message I tried with different settings, with or without auto-hide and with or without dynamic color, and it doesn't seems to have an impact (re-tried it right now to be sure, still same). I even tried disabling the progress bar or discharging the cover or the name of the artist/song and it doesn't change this strange behaviour behaviour.

**Comment by MarcoPixel** [comment]
Install this skin: https://forum.rainmeter.net/download/file.php?id=15328&sid=0c360a3f02475d547f8b2e799375cd58

Open the file, check if SpotifyPlugin.dll is getting replaced and then restart Rainmeter.

**Comment by classicalpunk** [comment]
Ok so now CPU usage is fixed, I get 0~ when spotify is not running, but the progress bar goes way too fast, and instead of N/A i got "0" when spotify is closed. But I'm okay with that, It disappears when it's in that state anyway, and I don't really need the progress bar

**Comment by MarcoPixel** [comment]
Great, glad that it helped.

For the issue regarding the 0s, i've already created an issue on the plugin's repo here:
https://github.com/RobertFrydenlund/SpotifyPlugin/issues/6

I will keep you updated when the issue is fixed and will post the steps to fix it :)
