### ISSUE TITLE
Cover art and title and song names are not showing!

### ISSUE THREAD

**Issue by SeloTapeTM** [MarcoPixel/Monstercat-Visualizer#122]
I use Spotify on my PC for listening to music, and  I've been using an older version of this skin for a while now and it worked just fine, when suddenly it stopped showing the correct progress on the cover art (time), and I figured that there might be and update. So I completely deleted the old version and installed the new version of this skin from scratch and now it simply doesn't get any information from Spotify but the sound itself to the visualizer, which works anyways with any sound on my computer.

Can someone please help?? have anyone else been experiencing this exact problem and solved it?

P.S.
I have installed the latest rainmeter today

**Comment by SeloTapeTM** [comment]
Nevermind, I solved it :)

I simply updated the spotifyplugin.dll :P

**Comment by MarcoPixel** [comment]
Glad that the issue got fixed :)

I will close this issue now, if you have any other issues please open a new issue.
