### ISSUE TITLE
Crash when selecting iTunes

### ISSUE THREAD

**Issue by Sasha2k1** [MarcoPixel/Monstercat-Visualizer#123]
### Description

When selecting iTunes as a player, Rainmeter crashes and refuses to boot unless I change the player in variables.ini

### Versions

* Rainmeter Version:4.1.0 r2989 64-bit
* OS Version: Windows 10 Pro 64-bit (build 14393)
* Skin Version:1.8.1

**Comment by MarcoPixel** [comment]
Download the [latest beta version](https://github.com/rainmeter/rainmeter/releases/download/v4.2.0.3011/Rainmeter-4.2-r3011-beta.exe) of Rainmeter and then try again.

**Comment by Sasha2k1** [comment]
Fixed.
