### ISSUE TITLE
Visualizer bars not working

### ISSUE THREAD

**Issue by lezombie** [MarcoPixel/Monstercat-Visualizer#124]
### Description

Hi there, 
So I recently downloaded and installed monstercat, but everything except for the visualizer bars are working. Song information, cover art, progress bar etc. are all working fine. but the bars aren't budging at all.

I've maxed out the sensitivity in settings, tried uninstalling then re-installing rainmeter, spotify, and monstercat. I've tried hitting refresh all multiple times. I've ensured that all my drivers (Realtek) are updated. I've tried uninstalling Realtek, but then sound just completely doesn't work, and I don't know of any other drivers I can use. I read somewhere that removing Sonic Studio worked, but I tried it myself and still nothing. 

### Versions

* Rainmeter Version: 4.2.0 beta r3011
* OS Version: 
* Skin Version: 1.8.1
* Spotify Version: 1.3.0.1

**Comment by MarcoPixel** [comment]
Sorry for the late response!

Did you try out all the different steps in the [Troubleshooting AudioLevel plugin](https://forum.rainmeter.net/viewtopic.php?p=123883#p123883) forum post?

If yes, please send a screenshot from the debug log of Rainmeter (https://docs.rainmeter.net/manual/user-interface/about/) and post it in here.

**Comment by lezombie** [comment]
Hey, no worries!

Just managed to solve it the other day. Rolled back the update on my audio driver, then re-installed the update. That did the trick, though I’m not entirely sure why. Thank you for getting back to me though :)
