### ISSUE TITLE
Strange bug with last bar

### ISSUE THREAD

**Issue by Creedoo** [MarcoPixel/Monstercat-Visualizer#126]
So, everytime that skin is loaded, the last bar in visualizer isn't "hidden", it's just staying still, doesn't matter if the music is playing or not (while the music is playing it's bouncing but keeps it's level and doesn't go below it). I tried to change bar count (sometimes it's working, sometimes not, sometimes if I change for example from 23 -> 24 it glitches out and "copies" the bug on 24 bars), tried refreshing skin, uninstalling it, uninstalling even rainmeter but it doesn't work.

* Rainmeter Version: 4.1.0 r2989 32-bit
* OS Version: Windows 7 Ultimate 64-bit (build 7601 + Service Pack 1)
* Skin Version: 1.8.1
* Spotify Version: I'm not using it, I use WMP to play music

Here's screenshot how it looks like:
![ughywyghy](https://user-images.githubusercontent.com/34888015/34382296-25e8fa00-eb0e-11e7-9d33-b1a0483fd590.png)

**Comment by MarcoPixel** [comment]
Sorry for the late response!

Might be an issue with the `FreqMax` variable, try changing this to a lower value (around 15000).

To access the variables, right-click the skin and press on **Open variables file** and it will open the file in Notepad.

**Comment by Creedoo** [comment]
Now sorry for my late reply ;P

Seems that it's working for now but I can't guarantee, sometimes it works normally but usually this bug happens... I'll will be testing it everyday now and tell something changes, for now thanks :smile:

**Comment by Creedoo** [comment]
Well, literally after another PC start-up this bugged popped up, I changed the FreqMax to 14500, 14750 and 15000 but without any luck :c Also I just came across another bug, this one makes that visualizer don't see any music playing - or to be exact, it sees that something is playing and shows it but when I i.e. check "hide visualizer when music is not playing" it hides :disappointed: also it shows the artist and title as N/A 
![image](https://user-images.githubusercontent.com/34888015/34613697-f386d37a-f22e-11e7-80f4-a812ea753b07.png)

**Comment by tjhrulz** [comment]
The N/A bugs are something else that is going on, is that happening with Windows Media Player as the player?

Also do you have any software on your computer that would be modifying your sound profile (Sometimes those can cause the top frequency to have issues so try going even lower yet until it stops happening)

**Comment by Creedoo** [comment]
Wow, sorry for keeping you wait, I didn't think someone will reply to this issue anymore D:

For the N/A bug, yup, it was happening when WMP was the player or Chrome but I guess that's normal

And no, I didn't have any software that would be modifying sound profile, all I heard was just raw, real sound without any "upgrades"

Also I should mention that this bug didn't appear since then so maybe it was like a one-time glitch or something :\

**Comment by RobertFrydenlund** [comment]
This actually happens to me quite frequently, I'd say 1/10 times on average. The length of the last bar varies  as well. I thought this was the last bar freezing on the current value, but it seems it can happen without any sounds playing at all. The last bar still grows when sound is playing, as if the working bar started from the top of the frozen bar. I get some weird errors, but this seems to happen regardless of whether the bug occurs or not. Also worth noting that i am using the standalone installation of Rainmeter. Refreshing the skin does not help.
![error](https://user-images.githubusercontent.com/4069790/37920230-9401919c-3126-11e8-9d33-4687e9e160c0.png)

**Comment by RobertFrydenlund** [comment]
@MarcoPixel Increased the bar count to 64, seems like it is working as intended now
