### ISSUE TITLE
Can You Intergreate Musixmatch Lyrics Support

### ISSUE THREAD

**Issue by fhbncghdytgf** [MarcoPixel/Monstercat-Visualizer#128]
I Want To See The Lyrics So Can You Intergrate Musixmach liyrics
[Click Here](https://developer.musixmatch.com)

**Comment by MarcoPixel** [comment]
This issue is not following the existing issue template and thus will be closed.

**Comment by fhbncghdytgf** [comment]
@MarcoPixel DO IT NOW!!!!!!!!!!!!!!!!!!!! OTHERWISE IM ANGRY!!!
