### ISSUE TITLE
WebNowPlaying doesn't work...

### ISSUE THREAD

**Issue by MisterThePiG** [MarcoPixel/Monstercat-Visualizer#130]
### Description

Song information and vizualizer doesn't work with webnowplaying but with media player it's run it perfectly....

### Versions

* Rainmeter Version: 4.1 Final Release - r2989
* OS Version: Windows 7  
* Skin Version: Monstercat-Visualizer-1.8.1
* Soundcloud, Youtube

### Additional notes/images

![monstercatdoesntwork](https://user-images.githubusercontent.com/35738190/35289521-de6aa7d6-0067-11e8-9185-a9e599e3bc18.png)

I've already search on others issues and no one can help me.

**Comment by tjhrulz** [comment]
Double check that Rainmeter is not blocked by your Rainmeter firewall. https://github.com/tjhrulz/WebNowPlaying-BrowserExtension/wiki/Troubleshooting#windows-firewall-is-blocking-rainmeter-requests

**Comment by gustavolvieira** [comment]
I had the same problem, and found out [here](
 https://forum.rainmeter.net/viewtopic.php?t=26619) I needed to change firefox configs.

> Note: While chrome requires no changes in Firefox you will need to go to the about:config page in Firefox and set network.websocket.allowInsecureFromHTTPS to true.

I think it might be useful to update the wiki with this info!

**Comment by tjhrulz** [comment]
It's on the webnowplaying Wiki and on the add-on download page but yeah I should add it to the wiki here. I need to investigate if I can tell if that setting is blocking me.

However the screenshot is of chrome so the only issue should be firewall, antivirus, or that MV is set to a different player

**Comment by MisterThePiG** [comment]
I've authorized firewall also it doesn't work, but now I've got message from WebNowPlaying which said "Not connected to Rainmeter. Click to troubleshoot".
 This is not my antivirus, I turn it off and nothing happen. 
What do u mean by MV ? (sorry i'm french xD )

![autorisation](https://user-images.githubusercontent.com/35738190/35449935-c1cf5aa0-02be-11e8-8d74-0274ef5af003.png)

Thanks a lot for your help :)

**Comment by tjhrulz** [comment]
MV stands for Monstercat visualizer, is was on mobile at the time and was being lazy 😋

**Comment by MisterThePiG** [comment]
Reboot doesn't work... 
So sad can't use WNP :'(

**Comment by tjhrulz** [comment]
What is your network setup like? Are you on a more restrictive setup at a university? 

Have you tried using it on another machine to see if maybe another program on your desktop is interfering with WebNowPlaying?

**Comment by MisterThePiG** [comment]
When I go in the plugins tab I see "NowPlaying         *As an internal measure" :x 
I didn't try with another pc

**Comment by MisterThePiG** [comment]
So I don't have this plugin active in Rainmeter, don't know how he still don't be active '-'
Do you got any solution ? Did I made the installation wrong ? Also I just download WebNowPlaying and do anything else...

**Comment by tjhrulz** [comment]
Then you never installed the WebNowPlaying plugin. You need to install the .rmskin or copy the plugins in to the correct folder if you are doing a manual install and it will work fine.

**Comment by qua9chuoi9** [comment]
> Then you never installed the WebNowPlaying plugin. You need to install the .rmskin or copy the plugins in to the correct folder if you are doing a manual install and it will work fine.

Copy exactly plugin WebNowPlaying follow rainmeter x32 or x64 to Rainmeter\Plugins\WebNowPlaying.dll. replace it.
