### ISSUE TITLE
Feature Request: Visualizer turned off only when no audio is played at all

### ISSUE THREAD

**Issue by NorthLake** [MarcoPixel/Monstercat-Visualizer#131]
Maybe an option to only make the visualizer hide when there is no audio at all, instead of it listening to the media players would be nice? This is handy for audio playing from YouTube, for example. Just a suggestion, though...

**Comment by tjhrulz** [comment]
There are two options that do this right now, one will ignore all sounds when music is not currently playing and the other will hide Monstercat visualizer when it is not playing
