### ISSUE TITLE
Unknown genre default to electronic colors (Suggestion)

### ISSUE THREAD

**Issue by pixelsandbacon** [MarcoPixel/Monstercat-Visualizer#132]
Would it be possible to make it so that if a known genre name isn't detected it changes the color to electronic?

**Comment by MarcoPixel** [comment]
You can change the default color by going into the Settings > Styling.

**Comment by pixelsandbacon** [comment]
Didn't do anything. I mean, I have dynamic genre colors turned on, and
whenever I play a song with a genre other than an official Monstercat one
it uses the previous song's color.

**Comment by MarcoPixel** [comment]
Which media player are you using?

**Comment by pixelsandbacon** [comment]
iTunes
