### ISSUE TITLE
Support for Windows 10 Soundcloud Client

### ISSUE THREAD

**Issue by daditz** [MarcoPixel/Monstercat-Visualizer#133]
So i just found out that soundcloud has windows 10 client, maybe a support for this app in the future?

**Comment by MarcoPixel** [comment]
As the SoundCloud app is not supported by any of the used plugins, it won't work now.
It seems that the official app doesnt have any APIs so with the current state its also not possible to easily add this to Rainmeter.

But you can use the **WebNowPlaying** plugin to use Soundcloud in your webbrowser.
