### ISSUE TITLE
iTunes Crashing when playing media

### ISSUE THREAD

**Issue by Tempusernameiguess** [MarcoPixel/Monstercat-Visualizer#134]
[IMPORTANT: Please remove or replace everything between two square brackets ( [ ] ) before posting your issue.]

### Description

[After installing, going through setup and customization, I attempted to use iTunes (my source of media of choice) however when playing a song, Rainmeter completely stopped working. I tried deleting and reinstalling your visualizer, checking for updates on Rainmeter, and nothing seemed to work. I currently have a honeycomb skin on with 29 buttons but have not had any problems before that made the entire thing stop working]

### Versions

[Monstercat visualizer Version: 1.81
Rainmeter Version: 4.1]

[You can remove this section when posting an feature request]

* Rainmeter Version: [You can check this here: https://docs.rainmeter.net/manual/user-interface/about/#VersionTab]
* OS Version: [You can check this here: https://docs.rainmeter.net/manual/user-interface/about/#VersionTab]
* Skin Version: [You can check this here: Right-Click the Skin -> Open variables file. It should be at the top of the file]
* Spotify Version: [You can check this here: https://docs.rainmeter.net/manual/user-interface/about/#PluginsTab]

### Additional notes/images

[If you have any additional infos you can give us, please write them down]

**Comment by tjhrulz** [comment]
Update to Rainmeter 4.2 beta to resolve this issue.
