### ISSUE TITLE
Feature Request - New Visual

### ISSUE THREAD

**Issue by matheustsa** [MarcoPixel/Monstercat-Visualizer#136]
Hello!
I'm trying to make the visualizer (and the progress bar) rounded, like VisBubble or Orbit.
The main reason is beacause monstercat seems a more fluid/smooth player that these others.

Examples: 
VisBubble - https://undefinist.deviantart.com/art/VisBubble-Round-Visualizer-for-Rainmeter-488601501
Orbit - http://jseapplications.com/rmskins.php

The progress bar is almost ready, along with rearranged player controls, music title, etc.
But, how can I make the bars rounded?

**Comment by MarcoPixel** [comment]
The skin is not supposed to be a universal one with different modes, its designed to be similar to the visualizer in the videos so there won't be a round one.

You can try and fiddle around the settings in the other visualizers to get closer to the wanted result or you can try replacing the measure file from my skin to the others and see if it works. :)

**Comment by tjhrulz** [comment]
As for how best to edit it editing the scripts to generate the bars and their shadows would be quickest. Options can be defined here: https://github.com/MarcoPixel/Monstercat-Visualizer/blob/master/visualizer.ini#L63
