### ISSUE TITLE
Cover and Artist stays the same

### ISSUE THREAD

**Issue by MichaelJZ3377** [MarcoPixel/Monstercat-Visualizer#137]
### Description

When loading song cover and song information the cover image and artist name remain the same except the name song

### Versions
Monstercat Visualizer 1.8.1

* Rainmeter Version: Final 4.1
* OS Version: Windows 10 Pro
* Skin Version: 1.8.1

### Additional notes/images
![issue](https://user-images.githubusercontent.com/36273020/35984820-8077bf20-0cf5-11e8-98ce-cfbb61d21f21.gif)

![issue](https://user-images.githubusercontent.com/36273020/35984842-8cba2f3e-0cf5-11e8-9ef1-a1fb30f49961.gif)

**Comment by tjhrulz** [comment]
Upgrade to the Rainmeter 4.2 beta
