### ISSUE TITLE
Progress bar not matching length of EQ bars

### ISSUE THREAD

**Issue by mrmonkeyninja** [MarcoPixel/Monstercat-Visualizer#138]
Lined up visualizer with corner of screen, turned on progress bar. Progress bar is to long when compared to EQ bars.

Rainmeter Version: 4.1.0 r2989 64-bit (Nov  6 2017)
OS Version: Windows 10 Education 64-bit (build 16299)
Skin Version: 1.8.1
Spotify Version: 1.3.0.0

![image](https://user-images.githubusercontent.com/36406726/36095365-0c7d659e-1046-11e8-86de-89f3ca30f367.png)

**Comment by tjhrulz** [comment]
Could you grab your variables.ini file (its under @resources under the skin folder in your document) and upload so I can test at home.

My bet is that I off by one bugged it somehow with my changes to that a while back that made it more pixel perfect. 
(Also I would recommend upgrading to the Rainmeter betas to prevent a potential crash with iTunes but that is unrelated to this)

**Comment by mrmonkeyninja** [comment]
I assume this is what you're asking for.

[Variables]
Version=1.8.1
;==========================
; General settings
;==========================

PlayerName=Spotify
; Change this variable to your media player.
; Visit this page for all supported players:
http://docs.rainmeter.net/manual/plugins/nowplaying#playerlist

ScaleVisualizer=0.54
; Changes the size of the visualizer
; Can be anything between 0.1 (really small) to 1.0 (fullscreen).
; Default: 0.8

ScaleSongInformation=0.9
; Changes the size of the song information skin.
; Can be anything between 0.1 (really small) to 1.0 (fullscreen).
; Default: 0.8

Angle=0
; Change the orientation of the visualizer in degrees.
; Default: 0

;==========================
; Spectrum settings
;==========================

AverageSize=8
; Higher numbers = smoother visualization, but with delay
; Lower numbers = faster visualization, but less smooth
; This will increase/decrease performance and the quality of the
visualization.
; Default: 3

BarWidth=18
; Width of the visualizer bars, don't go lower as 6 or the rounded edges
will dissolve.
; Default: 18

BarHeight=186
; Height of the visualizers bars in Pixels. Also allowed are percentages
based on the screen size.
; Default: 350

BarGap=7
; Margin between the different visualizer bars.
; Default: 7

BarCount=100
; Number of the visualizer bars, maximum 100.
; Default: 63

MinBarValue=0.01
; Bars shown at the bottom of the visualizer bars.
; Increasing the value will make the bars bigger, decreasing it smaller.
; Default: 0.01

Sensitivity=24
; A number specifying in what dB range the measure will return FFT and Band
data.
; Increasing this value will make the visualizer respond to quieter sounds
and make the graph bigger, decreasing it will show louder sounds.
; Default: 35

FFTSize=4096
; A number value for the frequency resolution of the output data.
; Increasing this value will add more cpu load, so keep it for the best
result on this value. If you have a slower pc change the value to 512 or
256.
; This will increase/decrease performance and the quality of the
visualization.
; Best kept at default values.
; Default: 4096

FFTAttack=100
; Time in Milliseconds till the bars rise to the signal level.
; Higher values adds delay to the visualization, but makes it much smoother
and calmer.
; Best kept at default values.
; Default: 100

FFTDecay=60
; Time in Milliseconds till the bars fall from the signal level.
; Higher values will keep the bars much longer visible, lower values makes
it more "jumpy".
; Best kept at default values.
; Default: 60

FreqMin=25
; Minimum frequency detected by the visualizer.
; Default: 20

FreqMax=16500
; Maximum frequency detected by the visualizer.
; Default: 16500;

InvertVisualizer=0
; Inverts the spectrum/visualizer.
; Default: 0;

;==========================
; Style settings
;==========================

font1=Nexa Bold
font2=Nexa Light
; Fonts used for the title and artist.
; Font1 is for the Artist, Font2 for the Title
; Default: font1=Nexa Bold, font2=Nexa Light

FontSize1=72
FontSize2=40
; Font sizes for the title and artist.
; Font1 is for the Artist, Font2 for the Title
; Default: FontSize1=72, FontSize2=40

TextColor=E3E3E3
; Color used for text.
; Default: #White#

Color=D6D6D6
; Color of the visualizer bars/monstercat cover in RGB(a).
; This is the default color when genre-based colors are activated.
; You can change the color to one of the following genres (in the list) by
writing the genre like this: #Dubstep#

; This is the color list for the genre-based colors in RGB(a).
EDM=193,193,193
Electro=230,206,0
House=234,140,6
DnB=242,25,4
Dubstep=141,4,225
Drumstep=243,33,136
GlitchHop=11,151,87
Trap=140,15,39
Trance=0,126,231
HardDance=1,151,0
NuDisco=28,171,179
FutureBass=154,152,252
White=255,255,255
Black=0,0,0

EnableDynamicColors=0
; Changing this value will enable/disable dynamic colors.
; There are three different settings you can choose.

; 0 - OFF, all dynamic color settings disabled.

; 1 - GENRE, color will change dynamically to the genre of the song.
;     This will work currently only on AIMP, CAD, iTunes, WMP and Winamp.
;     Also the song needs Genre ID3 tags.

; 2 - COVER, color will change dynamically to the cover art of your song.

; This will have an major impact on the performance of the visualizer and
your CPU.
; Turn off if you experience lags or slowdowns.
; Default: 0

DisableDynamicFontColors=1
; Changing this value will enable/disable dynamic font colors.
; There are three different settings you can choose.
; Default: 1

ShowMonstercatCover=0
; Changing this value will replace the song cover with an full-color cover
with the monstercat logo (like in the videos).
; Default: 0

NoArtistNameText=
NoTrackNameText=
; This will replace the replacement text when there's no track name/artist
or if nothing is playing.
; Default: NoArtistNameText=N/A, NoTrackNameText=N/A

DisableAutoHide=1
; Changing this value will hide the Visualizer when not playing.
; Default: 1

DisableAutoMute=1
; Changing this value will make the Visualizer ignore sound when not
playing.
; Default: 1

HideProgressBar=0
; Changing this value will hide the progress bar below the visualizer.
; Default: 1

ClipSongInformation=1
; This will clip the song information to fit exactly under the visualizer.
Longer song names or artists will get clipped at the size of the visualizer
bars.
; Default: 1

AddTextBorder=0
; This will add a border to the song information to make it easier to read
on bright wallpapers.
; Default: 0

BorderColor=0,0,0
; Color used for border.
; Default: 0,0,0

EnableDropShadow=1
; This will enable a drop shadow below the visualizer and song information.
; Default: 1

DropShadowColor=0,0,0,75
; Color of the drop shadow.
; Default: 0,0,0,75

;=====================================================

; These variables are constants and are better untouched! Changing here
will probably break something.
DefaultHeight=(#WORKAREAHEIGHT#/3)
BarCountCalc=(#BarCount#+1)
GenreColor=#Color#
MPMode=Spotify
SettingsHeight=570
Config=monstercat-visualizer
Matrix=(Cos(145*PI/180));(-Sin(145*PI/180));(Sin(145*PI/180));(Cos(145*PI/180));286.70322;974.85043
NearestAxis=0
AudioDeviceID=
SkinWidth=(((#BarGap#*#ScaleVisualizer#*#BarCount#)+(#BarWidth#*#ScaleVisualizer#*#BarCount#))
- (#BarGap#*#ScaleVisualizer#))

**Comment by MarcoPixel** [comment]
Fixed with https://github.com/MarcoPixel/Monstercat-Visualizer/commit/afc919fa2020ce680a161924afb32994f71bab3b, check out the manual installation on the projects main page.
