### ISSUE TITLE
Playing certain songs causes Rainmeter to crash

### ISSUE THREAD

**Issue by TheFrozenSlime** [MarcoPixel/Monstercat-Visualizer#141]
### Description

I moved to a new computer recently, and part of that entailed moving my songs from one computer to the new one. I put them on a flash drive and added them to iTunes on the new computer, so there were no changes to the file. Playing certain songs now causes Rainmeter to crash; I've noticed that these are songs that I downloaded that came with very little to no id3 tags, and are in the "Unknown Artist" file in iTunes. It started as the skin not showing the artist name, album art, or updating genre colors for the song, but now they just crash Rainmeter entirely. On the old computer (Windows 7 Professional, with the same Rainmeter version and Skin version 1.7.0) I could play these songs with no issue. 

### Versions

* Rainmeter Version: 4.1.0 r2989 64 bit
* OS Version: Windows 10 Pro 64 bit, Version 1709, Build 16299.248
* Skin Version: 1.8.1

### Additional notes/images

Not all of the songs in the "Unknown Artist" folder will cause Rainmeter to crash; Rainmeter crashes even when the problem songs are paused. [This](https://gyazo.com/d8ab0e35871b25aa7e3d20664682c0c4) is the error I get.

**Comment by tjhrulz** [comment]
Update Rainmeter to the [4.2 Beta](https://github.com/rainmeter/rainmeter/releases/download/v4.2.0.3029/Rainmeter-4.2-r3029-beta.exe) to fix this issue.
