### ISSUE TITLE
Change Audio Device Changes and Visualizer Doesn't Realize Audio Device Changed

### ISSUE THREAD

**Issue by Sleetui** [MarcoPixel/Monstercat-Visualizer#142]
### Description

I have multiple audio speakers hooked to my computer.  Sometimes I switch to my headset or back to my default speakers.  I'm on Windows 10 and easily change the default audio speaker to something else near the notification area.  Upon changing the audio speaker, the Visualizer isn't "paired" to the current audio speaker I'm using.  So, I have to manually go into the Visualizer setting and change it to Default so it will "pair" with my current speaker.  Is there something better I can do besides manually changing it?

### Additional notes/images

None

**Comment by tjhrulz** [comment]
We have actually already implemented this feature already (I was just fixing a bug with it a few moments ago) it just is not part of the latest official release and so you must manually install the latest version from github.
Steps to manually install the most up to date version of monstercat visualizer can be found [here](https://github.com/marcopixel/Monstercat-Visualizer/#manual-installation)

**Comment by Sleetui** [comment]
Replaced almost all the plugins besides the Spotify one.  Needed Admin Rights or something.  Should the feature just work automatically?  Or do I have to configure an option?

**Comment by tjhrulz** [comment]
No it's on by default but it has nothing to do with plugins (the plugin it needs is included with rainmeter) you need to manually install the skin part too as that was where it is implemented
