### ISSUE TITLE
Custom Color Transparency Issue

### ISSUE THREAD

**Issue by Sleepy-Nug** [MarcoPixel/Monstercat-Visualizer#143]
### Description

Anytime I try to use the custom colors for the skin, they appear as if the transparency is set to ~100; however, the value is still at 0% according to all indications. Can't seem to find a way around this issue.

### Versions
Everything is the newest version: Rainmeter, the skin, and Spotify are all completely up to date.
Running Win7.

**Comment by tjhrulz** [comment]
We are gonna need more info, can you upload to modifications you made?

**Comment by tjhrulz** [comment]
Closing due to lack of info
