### ISSUE TITLE
Audio visualization doesn't work (Realtek)

### ISSUE THREAD

**Issue by og-rahoon** [MarcoPixel/Monstercat-Visualizer#145]
I installed Monstercat Visualizer, and I have the same problem as most other people, the visualizer doesn't move. The spotify plugin is fine and I know I have to uninstall Realtek to get the visualizer working but if I uninstall Realtek then I loose sound through my headphones. 

* Rainmeter Version: 4.2.0
* OS Version: Windows 10 Home 64 Bit
* Spotify Version: 1.3.0.0
#93

**Comment by tjhrulz** [comment]
You should have no issues after a reboot

**Comment by og-rahoon** [comment]
Which reboot?

**Comment by tjhrulz** [comment]
Not sure, feel free to try and report back.

**Comment by og-rahoon** [comment]
So i uninstalled realtek and rebooted it but still can't get sound from headphones.

**Comment by tjhrulz** [comment]
Go into the windows device manager and find the device and tell windows to install the drivers for it

**Comment by og-rahoon** [comment]
There are none

**Comment by MarcoPixel** [comment]
@og-rahoon Any progress on the issue?

**Comment by Ruben533** [comment]
If you open your menu and check bar count what do you see? Because I have a similar issue where if you want to change the bar count it goes to 0 and it becomes unable to move to a higher count. What makes it invisible.

- Rainmeter 4.2.0
- OS: Windows 10 Prof  64 bit

**Comment by MarcoPixel** [comment]
@Ruben533 Sounds like the Mouse plugin wasn't properly installed, try to run the rmskin and install all necessary plugins.

**Comment by Ruben533** [comment]
Thank you for your feedback. I will try 👍

**Comment by Ruben533** [comment]
I'm sorry I've mistaken myself I've checked again and it was bar width that jumps to 0 and you cant move the bar count works just fine. :/  Sorry

**Comment by MarcoPixel** [comment]
@Ruben533 If your problem is still there and it is not the same, i would recommend to create your own issue so we don't clutter this one. :)
