### ISSUE TITLE
Artist Name displays too many characters

### ISSUE THREAD

**Issue by DDarkstorm** [MarcoPixel/Monstercat-Visualizer#146]
### Description

So I used this skin for quite a long time, but i recently saw that if my artist name is too long, it will go on my others skins. Is there anyway to clip the artist name with fewer characters? I don't want to change the size since it's perfect in height.

### Versions

* Rainmeter Version: [4.1.0 r2989]
* OS Version: [Windows 10 Home 64bit]
* Skin Version: [1.7]

### Additional notes/images

![eeizerz](https://user-images.githubusercontent.com/9608429/37165913-08e530d6-22fe-11e8-8334-2ca18f882de3.jpg)

**Comment by tjhrulz** [comment]
Likely related to https://github.com/MarcoPixel/Monstercat-Visualizer/issues/138

**Comment by MarcoPixel** [comment]
Should be fixed with https://github.com/MarcoPixel/Monstercat-Visualizer/commit/afc919fa2020ce680a161924afb32994f71bab3b, check out the README for the manual installation for now.
