### ISSUE TITLE
Doesn't recognize MusicBee as player and won't unhide

### ISSUE THREAD

**Issue by Nazenn** [MarcoPixel/Monstercat-Visualizer#15]
Recently downloaded this skin and absolutely loving it however when trying to use the option "Hide skin when media player is not running" and also selecting MusicBee as the player in the Media Player option then the skin is permanently hidden. 
Turns out this is because of an issue with not having Edit > Preferances > Plugins > CD Art Display enabled within Music Bee itself. Its probably very helpful if you were to add that to your FAQ as well as that's not enabled by default

**Comment by MarcoPixel** [comment]
Thanks for your report. I've added the necessary steps to the Troubleshooting Wiki.
