### ISSUE TITLE
Visualization Bar Width stays at zero

### ISSUE THREAD

**Issue by Ruben533** [MarcoPixel/Monstercat-Visualizer#150]
I have the had the visualizer for about a year and I am very positive, it just loos very smooth and clean. But two weeks ago I switched to a new laptop and had to reinstall the plugin. But because I don't want to have a very large bar on my small screen I usually adjust the bar with to a few pixels. But now if I want to adjust it to a few pixels the Bar with jumps to 0 and stay's there and the visualizer disappears. If I want to see the visualizer again on my monitor I have to reinstall the plugin.

I have put a screen recording as a zip file down below so you can see what the problem is.

- OS windows 10 pro 64 bit

- Visualizer version 1.8.1

- Rainmeter 4.2.0

[2018-03-21-01-28-22.zip](https://github.com/MarcoPixel/Monstercat-Visualizer/files/1831700/2018-03-21-01-28-22.zip)

**Comment by MarcoPixel** [comment]
Seems like an issue with the Mouse plugin, please send a screenshot of the Plugins tab (https://docs.rainmeter.net/manual/user-interface/about/#PluginsTab) so i can check out which version you have installed.

**Comment by Ruben533** [comment]
Here is a screenshot of all my plugins installed.

![plug-ins rainmeter](https://user-images.githubusercontent.com/35854799/37720100-d4baf9d4-2d26-11e8-8912-3c989c3b5def.png)

**Comment by MarcoPixel** [comment]
Download the latest version of the visualizer, open the RMSKIN file and install all necessary plugins.

Check if all plugins are checked and on the latest version.
![grafik](https://user-images.githubusercontent.com/3743025/37722346-182f265e-2d2c-11e8-9f59-ed96b11731b8.png)


Download: https://github.com/MarcoPixel/Monstercat-Visualizer/releases

**Comment by Ruben533** [comment]
Thank you my problem is solved. 👍

**Comment by MarcoPixel** [comment]
Glad that it got all sorted out 👍
