### ISSUE TITLE
Update Rate on Artist/Track

### ISSUE THREAD

**Issue by luisg0nc** [MarcoPixel/Monstercat-Visualizer#153]
Artist and Track information have an update rate of 50, this is extremely fast as a default value.
If these meters are scaled up it will start consuming a lot of CPU.

* Rainmeter Version: 4.1.0 r2989 64-bit (Nov  6 2017)
* OS Version: Windows 10 Pro N 64-bit (build 16299)
* Skin Version: 1.7.0

**Comment by tjhrulz** [comment]
It's a string meter that does not have dynamic variables on, it is not going to use any CPU. Sure it could be made to be 100ms like the measure it pulls from but if we are worried about CPU that is the last area I would focus on.

If we really wanted to have a much better CPU version of MV we would probably just start from scratch as I (and I am sure Marco) know way more about how to make a very CPU efficient skin these days than we used to.
