### ISSUE TITLE
Slider alternative

### ISSUE THREAD

**Issue by joshuah345** [MarcoPixel/Monstercat-Visualizer#154]
### Description
Feature Request
i have a hi dpi display and the sliders in settings can be hard to drag, implement a simple way to edit the amount such as typing it.

**Comment by MarcoPixel** [comment]
Edit the values via **Right-Click -> Open Variables** file or use your mouse scroll to move the values by 1.

**Comment by tjhrulz** [comment]
@MarcoPixel We should maybe look at making the settings menu aware of the resolution of the screen it is on and scale better, it wouldn't be aware of the be DPI aware but at least for hi DPI screens it will be nicer
