### ISSUE TITLE
Reduce idle visualizer CPU load

### ISSUE THREAD

**Issue by suffixGITHUB** [MarcoPixel/Monstercat-Visualizer#16]
I'm very sorry if this isn't the place for this. I have no technical understanding of coding (Please bear with me.)
I'm on latest Rainmeter (non-Beta) and Monstercat Visualizer. Settings left as is.

With visualizer.ini loaded, my CPU load on Rainmeter.exe increases by 7% (total 10%) when no media player is running.
I'm certain processing power is sufficient as I'm on a powerful system and total CPU load doesn't go over 3% even with tons of other widgets and live wallpaper loaded.

Any way to reduce idle load?

**Comment by MarcoPixel** [comment]
Do you have dynamic colors active?
Because these settings use a lot of CPU power.

Also please send your OS, Rainmeter version and skin version. Also please send a screenshot from the debug log of Rainmeter (https://docs.rainmeter.net/manual/user-interface/about/)

**Comment by suffixGITHUB** [comment]
You're right, CPU load reduced significantly when I unticked dynamic colors.

May I ask why exactly CPU load is so high with dynamic colors even without any media player active?
Is it possible for you to implement a switch (dynamic and static color) based on if any media player is running, just like the hide feature? Wouldn't this solve the idle CPU load issue?

Thanks very much, I also attached the logs if these are any relevant.

OS: Windows 10 Pro x64 latest build and updates
Rainmeter version: 4.0.0 r2746 64 bit
Skin version: v1.5.3

![logs idle](https://cloud.githubusercontent.com/assets/25638014/22739180/d8dab68c-ee0a-11e6-9c1c-bee98ea69d7d.png)

**Comment by MarcoPixel** [comment]
Because the colors get updated every 10ms and every time a update happens the plugin needs to load the file for the covers. I'm currently working on optimizing the skin so maybe one of the next few updates will help with the issue.

You can also try to reduce the sound resolution to 1024 or 2048 and try if you still got high cpu usage.

**Comment by MarcoPixel** [comment]
Also the settings skin (where you can adjust the skin) is currently really unoptimized and probably one of the main issues with performance.

**Comment by tjhrulz** [comment]
I think I'll make that fork I was talking about before and attempt to bring down cpu

**Comment by MarcoPixel** [comment]
It seems most of the issues are resolved with the last update, so i'm gonna close this issue for now. If you still have any improvements which i can do, please make a pull request with the changed files and i will check them out.
