### ISSUE TITLE
Transform this widget in a window to get easy window capture for obs in stream

### ISSUE THREAD

**Issue by flavius1995** [MarcoPixel/Monstercat-Visualizer#161]
[IMPORTANT: Please remove or replace everything between two square brackets ( [ ] ) before posting your issue.]

Transform this widget in a window to get easy window capture for obs in stream

[Please explain your problem here, tell all the step you've taken and how you found the issue.]

OBS can't get monstercat visualizer with rainmeter as a window and capture it 

[IMPORTANT: Please fill out the version numbers so we can properly look for your issue.]

[You can remove this section when posting an feature request]

* Rainmeter Version: [You can check this here: https://docs.rainmeter.net/manual/user-interface/about/#VersionTab]
* OS Version: [You can check this here: https://docs.rainmeter.net/manual/user-interface/about/#VersionTab]
* Skin Version: [You can check this here: Right-Click the Skin -> Open variables file. It should be at the top of the file]
* Spotify Version: [You can check this here: https://docs.rainmeter.net/manual/user-interface/about/#PluginsTab]

### Additional notes/images

[If you have any additional infos you can give us, please write them down]

**Comment by MarcoPixel** [comment]
This is currently not possible with Rainmeter as OBS can't capture so called "layered windows" which Rainmeter uses.

Read more about this issue here: https://forum.rainmeter.net/viewtopic.php?t=27305
