### ISSUE TITLE
Resizing cover

### ISSUE THREAD

**Issue by newtothisstuff** [MarcoPixel/Monstercat-Visualizer#162]
[Resizing feature]

### Description

I'm trying to make the cover such that i can overlay it over my taskbar so i can easily change the song, however the square format doesn't allow it. My question is, where are the settings in the mediaplayer so that i can make it a rectangle *if possible*?

**Comment by MarcoPixel** [comment]
There is no setting to change the cover size as nearly all covers supplied by media players are square. If you still want to proceed, you need to change the **width** and **height** values in the **Cover.ini** file. I will not add a cover size feature as it's really easy to do it yourself with a little bit of work. 

You can learn more about customizing skins in the documentation here: https://docs.rainmeter.net/manual-beta/getting-started/customizing/
