### ISSUE TITLE
Skin Can't Detect Spotify Audio

### ISSUE THREAD

**Issue by memoeries** [MarcoPixel/Monstercat-Visualizer#163]
### Description

With the ignore sound option turned on with Spotify enabled the visualizer doesn't move

### Versions

Rainmeter 4.1
Win 10 Pro 64-bit build 16299
Skin ver 1.8.1
Spotify ver 1.3

**Comment by MarcoPixel** [comment]
This is also a sideeffect of the issue caused by a recent Spotify update, go to #144 for more information.
