### ISSUE TITLE
Some background module ails

### ISSUE THREAD

**Issue by B-Leeve** [MarcoPixel/Monstercat-Visualizer#164]
### Description

Hi Marco, I was just wondering something, since I absolutely love your automatic color picker for album art that changes the visualizer colors depending on said color. I was just wondering if I could somehow get the background module to change to the opposite / negative color of the album art color, or at least to white if the color is dark and to black if the color is light. 

I've been digging around your code and I've used this module for years but I'm not sure how to do it. Any insight? Also, keep doing God's work man this visualizer is not only aesthetically pleasing but extremely easy to configure as well. All the best!

### Versions

* Rainmeter Version: 4.1.0 r2989 64-bit (Nov 6 2017, latest I believe)
* OS Version: Windows 7 Professional SP1 (build 7601)
* Skin Version: 1.8.1
* Spotify Version: 1.3.0.0

**Comment by MarcoPixel** [comment]
Replace your background.ini with this file: https://gist.github.com/MarcoPixel/5e735325f12a9f793cbcb054eb083061

You can change the color fetched from the plugin by modifying the ` Color` variables.
Read the documentation of the plugin for more info: https://github.com/socks-the-fox/chameleon

**Comment by B-Leeve** [comment]
Thank you so much Marco! Good luck with any future projects you have!

And thanks for sticking with this one for so long, I've been using this for years now!

**Comment by B-Leeve** [comment]
Okay sorry to bother you again Marco, but since the bars can change colors to pretty much any color, it is hard for them to be visible against the background. I'm trying to get the background to dynamically change to something that will allow the bars to be visible.

I am trying to do this by making the background change to something that is the "opposite" (is that even possible with color arrays?) of the MeasureCoverBG color. Maybe making it the opposite will be hard, but perhaps even an if statement saying "if the total of R, G, and B is higher than half of 255, 255, 255, then change background to black, and if else make it white" would work. No idea how to do this though, 

I've been fiddling with the inc and lua files but I've got no idea how this Rainmeter language works. I'm not proficient with code even in normal circumstances but this is something else! Any help would be appreciated greatly.

**Comment by MarcoPixel** [comment]
I really recommend you to go to the documentation and read the [Getting Started](https://docs.rainmeter.net/manual-beta/getting-started/) if you want to customize your skins more.

Chameleon can generate multiple colors from one image, so you can set it to different ones.

Try changing [line 34](https://gist.github.com/MarcoPixel/5e735325f12a9f793cbcb054eb083061#file-background-ini-L34) to one of the following:

> 
> `Color` can be one of:
> 
> * `Background1`
> * `Foreground1`
> * `Background2`
> * `Foreground2`
> * `Light1`
> * `Light2`
> * `Light3`
> * `Light4`
> * `Dark1`
> * `Dark2`
> * `Dark3`
> * `Dark4`
> * `Average` which is the overall average color of the image
> * `Luminance` which is not a color, but rather a floating point value
> between 0 and 1 indicating the average luminance of the image.

If you still want more granular control over the colors, you could also try working with [IfConditions](https://docs.rainmeter.net/manual-beta/measures/general-options/ifconditions/) and see if they would work.

Also i recommend you to go to the [Rainmeter Discord](https://discordapp.com/invite/rainmeter) and ask if they can help you further.
