### ISSUE TITLE
add shazam support

### ISSUE THREAD

**Issue by fhbncghdytgf** [MarcoPixel/Monstercat-Visualizer#167]
add shazam support for webmediaplayer
to make the song more accurate

**Comment by tjhrulz** [comment]
You mean you want us to send the song you are listening to to Shazam to better recognize it?

Not only is this incredibly difficult but a huge breach of privacy IMO it is also against shazam's TOS and would likely get every user IP blocked very quickly and I would have a cease and desist on my doorstep in less than a month.

So no this is never gonna happen.
