### ISSUE TITLE
Bars work with USB Headset, but not stereo connected by Aux Line-In

### ISSUE THREAD

**Issue by TeddT** [marcopixel/Monstercat-Visualizer#171]
### Description

Whenever my Razer Kraken USB Headset is being used as a primary audio device, the bars work. However, whenever my stereo (connected by Auxiliary Line-in) they don't.

### Versions

* Rainmeter Version: 4.1
* OS Version: Windows 10 Pro
* Skin Version: 1.8.1
* Spotify Version: 1.0.80.474.gef6b503e

**Comment by MarcoPixel** [comment]
Could be fixed with https://github.com/MarcoPixel/Monstercat-Visualizer/commit/367dcee2e901dfc8ae0f5943d812670767aabff6, try it again when the update hits in a few hours.

**Comment by TeddT** [comment]
Despite updating to the newer version (and to Rainmeter 4.2), Now the bars don't work on my headset AND the stereo

**Comment by eerwwe** [comment]
@TeddT theres to simple ways to fix this 
go to general in monstercat and click change audio device. 
in between the time of your issue and now windows added a setting that allows u to change where a applications sound outputs to. just play around with it  
![image](https://user-images.githubusercontent.com/28791625/46626096-ea38e780-cafb-11e8-81ff-6073d3b1bdcf.png)
