### ISSUE TITLE
Spotify podcast and local file artwork doesn't appear

### ISSUE THREAD

**Issue by couchz** [MarcoPixel/Monstercat-Visualizer#174]
### Description

Tried refreshing the visualizer and it won't load podcast or local file artwork while it gets all other music on Spotify no problem.

### Versions

* Rainmeter Version: 4.2.0 beta r3018 64-bit (Dec 20 2017)
* OS Version: Windows 10 Pro 64-bit
* Skin Version: 1.8.1
* Spotify Version: 1.3.0.0

### Additional notes/images

Spotify program itself is version 1.0.80.474.gef6b503e

Not sure if this is an issue or just a feature request but it would be really great if the visualizer would show podcast and local file artwork!

**Comment by tjhrulz** [comment]
Local file artwork not showing is a spotify limitation and podcasts have had some issues with there system in the past. Mind sending a link to the podcast?

**Comment by couchz** [comment]
Sure, this one in particular is https://open.spotify.com/show/7IWzayPhHif6GhgtTQdB84?si=Yfsp4RmRS-uiHZTG6T044w

**Comment by RobertFrydenlund** [comment]
At the moment Spotify is not giving this info to the API we are using. Podcasts doesn't show up at all, so unless Spotify changes something, i don't see a way we can get that to work. 
As for local files, I will add a measure to the plugin for track type, so you at least get told when you are playing a local track. I'm sure someone more talented at making skins than I am, could make some kind of conditional check for local tracks and change the album cover from SpotifyPlugin to some other kind of API. There seems to be a few album art APIs out there, but this is beyond the scope of SpotifyPlugin at this point.

**Comment by couchz** [comment]
Alright then, thought I'd give a shot. Thanks both of you for your time anyways!

**Comment by tjhrulz** [comment]
Yeah RobertFrydenlund I even tried looking into if there was a way to pull it out in some way from the API but really all it gives you is a randomly generated ID for the local track that can not do anything. Hopefully we can work out some sort of a workaround on the Rainmeter end of things in the future.
