### ISSUE TITLE
[Request] visualizer sensitivity curve.

### ISSUE THREAD

**Issue by Varynn** [MarcoPixel/Monstercat-Visualizer#175]
### Description

The visualizer looks fantastic on its own, but you know what makes it even cooler? Grabbing an animated wallpaper off Wallpaper Engine and sticking the visualizer behind the city skyline! Problem is that the visualizer sensitivity needs to be turned up to make it work the greatest, but the problem with THAT is that if it's too high then all the music just flies up to the top of my screen. 
If you've ever used overclocking software, then the feature I'm proposing is similar to "Fan Curve" adjustments where you can use a graph to set how the bars sensitivity should be scaled depending on how large the bars are. I want to be able to tell the visualizer that at low volumes it should be more sensitive, but as the visualizer bars go up higher it should dial back sensitivity. For my purposes, it would probably turn less sensitive on each bar as they fill up about 80% of the maximum height.

###Images
https://i.imgur.com/JfOUG5R.jpg

**Comment by tjhrulz** [comment]
I agree with the Wallpaper Engine thing (I built a hacked version of this skin once that actually pulled the music video for the song playing and used that as the background)

I know Marco has talked about changing the visualizer bars to be "smarter" by using a log scale but not sure what became of that. Until then though try modifying the bar height to something larger and setting it back to a normal sensitivity as that may provide the result you are looking for.

**Comment by ScratchHacker1** [comment]
In volume mixer you can adjust rainmeters volume (right click on audio). The lower it is, the lower the visualization is. Maybe this will help?

**Comment by MarcoPixel** [comment]
Sensivity curve is sadly not possible with the plugin since we can't properly say what frequency each bar is since the calculations are done on the plugin and not on the skin.

But i have added a new setting called **"Multiplier"** in which you can increase on how high the bars go, combine that with the **"Sensitivity"** setting and you should be able to get the result you've wanted.
