### ISSUE TITLE
Bar Clipping

### ISSUE THREAD

**Issue by bandaid** [MarcoPixel/Monstercat-Visualizer#178]
Previous version 1.3 we had the ability to increase the bounding box for the visualizer. In the previous version (1.3) a user could edit and increase the following values found in visuzlizer.ini  [ BarHeight=(#WORKAREAHEIGHT#*#Scale#)/3 BarCountCalc=(#BarCount#+1) ]  doing so would resolve the issue with the bar clipping.

Current Versions:
Monstercat-Visualizer 2.0.1
Rainmeter 4.2.0 beta r3074

bar clipping
![clipboard-20180614_cr](https://user-images.githubusercontent.com/8212255/41444456-ca34f44a-7008-11e8-98eb-e34c39b1acde.png)

![clipboard-20180614-02](https://user-images.githubusercontent.com/8212255/41444998-16be5c22-700c-11e8-9313-cb49d370daf4.png)

**Comment by MarcoPixel** [comment]
Well you can still modify the BarHeight manually in the **variables.ini** file under `@Resources`. Not sure what you wanted to do with that small code snippet, but it only sets the BarHeight 1/3 of the desktop height.
