### ISSUE TITLE
Visualizer not working with Spotify

### ISSUE THREAD

**Issue by Klossel** [MarcoPixel/Monstercat-Visualizer#18]
When I first installed the visualizer it was working fine with Spotify but then it randomly stopped working and no matter what I do it won't work again. I've tried downloading other visualizers and they are not working with Spotify too! Really have no idea what the problem is and I love the Monstercat Visualizer :(

**Comment by tjhrulz** [comment]
Just to clarify is the Spotify info such as what song is playing there and just the audio visualizer isn't working? 

If so iirc that normally happens when the audio plugin has not detected the default audio device has changed, try restarting rainmeter.

**Comment by Klossel** [comment]
Yes that's all there but I just tried restarting rainmeter and the visualizer still won't work. I've tried re-installing the program and still nothing, I've also tried other visualizers and still nothing?

**Comment by MarcoPixel** [comment]
Could you please send a screenshot from the debug log of Rainmeter (https://docs.rainmeter.net/manual/user-interface/about/) and post it in here.

Also please write down your OS version, Rainmeter version and skin version.

**Comment by Klossel** [comment]
![screenshot_3](https://cloud.githubusercontent.com/assets/25836866/23104618/3a7f9314-f6c9-11e6-9e20-23c604e5066b.png) OS is Windows 10 (64 bit), Rainmeter version is 4.0.0 r2746 64-bit and skin version is 1.5.3

**Comment by Klossel** [comment]
![screenshot_6](https://cloud.githubusercontent.com/assets/25836866/23104655/18237b04-f6ca-11e6-9b5c-8145e084ab20.png) Here's the log when I open Spotify.

**Comment by Klossel** [comment]
![screenshot_7](https://cloud.githubusercontent.com/assets/25836866/23104680/76e4981c-f6ca-11e6-902b-c57968e23426.png) Here's just the debugs when running Spotify.

**Comment by MarcoPixel** [comment]
Did you already reinstall Spotify? Cause most of the time when the plugin can't detect Spotify there is a issue with the SpotifyWebHelper.exe which got corrupted via update or is not running at all. Open explorer, enter %AppData%\Roaming\Spotify in the top and try to launch SpotifyWebHelper.exe.

**Comment by Klossel** [comment]
I'll try reinstalling it now and just tried to open the SpotifyWebHelper.exe. and it wouldn't run/open?

**Comment by MarcoPixel** [comment]
It will be running in the background, it will not open anything.

**Comment by Klossel** [comment]
Oh ok, just reinstalled Spotify and still not working and I was running the webhelper in the background.

**Comment by MarcoPixel** [comment]
Try installing NET Framework 4: https://www.microsoft.com/de-at/download/details.aspx?id=17718

**Comment by Klossel** [comment]
Just tried to install it and it said I already have it installed on my OS

**Comment by Klossel** [comment]
![screenshot_8](https://cloud.githubusercontent.com/assets/25836866/23105036/9f6c7dd0-f6d0-11e6-8b46-68f9fa318fe3.png) And just opened that link and it said this at the top and I was running the webhelper, I don't know what it meant.

**Comment by MarcoPixel** [comment]
Ok, so at least you should get the token so this is not an issue. Are you in private or offline mode? Because it only works in normal mode.

Also try to restart your computer after reinstalling Spotify, sometimes that helps too.

**Comment by MarcoPixel** [comment]
Also which Antivirus are you using?

If you are using AVG, please disable Link scanner as shown in the gif below:

https://i.gyazo.com/3960cbaf9abb257bbc6c3f7edb786833.gif

**Comment by Klossel** [comment]
Restarted my pc and I just use Windows Defender and my Spotify on my pc isn't in offline or private mode

**Comment by Klossel** [comment]
I restarted and still not working

**Comment by tjhrulz** [comment]
Marco maybe I am misunderstanding his issue but I think this is an issue with the audio plugin not the Spotify plugin. Klossel, do you have a discord account so that we can go through debugging what is going on in a faster fashion? If you do add me at tjhrulz#5476

**Comment by Klossel** [comment]
Just sent you a friend request :)

**Comment by tjhrulz** [comment]
After some debugging the AudioLevel plugin did not correctly install, reinstalled rainmeter and it fixed it.

**Comment by Klossel** [comment]
Thanks for all your help guys :)

**Comment by IonstormEU** [comment]
I'm also having this issue, Windows Sounds make the visualizer work, this was actually working but randomly stopped, tried reinstalling everything, no fix :S

**Comment by tjhrulz** [comment]
Is this an issue with Spotify or the Audi bars. Also do to some recent issues try doing a manual install: #manual-installation

**Comment by MissCupcakeDK** [comment]
tjrulez i added you on discord, as i have the exact same issue :(
