### ISSUE TITLE
What does this red icon mean?

### ISSUE THREAD

**Issue by SetyGames** [MarcoPixel/Monstercat-Visualizer#180]
### Hello, I saw this icon next to my album art and I updated from 2.0.1 to 2.0.2 and it's still there.
I was wondering what it means and how do I get rid of it?

### Versions

* Rainmeter Version: 4.2.0 beta r3074 64-bit
* OS Version: Windows 10 Home 1803 64-bit (build 17134) - English (1033)
* Skin Version: Monstercat-Visualizer - Update 2.0.2
* Spotify Version: [You can check this here: https://docs.rainmeter.net/manual/user-interface/about/#PluginsTab]

### Additional notes/images

![image](https://user-images.githubusercontent.com/8408970/41509491-95d4611a-7222-11e8-9cdd-3e19550ee409.png)

**Comment by MarcoPixel** [comment]
This is not part of my skin, no idea where this is coming from. Maybe it's another skin which causes it or some sort of antivirus detection.
