### ISSUE TITLE
Song info can't be moved into certain positions

### ISSUE THREAD

**Issue by LuckyLapras** [MarcoPixel/Monstercat-Visualizer#182]
### Description

I have the visualiser set up as it looks in the Monstercat videos. Since the 2.0.0 update, I've found that the song information will not move further right past a certain point on my screen, which means it's covered up by the album art in the current layout. Before the 2.0.0 update, I could get around this by turning off the song info clipping setting, but now I can't get it to work either way.

### Versions

* Rainmeter Version: 4.2.0 beta r3074 64-bit
* OS Version: Windows 10 Home 1803 64-bit (build 17134)
* Skin Version: 2.0.2
* Spotify Version: 2.1.5

### Additional notes/images

![image](https://user-images.githubusercontent.com/40395281/41602227-398e6df4-73d2-11e8-8f48-1ce80087383c.png)

**Comment by MarcoPixel** [comment]
Should be fixed in the next update with https://github.com/MarcoPixel/Monstercat-Visualizer/commit/5a876cfb568f2ddfcbe31a49513b4a7d456fa13c :)
