### ISSUE TITLE
How to backup saved settings?

### ISSUE THREAD

**Issue by Devel0per95** [MarcoPixel/Monstercat-Visualizer#183]
Anyway To backup saved setting and add it in the next version, cuz i update it and it overwrite my saved settings (Ithink!).

Hope some can help me :).

**Comment by MarcoPixel** [comment]
After 2.0.0, every new update should "merge" the settings and keep the old ones.

**Comment by MarcoPixel** [comment]
All settings are stored in the variables.ini file under ```Documents/Rainmeter/Skins/Monstercat-Visualizer/@Resources```. Keep in mind that pre 2.0.0 files will not completely work on 2.0.0 or higher. I'll recommend doing a fresh install and configuring the skin from scratch.

**Comment by Ipiano** [comment]
This does not appear to be working. I just updated to 2.0.2, and it looks like I have to re-do all of the settings. I can't imagine enough settings changed between 2.0.0 and 2.0.2 to necessitate this

**Comment by MarcoPixel** [comment]
Yeah, just noticed that i've had it disabled on 2.0.2 😅 On the next update it should work propertly.
