### ISSUE TITLE
[Feature request] Clip informations after a set width

### ISSUE THREAD

**Issue by ThaumicTom** [MarcoPixel/Monstercat-Visualizer#185]
### Description

To reproduce have the setting "Clip Information" on. Add an setting to Clip Information that allows you to set after how much pixels of width the Text should clip, because without it, long names will clip with the same width of the visualizer, but most people prefer this design.

### Versions

Rainmeter Version: 4.2.0 beta r3088 64-bit (Jun 15 2018)
OS Version: Windows 10 Home 1709 64-bit (build 16299)
Skin Version: 2.0.2
Spotify Version: SpotifyPlugin.dll: 2.1.5

### Additional notes/images

![584 -- 21-34-38 20 06 2018](https://user-images.githubusercontent.com/15818698/41720036-160b3fce-7562-11e8-830e-f3d72becc251.png)

**Comment by MarcoPixel** [comment]
You can change the width of the clipping by modifying this line in **Left.ini**:
```
Line 41:
IfEqualAction=[!SetOption MeterArtist W "#SkinWidth#"][!SetOption MeterTrack W "#SkinWidth#"]
```

Replace #SkinWidth# with your desired clip width in pixel.
