### ISSUE TITLE
Peaks does not appear - ErrorCode=12002

### ISSUE THREAD

**Issue by KtDodye** [MarcoPixel/Monstercat-Visualizer#190]
### Description

Hello, for a few weeks Visualisation peaks does not apperar when playing music on Spotify Desktop. Song lengh, title and images are still working. I updated my Rainmeter and reset my plugin but without effect.

Only error from Rainmeter I got is this:
(Fetch error) The operation timed out  (ErrorCode=12002) (Monstercat-Visualizer\visualizer.ini - [MeasureWebParser])

### Versions

* Rainmeter Version: 4.2.0 r3111 64-bit
* OS Version: Windows 7 Ultimate 64-bit (build 7601) SP 1
* Skin Version: 2.0.2
* Spotify Version: 2.1.5

### Additional notes/images

Have a nice day. =)

**Comment by KtDodye** [comment]
+ Found out another error, maybe related I dunno o.O

21:42:31 12. července 2018
SpotifyPlugin version 2.1.5.0
Culture: en-US
OSVersion: Microsoft Windows NT 6.1.7601 Service Pack 1
----
 The remote server returned an error: (404) Not Found.
----
    at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at SpotifyPlugin.AlbumArt.GetAlbumImage(Int32 resolution, String filePath)

**Comment by MarcoPixel** [comment]
Maybe A/B testing of the Spotify client, will be merged with #191.
