### ISSUE TITLE
Audio being detected even when set to ignore

### ISSUE THREAD

**Issue by bDavid18** [marcopixel/Monstercat-Visualizer#192]
### Description

Hello, I'm not sure if this belongs here, but I noticed while looking at the logs that even if I set the visualizer to ignore sounds that are not from my music player, it still reads sounds. It doesn't affect the visualizer (as expected), but the values still update according to the logs. I just wanted to know if this will affect CPU performance, and, thus, battery usage, in any way. Thank you!

### Versions

* Rainmeter Version: 4.2.0 r3111 64-bit
* OS Version: Windows 10 Pro 1803 64-bit (build 17134)
* Skin Version: 2.0.2
* Spotify Version: 1.0.84.344.gfc674f6f (Windows Store version)

**Comment by MarcoPixel** [comment]
Probably a side effect of #191, please try the setting with another media player (like AIMP, Winamp or iTunes) and report back if it's still not working. Also include a screenshot of the Rainmeter log so we can properly fix this issue together.

**Comment by bDavid18** [comment]
Hello, sorry, I might have been unclear. I was referring to the MeasureAudio values in the Skins tab in the "About Rainmeter" window that pops up when you click "Open Log" actually. I tried WMP that particular measure still updates its values even when WMP is closed. Here's a screencap of the logs, but I'm not sure if it helps. 
![image](https://user-images.githubusercontent.com/14279217/43354925-812cff86-9286-11e8-8a05-5ab61e0c24d1.png)
