### ISSUE TITLE
Sound resolution not adjustable

### ISSUE THREAD

**Issue by shoey9998** [marcopixel/Monstercat-Visualizer#193]
[IMPORTANT: Please remove or replace everything between two square brackets ( [ ] ) before posting your issue.]

### Description

[The Spotify plugin doesn't work after troubleshooting, although that is already a noted issue. My problem is that the sound resolution can't be adjusted above 1024]

### Versions

[2.02]

* Rainmeter Version: [4.2.0 r3111 (64 Bit)]
* OS Version: [Windows 10 Home latest update]
* Skin Version: [Monstercat Visualizer 2.02]
* Spotify Version: [Plugin 2.15, most recent desktop client]
* Audio Device [Behringer U-Phoria 202HD, 24bit, 192k]

**Comment by MarcoPixel** [comment]
Seems like an issue with the config file, so if youre comfortable to delete your current settings go to `Documents/Rainmeter/Skins/Monstercat-Visualizer/@Resources` and remove the **variables.ini** file and replace it with the default one from here: https://github.com/MarcoPixel/Monstercat-Visualizer/blob/master/%40Resources/variables.ini. 

After that, restart Rainmeter and go to the settings. Click on the box with the sound resolution and then enter your value and when you're done press ENTER to confirm it.

If it's still not working, please send in a screenshot of the Rainmeter log after you've tried to set the value.
