### ISSUE TITLE
Shortening the song information section when there is more than two features on a song

### ISSUE THREAD

**Issue by HurtSo** [MarcoPixel/Monstercat-Visualizer#198]
### Description

I would like the artist section in the Song Information skin to be shortened to only the primary perfomer, because the whole thing stretches far and wide if the song has more than three features.

**Comment by MarcoPixel** [comment]
This is not possible with this skin, as it depends on the media player / plugin used and doing it manually would involve a lot of work / testing. 

For example, Spotify already only shows the main artist of the song. If you have local music files, you could modify the ID3 tags to remove all additional artists.
