### ISSUE TITLE
Get the frequencies of each bar

### ISSUE THREAD

**Issue by ThomaScholz** [MarcoPixel/Monstercat-Visualizer#20]
Hi MarcoPixel,

Is it possible to encounter the frequencies of each bar? A nice feature could be to select the frequencies that the visializer shall show.

BR,
Thomas

**Comment by MarcoPixel** [comment]
Hey ThomaScholz,
thanks for your feedback!

 For now it's not possible to set a specific frequency to a single bar without breaking the code for the bar generation (to change the number of bars, size, etc...). 
This might change in the future, though, so if there will be a method in the future I'm going to reopen this issue.

For the frequency range you can change the variables to set the minimum and maximum frequencies in the **variables. ini** file under **Rainmeter\Skins\Monstercat-Visualizer\@Resources** under FreqMin and FreqMax.
