### ISSUE TITLE
Rainmeter crash at startup with visualizer

### ISSUE THREAD

**Issue by LordOfRhun** [MarcoPixel/Monstercat-Visualizer#201]
### Description
when i install this plugin the monstercat set-up window appear and then rainmeter crashes.
Every time i restart Rainmeter it instantly crashes.

I tried uninstalling rainmeter and installing everything back.
If i delete the Monstercat skin in C:\Users\User\Documents\Rainmeter\Skins\ it start without crashing 

### Versions
* Rainmeter Version: 4.2.0 r3111 64-bit
* OS Version: windows 10 pro 1803 64 bit
* Skin Version: 2.0.2
* Spotify Version: 1.0.86.337.ga8d5cef9

**Comment by MarcoPixel** [comment]
Can you send a screenshot of the plugins installed in Rainmeter? Might be something conflicting at the start and thus crashing Rainmeter.

**Comment by LordOfRhun** [comment]
![skins](https://user-images.githubusercontent.com/32278516/43340895-d214921e-91ab-11e8-8c1f-ddd91917020a.png)

**Comment by MarcoPixel** [comment]
Not the skin folder, the plugins tab under About.

https://docs.rainmeter.net/manual/user-interface/about/#LogTab

Then click on **Plugins** and make a screenshot of that with all version numbers.

**Comment by LordOfRhun** [comment]
![plugins](https://user-images.githubusercontent.com/32278516/43341078-62f449d2-91ac-11e8-828e-e90fc2585342.png)

**Comment by MarcoPixel** [comment]
Go to Manage / Settings and turn on **Debug Mode** and **Log to file.**

![grafik](https://user-images.githubusercontent.com/3743025/43341305-5c5b6032-91df-11e8-9562-23787b6789be.png)

Then readd the skin and start Rainmeter. After crashing open the log in "C:\Users\**<USER>**\AppData\Roaming\Rainmeter" and copy the file in here.

**Comment by LordOfRhun** [comment]
I think i found the problem, i had certain sportify address blocked in C:\Windows\System32\drivers\etc\host.
As soon as i removed them it worked.

Thank you for the help !
