### ISSUE TITLE
Way to disable smoothing ends?

### ISSUE THREAD

**Issue by mlodyseven** [marcopixel/Monstercat-Visualizer#208]
**Any way to make the bars on the sides as responsive as the ones in the middle?**
I have the visualiser from edge to edge of my screen and smoothing ends looks not too good in this config for me. An option similar to the one in Frost visualiser where you can choose whether to smooth ends (e.g. when you have certain width that doesn't match the full screen) or not to smooth them at all (e.g. if the visualiser takes full screen width) would be good. If there's no option to do so, It would be good to see one in a new release! Thank you!

**Comment by tjhrulz** [comment]
Marco a while back was working on updating the smoothing for the bars to make it a little nicer but at the end of the day the smoothing is meant to look as close as possible to the Monstercat videos so we have no plans to add other smoothing types. You could just turn off smoothing in the settings or you could just change the individual `IfFalseAction` in the MeasureBandsSmoothed.inc to all be divided by the same value
