### ISSUE TITLE
Feature Request (Removing N/A from song information)

### ISSUE THREAD

**Issue by Darkchaos88** [MarcoPixel/Monstercat-Visualizer#210]
Would like a feature request to be added.

Is there a way to hide just the song information rather than display "N/A"? Would like the song information to only appear if it can locate the proper song information, otherwise just not exist while the visualizer will always run no matter whether the song information is available or not.

Alternatively if anybody is experienced with editing this .ini file and knows the solution, please share. Only got Rainmeter quite recently and not that experienced in coding.

Currently the only option I can find is to "Hide skin when media player is not running", which unfortunately hides the visualizer at the same time :(.

**Comment by MarcoPixel** [comment]
You can remove the "N/A" text by going into the variables file via 

> Right-Click -> Open variables

 and then removing the value in the 

> NoArtistNameText
> NoTrackNameText

variables.
