### ISSUE TITLE
visualizer bar picks up every audio except spotify

### ISSUE THREAD

**Issue by IzzHaziq** [marcopixel/Monstercat-Visualizer#213]
### Visualizer bars works perfectly except for spotify

The visualizer detects youtube , voice calls and the cover art and info is working perfectly which is neat but the spotify audio which is the main use is not being detected

### Versions

* Rainmeter Version: 4.2.0 r3111 64-bit july 8 2018
* OS Version: Windows 10 Home 64-Bit
* Skin Version: 2.0.2
* Spotify Version: 2.1.7

**Comment by tjhrulz** [comment]
This is an audiolevel issue and likely has something to do with default media playback devices.

I would look at the help guide for audiolevel and ask for help there. https://forum.rainmeter.net/viewtopic.php?t=23348
