### ISSUE TITLE
Youtube info is displayed strangely

### ISSUE THREAD

**Issue by Ein6tein** [marcopixel/Monstercat-Visualizer#214]
### Description

Am using song information + Cover combo, no Visualizer. Today started my Youtube playlist, and instead of showing usual info (Channel name instead of Artist and simply video title instead of Song Name), now it shows MY channel name and video title is shown as if with 4+ new line characters. Reloading skin didn't help.

### Versions

* Rainmeter Version: 4.2.0 r3111 64-bit (Jul  8 2018) - English (1033)
* OS Version: Windows 10 Pro 1803 64-bit (build 17134) - English (2057)
* Skin Version: 2.0.2
* Spotify Version: irrelevant, Youtube issue + using WebNowPlaying Companion Chrome extension, v 0.4.2 

### Additional notes/images

Here how it looks: ![image](https://user-images.githubusercontent.com/1998101/44453638-368a9f80-a602-11e8-919d-58fc86816bb2.png)

**Comment by tjhrulz** [comment]
This is a WebNowPlaying issue so technically this is in the wrong place, but I will leave this open and respond here when I fix it.

**Comment by tjhrulz** [comment]
This should be fixed now
