### ISSUE TITLE
Not Showing Web Browser Song Info

### ISSUE THREAD

**Issue by JeroSammy** [marcopixel/Monstercat-Visualizer#215]
So I've just recently gotten Rainmeter, and this is the most appealing thing on it. The problem is of course, it doesn't work on Spotify so I tried Soundcloud and YouTube, and neither work. The visualizer works, but the song info is just what you're going to see. I don't mind the picture just being the Monstercat logo.

Also, is it possible to make the Monstercat logo/Album Cover more rounded? Would look better with my background.

### Versions
Rainmeter - 4.2 r3111
Visualizer - Version 2.02
Windows 10

https://gyazo.com/902d63c54e964375fa35cd33a3a904ee

**Comment by JeroSammy** [comment]
Sorry bout the extra step with the gyazo link, I don't know how to add a picture straight to the thread.

**Comment by woeterman94** [comment]
Got the same problem with spotify. It shows the visualizer but not song info.

![image](https://user-images.githubusercontent.com/5755057/44619911-8a101e00-a88c-11e8-895d-ce26745c838f.png)

@JeroSammy just use ctrl +c , ctrl + v to pase an image from your clipboard.

**Comment by tjhrulz** [comment]
@JeroSammy try going through the steps here: https://github.com/tjhrulz/WebNowPlaying-BrowserExtension/wiki/Troubleshooting also rounding the album art is not an easy task.

@woeterman94 that is an issue with Spotify itself and that info can be found here: #191

**Comment by mcaiazzo23** [comment]
I'm having the same issue with the cover art and song information when playing music through google play and youtube through my web browser, using chrome. Any insight on this?

**Comment by tjhrulz** [comment]
This was likely fixed upstream and this issue will be closed
