### ISSUE TITLE
why when i add monstervizualizer to rainmeter after that its said rainmeter has stopped working and all of my rainmeter skin gone

### ISSUE THREAD

**Issue by bradleyhendry** [MarcoPixel/Monstercat-Visualizer#218]
[IMPORTANT: Please remove or replace everything between two square brackets ( [ ] ) before posting your issue.]

### Description

[Please explain your problem here, tell all the step you've taken and how you found the issue.]

### Versions

[IMPORTANT: Please fill out the version numbers so we can properly look for your issue.]

[You can remove this section when posting an feature request]

* Rainmeter Version: [You can check this here: https://docs.rainmeter.net/manual/user-interface/about/#VersionTab]
* OS Version: [You can check this here: https://docs.rainmeter.net/manual/user-interface/about/#VersionTab]
* Skin Version: [You can check this here: Right-Click the Skin -> Open variables file. It should be at the top of the file]
* Spotify Version: [You can check this here: https://docs.rainmeter.net/manual/user-interface/about/#PluginsTab]

### Additional notes/images

[If you have any additional infos you can give us, please write them down]

**Comment by tjhrulz** [comment]
Closing since you left no info. Probably just need to clean uninstall then reinstall rainmeter. https://docs.rainmeter.net/tips/clean-rainmeter-uninstall/
