### ISSUE TITLE
Dymanic Color From System

### ISSUE THREAD

**Issue by Riajyuu** [marcopixel/Monstercat-Visualizer#219]
Windows 8.1/10 can set system color from desktop wallpaper image. I wonder if Monstercat Visualizer can follow this.

**Comment by tjhrulz** [comment]
I would like this, but more so in reverse. It is possible, albeit not so straightforward to do, given how busy Marco and I am right now it probably won't happen but if I ever add something like this to my hacky version of MV I will certainly port it back to master.

For the time being the best method is to manually set the color of Monstercat Visualizer in the settings and then you will just have to change it whenever you change your album art.

**Comment by Riajyuu** [comment]
@tjhrulz 
I totally understand that.
But unfortunately I am unlikely to change manually. I use a uwp app to download bing wallpaper everyday.

**Comment by marcopixel** [comment]
Added with https://github.com/marcopixel/Monstercat-Visualizer/commit/061c123ccda86441018ab1fec37b36105d59237f, thanks for your suggestion :)
