### ISSUE TITLE
Feature request, can we have more visualizer bars?

### ISSUE THREAD

**Issue by Surfx24** [marcopixel/Monstercat-Visualizer#220]
So I was messing around with the settings and really wanted to have it show more then 100 bars but it says that there's a max of 100 and if I to go over that itll cut off the rest, for instance if I want it at 200 the left 100 bars would be completely cut off but would still take up screen space by not letting me move it all the way right. I'm on version 2.0.2 but since its obviously known this is more or less a feature request.

**Comment by tjhrulz** [comment]
100 is the limit for performance reasons. You could tweak it under the hood if you wanted to add more.
