### ISSUE TITLE
Spotify Songtitle not shown displayed

### ISSUE THREAD

**Issue by PhilT995** [marcopixel/Monstercat-Visualizer#222]
### Description

The visualizer picks up every sound correctly, but fails to display the currently played song title by spotify. I re-installed Spotify, rainmeter and the spotify plugin. 
If i remember correctly, the plugin doesnt work correctly since a month.

### Versions

* Rainmeter Version: Version 4.2.0 r3111 
 
* OS Version: Windows 10 Pro 64 bit Version 1803
* Skin Version: Version=2.0.2
* Spotify Version: 1.0.89.313.g34a58dea

**Comment by silvesterbertels** [comment]
I have the same problem, appeared after a Spotify update last month.

**Comment by ColonialDagger** [comment]
Look at other issues before posting your own.
#191

**Comment by PhilT995** [comment]
> 
> 
> Look at other issues before posting your own.
> #191

Can be closed then.
