### ISSUE TITLE
Feature Request: Add compatibility for Windows 10 Groove Music

### ISSUE THREAD

**Issue by Keelanakax3** [marcopixel/Monstercat-Visualizer#223]
Was wondering if it would be possible to add compatibility for Windows 10's music player, Groove Music.

**Comment by tjhrulz** [comment]
Microsoft does not support any sort of API for Groove Music and there is no known way to hack something together to support it. If you see another app that adds support for it let me know and I can try to add support but as it stands right now this is not possible.
