### ISSUE TITLE
Does not show spotify information

### ISSUE THREAD

**Issue by eyal100** [marcopixel/Monstercat-Visualizer#224]
### Description
The theme does not show the spotify info, I tried solutions provided [here](https://github.com/MarcoPixel/Monstercat-Visualizer/wiki/Troubleshooting)
I have eset av if it matters. Spotify web player works.

### Versions

* Rainmeter Version: r3111
* OS Version: Windows 10 Pro 1803
* Skin Version: 2.0.2
* Spotify Version: 2.1.5

**Comment by Wist9063** [comment]
See https://github.com/MarcoPixel/Monstercat-Visualizer/issues/191

**Comment by eerwwe** [comment]
see #226

**Comment by tjhrulz** [comment]
Given this is a duplicate issue and it was already posted the other issues this will be closed
