### ISSUE TITLE
Fix formatting for hour+ long songs

### ISSUE THREAD

**Issue by Wist9063** [marcopixel/Monstercat-Visualizer#225]
### Description
Formatting for hour long songs are messed up.

### Versions

* Rainmeter Version: 4.2.0 r3111
* OS Version: Windows 10 Pro 1803
* Skin Version: 2.0.2
* Spotify Version: WebNowPlaying 0.4.0.0

### Additional notes/images

![5cj47](https://user-images.githubusercontent.com/22089269/46050446-0cd50480-c0e9-11e8-8bf6-63cb3477292e.png)

**Comment by tjhrulz** [comment]
There should be no issue with that, what player are you using?
