### ISSUE TITLE
Sound output's don't work.

### ISSUE THREAD

**Issue by berganize** [marcopixel/Monstercat-Visualizer#228]
Hello i just installed this visualizer  and i got this problem.
I have one headphone connected via USB, and a pair of speaker's connected on my mobo sound card.
but the visualizer only detect my headphones...
any tip to solve my problem?

i use the newest version of this visualizer and the newest version of rainmeter

**Comment by tjhrulz** [comment]
This is an issue with Audiolevel and you should go here for steps to fix it and for help.

https://forum.rainmeter.net/viewtopic.php?t=23348
