### ISSUE TITLE
Monstercat Visualizer for macOS Mojave

### ISSUE THREAD

**Issue by Azzhoe** [marcopixel/Monstercat-Visualizer#229]
This is awesome, would you please consider making this for macOS as well?

**Comment by joshuah345** [comment]
that would require recoding a lot of stuff as rainmeter isnt availiable on mac os

**Comment by joshuah345** [comment]
> This is awesome, would you please consider making this for macOS as well?

that would require recoding a lot of stuff as rainmeter isnt availiable on mac os

**Comment by tjhrulz** [comment]
This would require Rainmeter being ported to macOS which will never happen, you best bet is maybe getting Rainmeter to work with Wine
