### ISSUE TITLE
Visualizer 

### ISSUE THREAD

**Issue by ASAPKush** [MarcoPixel/Monstercat-Visualizer#23]
I have reinstalled everything 1000x with revo uninstaller, normal windows Program Changing/Uninstalling; and the visualizer does not seem to work with spotify or anything else. I can see the song title, cover, name, and visualizer but the visualizer is not bouncing how it should be. I just reinstalled spotify and reinstalled my the skin to the latest version and it says "spotifyplugin.dll" is the same version on my OS. Not even my windows sound is making the visualizer work. I am using audio router, but I do not think that is the problem. Really would appreciate the help :) I have also of course selected spotify inside of the monstercat GUI. 

here are some screenshots of what's going on 

http://image.prntscr.com/image/aeba616b8594493b981734ebff4a4cb3.png
http://image.prntscr.com/image/0ccc4e26703c49f6bd429946500823aa.png
http://image.prntscr.com/image/6e5093a86a194ce9b2b40f5845c268ca.png
http://image.prntscr.com/image/a254c4cc61d440428efd955db6338b8c.png
http://image.prntscr.com/image/3aa78c32df944b8fa7cd2abf8fc4d5c2.png
http://image.prntscr.com/image/cb81940309544d98937d8ad290a622b6.png <- I have replaced the SpotifyPlugin here. 

I've been using these download links: 
https://download.scdn.co/SpotifySetup.exe
http://marcopixel.deviantart.com/art/Monstercat-Visualizer-for-Rainmeter-1-5-486330771
https://www.rainmeter.net/

Paste of visualizer config: http://pastebin.com/6cD0DHPj

I honestly am really stumped as to why this is not working :( Used to work fine about three updates ago and I gave up on it but now I'm really hoping to get it back :)

**Comment by ASAPKush** [comment]
http://prntscr.com/ed84us this is my volume level and shit

**Comment by ASAPKush** [comment]
Update: I switched my playback device to something random and unloaded reloaded and refreshed my visualizer and it worked, and I switched back to my Soundblaster3Di soundcard and it stopped working ://

**Comment by tjhrulz** [comment]
Sounds like you are having the same issue as issue #18, the ultimate fix in that case was reinstalling rainmeter. Also did you try rebooting rainmeter after changing the sound device/are you running any software sound EQs or anything like that?

**Comment by MarcoPixel** [comment]
Since there was no response to @tjhrulz i'm gonna close this issue as it seems it got solved already. If not, please reopen this issue.
