### ISSUE TITLE
A maximum of 740+1 bars.

### ISSUE THREAD

**Issue by ThunderBolt6** [marcopixel/Monstercat-Visualizer#231]
### Description

Adding more bars by hand it reaches a limit of 741, cant get past that

### Versions

Monstercar vis 2.0.2
Rainmeter 4.2.0 r3111 64 bit Eng 1033
Win 10 pro 64bits

### Additional notes/images
Its not a bad spell check, it reset the file "MeterBars.ini" to a max of 740 bars [https://pastebin.com/mDsypnFT  file]
Meter bars smoothed ini [https://pastebin.com/CKiVDuGb]

**Comment by tjhrulz** [comment]
I believe this is a limitation of the audiolevel plugin and regardless having that many bars is not something we support or plan on supporting due to performance issues.
