### ISSUE TITLE
Progress Bar Is No Longer Clickable On The New Version.

### ISSUE THREAD

**Issue by djcyrax** [marcopixel/Monstercat-Visualizer#232]
The progress bar is no longer clickable on the new version.

Rainmeter Version: 4.3 Beta Release - 3260c
OS Version: Windows 10 Pro 1809
Skin Version: 2.0.2

**Comment by vitalinos** [comment]
MeterProgressBar.inc
Write this command line
LeftMouseUpAction=[!CommandMeasure MeasureProgress "SetPosition $MouseX:%$"][Wait 300][!Update][!Redraw]

**Comment by marcopixel** [comment]
Will be readded with https://github.com/marcopixel/Monstercat-Visualizer/commit/331caf644cb51e06543ad7b7c2febcf13201e765.
