### ISSUE TITLE
Fine tuning settings

### ISSUE THREAD

**Issue by ThatGuyAgain42** [marcopixel/Monstercat-Visualizer#233]
I'm just a little OCD and it's very hard to change settings to the exact numbers I want so if you could make it so you can fine tune the settings with the arrow keys or something that would be nice.

**Comment by tjhrulz** [comment]
You can change any variable if you want it more exact in the variables.ini %UserProfile%\Documents\GitHub\Monstercat-Visualizer\@Resources\Variables.ini
