### ISSUE TITLE
I kinda fixed the song info issue

### ISSUE THREAD

**Issue by Vision919** [marcopixel/Monstercat-Visualizer#237]
Ok its not really a fix but it works. If you download Monstercat Visualizer 1.5.3 it will show the cover info and everything. But it does not have WebPlayer, but does have spotify, google play music, and more. I hope this helped you guys!

**Comment by tjhrulz** [comment]
I have no idea what you are talking about and this makes no sense and does not seem to be describing and issue.

If you have a fix for an existing issue (Which your recommendation is not as downloading an older version of MV is not going to fix any current issue) do not open up a new issue, make a comment in the thread for that issue.
