### ISSUE TITLE
The bass of music isnt being picked up at all

### ISSUE THREAD

**Issue by Mnk3yAF** [marcopixel/Monstercat-Visualizer#240]
[IMPORTANT: Please remove or replace everything between two square brackets ( [ ] ) before posting your issue.]

### Description

The bars at the end of the visualizer which is usually for the lower end of a song does not move at all, the visualiser however pick up higher frequencies just fine. this only happens when I use the speakers of my laptop. When I use headphones this problem disappears. Maybe it's due to how the visualizer picks up the sounds? My laptop has a built in subwoofer so maybe that's the reason?

### Version
2.02

* Rainmeter Version: 4.3
* OS Version: Windows 10 Home 
* Skin Version: 2.02

### Additional notes/images

![Screenshot (3)](https://user-images.githubusercontent.com/49806816/56454708-bc284000-6387-11e9-9f4a-85bffed7f1dd.png)
![Screenshot (4)](https://user-images.githubusercontent.com/49806816/56454710-bdf20380-6387-11e9-88d8-b480d5f3e633.png)
 
first pic is with heaphones, second is without . both playing summer time magic

**Comment by ScratchHacker1** [comment]
Maybe audio enhancements are on? Wild guess.

**Comment by Mnk3yAF** [comment]
I'm using Dolby atmos but disabling it does nothing

**Comment by tjhrulz** [comment]
Realtek's audio drivers are a nightmare and your issue is related to them, uninstall them and use the default windows ones instead.

Also this issue is related to the audiolevel plugin and any further issues should be directed here where you will get help in a quicker fashion https://forum.rainmeter.net/viewtopic.php?t=23348
