### ISSUE TITLE
Dynamic coloring

### ISSUE THREAD

**Issue by josh-65** [marcopixel/Monstercat-Visualizer#241]
When using Grove or Google play music it won't change the color for the genre or cover when using dynamic coloring.

Rainmeter Version: 4.3.0.3298 - 64 bit
OS Version: Windows 10 pro 1809 - 64 bit - build 17763
Skin Version: 2.0.2

**Comment by tjhrulz** [comment]
Neither of those support genre so there is no way to support genre coloring in them and cover is what dynamic coloring is so you will have to be more specific as to what is going on there.
