### ISSUE TITLE
Swap Artist and Song Request

### ISSUE THREAD

**Issue by cazaman11** [marcopixel/Monstercat-Visualizer#242]
Just a request of adding the option to swap the artist name and the track name, so the song is the larger text above the artist.

**Comment by tjhrulz** [comment]
You could do this yourself if you prefer with minimal effort by just editing the left.ini and/or the right.ini

Just change line 62 from
`MeasureName=MeasureArtist`
to 
`MeasureName=MeasureTrack`

and line 78from
`MeasureName=MeasureTrack`
to 
`MeasureName=MeasureArtist`


Given how easy is this is to do yourself and that this skin is meant to imitate the old Monstercat videos and thus I think Marco would agree that unless a lot of people ask for this it will stay this way.
