### ISSUE TITLE
Windows accent colour not working with dynamic color

### ISSUE THREAD

**Issue by josh-65** [marcopixel/Monstercat-Visualizer#244]
### Description
When updating to the new 2.1.0 version and use the dynamic colour windows accent it just shows it as white for all colours.

### Versions
Rainmeter Version: 4.3
OS Version: Windows 10 pro - build 1809 vir. 17763.504 - 64 bit
Skin Version: 2.1.0

**Comment by marcopixel** [comment]
It might be caused by the SysColor plugin not being installed correctly, please send a screenshot of your log + plugins so we can fix this issue.

https://docs.rainmeter.net/manual/user-interface/about/#LogTab

**Comment by josh-65** [comment]
![Rainmeter issue 1](https://user-images.githubusercontent.com/26977075/58747429-27733080-8463-11e9-8909-2237e2ec5eb4.jpg)
![Rainmeter issue 2](https://user-images.githubusercontent.com/26977075/58747430-27733080-8463-11e9-960a-06544d5c291d.jpg)

**Comment by marcopixel** [comment]
The Plugin didn't get installed, try reinstalling the skin and check if SysColor.dll gets installed.

**Comment by josh-65** [comment]
I have and it works now thanks for the help
