### ISSUE TITLE
Spotify color changed?

### ISSUE THREAD

**Issue by StevenvL** [marcopixel/Monstercat-Visualizer#247]
https://i.imgur.com/TPcrck3.jpg

**Comment by marcopixel** [comment]
A small snippet of the installation guide will tell you why:

![image](https://user-images.githubusercontent.com/3743025/58765417-2fba9100-8573-11e9-91ce-7d91ad42c8d4.png)

Enter `spicetify config inject_css 0 replace_colors 0` and then `spicetify backup apply` and it should be gone!
