### ISSUE TITLE
Requesting the ability to change the color of the progress bar

### ISSUE THREAD

**Issue by ShikiTheReaper** [marcopixel/Monstercat-Visualizer#248]
### Description

I would love to see the ability to change the color of the progress bar on the visualizer itself.

### Versions

2.1.0
### Additional notes/images

![image](https://user-images.githubusercontent.com/50162091/59006167-97c8db80-87ee-11e9-9efb-ae2134239069.png) Like the ability to keep the visualizer bars red but, change the progress bar black or another color.

**Comment by marcopixel** [comment]
Issue merged into #251, please go there for discussion.
