### ISSUE TITLE
[Feature Request] Auto Hide 'Cover' and 'Song Information' 

### ISSUE THREAD

**Issue by thexmanxyz** [marcopixel/Monstercat-Visualizer#255]
### Description
I have a feature implemented on my local version of the skin which allows me to hide the 'Song Information' as well as the 'Cover' when e.g. there is no meta information coming from WebNowPlaying. I refer here on the measure type:

> `Status`
> 
> If 0 no supported websites are open, 1 is if one or more websites are open that are supported.

So I created something like this:
```

; Auto Hide Song Information and Cover when status returns 0
HideWhenNotActive=1

[HideCoverAndSongInformation]
Measure=Plugin
Plugin=WebNowPlaying
Type=Status
IfEqualValue=1
IfEqualAction=[!ShowFade "monstercat-visualizer\Song Information\Cover" "Cover.ini"],[!ShowFade "monstercat-visualizer\Song Information" "Left.ini"]
IfCondition=(#HideWhenNotActive#=1) && (HideCoverAndSongInformation=0)
IfTrueAction=[!HideFade "monstercat-visualizer\Song Information\Cover" "Cover.ini"],[!HideFade "monstercat-visualizer\Song Information" "Left.ini"]
UpdateDivider=1
DynamicVariables=1
```

So in my case when I close Spotify the Cover and Name is hidden because it won't be necessary to display it but maybe you want the Visualizer to be showing. I think this should be implemented as an option within the configuration of the skin. As a test I put the above configuration to the `variables.ini` and you also can do to check the feature yourself.

I also wanted to add a version here which demonstrates hidding the cover and song information when the stream is paused. This didn't work. I tried the following measure:

> `State`
> Integer of the play state of the music player. 0 is stopped, 1 is playing, 2 is paused.
> 

See also the API [WebNowPlaying](https://github.com/tjhrulz/WebNowPlaying). IDK if this is a bug within WebNowPlaying or if I'm just stupid. I tried nearly everything to get the actual playing state. Suggestions welcome!

None or less I would love to see this feature come directly within the skin with the option to enable and disable it.

**Comment by marcopixel** [comment]
You can manually remove the skin groups which will be hidden by removing the **!HideFadeGroup** or **!ShowFadeGroup** on the specific measure inside the media player measure file.

Here's an example which keeps the visualizer but auto-hides the song information:

```diff
[MeasureAutoHideNowPlaying]
Measure=NowPlaying
PlayerName=#PlayerName#
PlayerType=Status
IfEqualValue=0
+ IfEqualAction=[!HideFadeGroup "SongInfo"][!Log "AutoHide: Media player was closed, hiding skin"]
- IfEqualAction=[!HideFadeGroup "Spectrum"][!HideFadeGroup "SongInfo"][!Log "AutoHide: Media player was closed, hiding skin"]
IfAboveValue=0
+ IfAboveAction=[!ShowFadeGroup "SongInfo"][!Log "AutoHide: Media player was opened, showing skin"]
- IfAboveAction=[!ShowFadeGroup "Spectrum"][!ShowFadeGroup "SongInfo"][!Log "AutoHide: Media player was opened, showing skin"]
Disabled=(#EnableAutoHide# > 0 ? 0 : 1)
UpdateDivider=100
```

> Note: This has to be done for each media player plugin (e.g NowPlaying, WebNowPlaying), but the way it's done is the same for each.
