### ISSUE TITLE
Can't download Spotify desktop version

### ISSUE THREAD

**Issue by Vision919** [marcopixel/Monstercat-Visualizer#256]
Hi. So with the {sorta new} update I just downloaded it, and I noticed the fixes and the spicetify and WebPlayingnow thing, so i gave it a try. I downloaded the spotify desktop version from the site and it was downloading until it said "Migrating Data", and after that it automatically downloaded the Windows store version of spotify. I can give more info if needed. Thanks!

**Comment by marcopixel** [comment]
I've had this issue in the past too (especially if Spotify was never installed before), the only real workaround is by uninstalling both versions of Spotify and then reinstalling the desktop version again.

As for this issue, we can't really do anything against this so i'll close this here.

Download: https://www.spotify.com/de/download/windows/
