### ISSUE TITLE
Song information is clipped

### ISSUE THREAD

**Issue by rsp33d** [marcopixel/Monstercat-Visualizer#257]
### Description

When you use the Right option of the Song Information it cut the information if the song name/artist it´s bigger that the visualizer, even if you have the option "Clip Song Information" unchecked

### Versions
* Rainmeter Version: Rainmeter 4.3.0.3298 (64-bit)
* OS Version: Windows 10 Pro 1809 64-bit (build 17763)
* Skin Version: v2.1.0
* Spotify Version: 1.1.9.383.g9f48828e

**Comment by marcopixel** [comment]
Closing issue due to age, if the issue still persist please comment down below!
