### ISSUE TITLE
Cant change settings in the visualizer

### ISSUE THREAD

**Issue by FirstTimerGaming** [marcopixel/Monstercat-Visualizer#263]
So while I was using my tablet pc, I wanted to use a Monstercat visualizer so I ported it to here with an USB stick. Now the computer is broken, and I havent figured out how to use the thing.
When I try to adjudt the settings in the settings ini files, all I can do is press the tabs, change the colours and change the sound res. I cant change the sliders or anything. Ive tried to manually change the settings but Ill have to investigate that further.

### Versions

I am using a Linx tablet running Winodws 10 (not sure what build) and version 2.1.0.

* Rainmeter Version:Final Release
Windows 10 Home 
* Skin Version: 4.2.0

**Comment by marcopixel** [comment]
Seems like the plugins required for sliders aren't installed, so follow the steps explained here: https://github.com/marcopixel/Monstercat-Visualizer/issues/150#issuecomment-375003029

Also if you don't want to overwrite your configuration, disable the checkbox under Skins at the top and just install all plugins.

**Comment by FirstTimerGaming** [comment]
> Seems like the plugins required for sliders aren't installed, so follow the steps explained here: [#150 (comment)](https://github.com/marcopixel/Monstercat-Visualizer/issues/150#issuecomment-375003029)
> 
> Also if you don't want to overwrite your configuration, disable the checkbox under Skins at the top and just install all plugins.

I dont really know if that's the problem here, because it's the exact same install of a one that I did on a regular Windows 10 computer and it worked fine. However, on the tablet, even using a mouse will not work.
I think it has something to do with some of the windows that I use look blurry like they're in 640 by 480 pixels mode. So if it works fine on a fresh install of Rainmeter here, and a fresh install on Rainmeter there, I dont think plugins are the issue. Now referring to the link you sent me.

PS: Sorry for not replying for a while, computer bugged and it's now fixed.

**Comment by FirstTimerGaming** [comment]
Update: Turns out I just remembered that I vinstalled the visualizer by porting my Skins folder into Rainmeter. It _was_ the plugins! When I just ported them in, I had no plugins installed. No plugins. Somehow the visualizer still worked. The settings didnt. Well that problem is solved. I was kinda new to Rainmeter and didnt realise there were plugins to use, like namespaces in C++.
