### ISSUE TITLE
Spicetify applies css even if commanded not to do it

### ISSUE THREAD

**Issue by Ein6tein** [marcopixel/Monstercat-Visualizer#264]
### Description

Spotify updated to the latest version. To keep WebNowPlaying working with Spotify, I did the spicetify magic of `spicetify backup apply`. But it broke Spotify's UI (WebNowPlaying connection works though). UI can be fixed with `spicetify restore backup`, but it breaks WebNowPlaying connection.

### Versions

* Rainmeter Version: 4.3.0.3298 (64-bit)
* OS Version: Windows 10 Pro 1809 64-bit (build 17763) - English (2057)
* Skin Version: 2.1.0
* Spotify Version: 2.1.5 (from Plugins tab) / 1.1.15.448.g00fba0e3 (from Spotify's About)

### Additional notes/images
Example of how it looks broken:
![image](https://user-images.githubusercontent.com/1998101/64789376-ea97f900-d57c-11e9-8782-d6790d68e546.png)

**Comment by annaaisya** [comment]
unrelated?

**Comment by Ein6tein** [comment]
Well, I don't know for sure, since spicetify comes in bundle with visualizer, so my first thought is to post issue here. If unrelated, I'll post it to spicetify.

**Comment by Ein6tein** [comment]
Or - I won't post it there since Spicetify is archived...

If next Spotify update won't fix the issue and there will be more people with it, then either someone will have to fix Spicetify, or look for a replacement for it in this library. For now, all that's left is to wait.

**Comment by jduust** [comment]
> Or - I won't post it there since Spicetify is archived...
> 
> If next Spotify update won't fix the issue and there will be more people with it, then either someone will have to fix Spicetify, or look for a replacement for it in this skin. For now, all that's left to do is to wait.

Yea i'm getting the exact same issue. I'm wondering if there's anyway to get the WebNowPlaying plugin to work without having to use spicetify.

**Comment by Ein6tein** [comment]
Wow, it works now!!!
Strange - I did before everything just like @jduust suggested, except the first command...

Maybe the problem is that Monstercat Visualizer is packed with outdated Spicetify version?

**Comment by jduust** [comment]
> Wow, it works now!!!
> Strange - I did before everything just like @jduust suggested, except the first command...
> 
> Maybe the problem is that Monstercat Visualizer is packed with outdated Spicetify version?

Oh i actually thought you were using the GUI version of spicetify, i hadn't read the post all the way through. But seems you were just using an older CLI version then, because i was getting the same issue with the rainmeter GUI version of spicetify.

**Comment by Ein6tein** [comment]
Then I think issue is resolved!

For anyone, who finds themselves in a similar situation - just follow @jduust's instructions and it'll update Spicetify to the latest available version and it should work (at least as of 23rd of September, 2019).
