### ISSUE TITLE
Error from Spotify Cover Art

### ISSUE THREAD

**Issue by SaberAkiyama** [marcopixel/Monstercat-Visualizer#267]
### Description

I've saw an error on Rainmeter log was "Web Side Error: Error updating cover for Spotify"
Visualizer & Song Information are worked, but Cover didn't work

### Versions

* Rainmeter Version: v4.3.1 r3321
* OS Version: Windows 7 Ultimate
* Skin Version: Monstercat Visualizer 2.1.0
* Spotify Version: Web Player (Chrome) with WebNowPlaying Extension v0.4.6 (Sep 18th 2019)

### Additional notes/images

![Capture4](https://user-images.githubusercontent.com/48464326/65567428-dabee280-df88-11e9-9ae1-cda110e2cfd8.PNG)

**Comment by marcopixel** [comment]
No idea about that error, maybe @tjhrulz or @khanhas can help me with that?

**Comment by SaberAkiyama** [comment]
Maybe extension has issue since updated version 0.4.6.
In previous version is work fine without cover error.

**Comment by SaberAkiyama** [comment]
> No idea about that error, maybe @tjhrulz or @khanhas can help me with that?

Maybe a browser extension might be an issue v0.4.6.
In previous version 0.4.5, it works fine without cover error.

**Comment by marcopixel** [comment]
Closing issue due to age, if the issue still persists please comment down below!
