### ISSUE TITLE
Visualizer bar keeps moving to the middle after refresh

### ISSUE THREAD

**Issue by Timotej979** [marcopixel/Monstercat-Visualizer#268]
### Description
Hello,

whenever I refresh the rainmeter skin it positions the visualizer bar to the middle of the screen(cordinates X=665, Y=0) , i want to have it rotated 90 degrees and on the right edge(X=1757, Y=0). I have searched through the ini and resource files where number 665 could be... and i have done some basic changing of code, which was not very succesfull

Thanks for the help
### Versions
* Rainmeter Version: 4.3.1.3321
* OS Version: Windows 10 Educational
* Skin Version: just downloaded it, newest
* Spotify Version: also newest

### Additional notes/images

Before refresh
![Before refresh](https://user-images.githubusercontent.com/16840528/66714212-59eb4d80-edb4-11e9-84bc-4317d5f90908.jpg)

After refresh
![After refresh](https://user-images.githubusercontent.com/16840528/66714213-5e176b00-edb4-11e9-991e-fa0ebe133930.jpg)

**Comment by marcopixel** [comment]
Closing issue due to age, if the issue still persists please comment down below!
