### ISSUE TITLE
Progress bar disappears

### ISSUE THREAD

**Issue by CowheadDK** [marcopixel/Monstercat-Visualizer#269]
### Description

was playing around with getting webMediaPlayer working and saw the option to enable the progress bar and after i got webMediaPlayer working realized that the progress bar would appear for a split second and then disappear. i even edited the the general.ini file to make it show the progress bar if it wasnt enabled this didnt fix the problem.

### Versions

* Rainmeter Version: 4.3.0.3298 (64-bit)
* OS Version: Windows 10 Home 1809 64-bit (build 17763)
* Skin Version: 2.1.0

**Comment by CowheadDK** [comment]
Just tried turning my visualizer from 180 degrees to 0 and it came back.

**Comment by marcopixel** [comment]
Closing issue due to age, if the issue still persists please comment down below!
