### ISSUE TITLE
Spotify GUI completely broken

### ISSUE THREAD

**Issue by GrateBrittan** [marcopixel/Monstercat-Visualizer#270]
### Description

Basically, the GUI for Spotify cannot be interacted with and it looks like it came from a 2005 web page. there is a thingy over the whole GUI as if it's a piece of anti-click film. (Please ignore my stupid explanation of this)

### Versions

Spicetify: v0.9.5
Spotify: 1.1.16.522.g55a4b852
Rainmeter: 4.3.0.3298 (64-Bit)
Visualizer/skin: 2.1.0
Windows 10 Pro 1809 64-bit (build 17763) - English (1033)

### Additional notes/images

https://gyazo.com/0924f6e1ae5a33c2a82ce525f4bb0814
https://gyazo.com/894011f312cf7ddf3f7c6a8457ccaed5

**Comment by malik-tillman** [comment]
I know it's pretty late, but the work around is to stop using the Rainmeter version and download the CLI. Here's the [link](https://github.com/khanhas/spicetify-cli). It's not as intuitive but hey what can you do.

**Comment by stefanw1337** [comment]
I'm currently trying everything. Can't for the life of me get this Rainmeter OR the one from Wallpaper Engine to work. It will get the cover art and title/artist, but the Virtualization itself remains dead. Also I manage to break Spicetify, so it won't load even the SpicetifyDefault skin now. Help?

**Comment by malik-tillman** [comment]
Have you installed and applied the cli through powerShell?

**Comment by stefanw1337** [comment]
Yes, I did run it as admin as well. I did however, break it somehow, can't change themes now. Not even default, and restore setting does nothing.

And how is it listening in on the audio, is Spicetify doing that? Are there any settings to pick microphones or something?

-Stefan
________________________________

**Comment by bluelhf** [comment]
Did you forget `spicetify config inject_css 0 replace_colors 0` when installing Spicetify? If so, try the following steps:

1. Completely exit and stop Spotify
2. Open PowerShell as Administrator
3. Run `spicetify config inject_css 0 replace_colors 0`
4. Run `spicetify apply`
5. Once Spicetify is done, restart Spotify.

For sound, I believe the visualizer just detects if a song is playing with spicetify's webnowplaying.js extension, and if one is, it detects all audio output from the current audio device. This is why you can pause the song and play a YouTube video and still have the visualizer show all audio.
If you want to change the audio device it detects on, you'd probably have to edit the skin directly.

**Comment by marcopixel** [comment]
Closing this issue, please create an issue on the [spicetify-cli](https://github.com/khanhas/spicetify-cli) repo for further help on spicetify.
