### ISSUE TITLE
Suggestion: add a compatibility with Tidal

### ISSUE THREAD

**Issue by eugenio53390** [marcopixel/Monstercat-Visualizer#273]

**Comment by dan-rprado** [comment]
please yesss

**Comment by kargupta28** [comment]
Please add compatibility for tidal!

**Comment by marcopixel** [comment]
**WebNowPlaying** does support Tidal inside your web browser, but sadly the desktop app can not be supported because there is no specific Rainmeter plugin made for it yet.

If someone decided to make a plugin for Rainmeter, we can add it but for now it's not possible.
