### ISSUE TITLE
Youtube Support

### ISSUE THREAD

**Issue by DefaltEcho** [marcopixel/Monstercat-Visualizer#278]
So,i was reading information about webnowplaying and i noticed that it had youtube support,but rainmeter isnt detecting none of it,is this a problem or am i just stupid and i dont know how to use the skin correctly?
Rainmeter version:4.3.1.3321
Skin version:2.1.0

**Comment by marcopixel** [comment]
Check out https://github.com/marcopixel/Monstercat-Visualizer/issues/312#issuecomment-715430994 for more information about Youtube & Youtube Music.
