### ISSUE TITLE
Spotify not working

### ISSUE THREAD

**Issue by PickycowXD** [marcopixel/Monstercat-Visualizer#279]
[IMPORTANT: Please remove or replace everything between two square brackets ( [ ] ) before posting your issue.]

### Description

I installed the spicetify with everything needed to get spotify working, and it not working. i play  a song and it just says n/a. how do i get it to register from spotify?

### Versions

* Rainmeter Version: 4.3.1.3321
* OS Version: Windows 10 Home 1903
* Skin Version: 2.1.0
* Spotify Version: 1.1.25.559.g85cf5e4c

### Additional notes/images

[If you have any additional infos you can give us, please write them down]

**Comment by marcopixel** [comment]
Closing this issue, please create an issue on the [spicetify-cli](https://github.com/khanhas/spicetify-cli) repo for further help on spicetify.
