### ISSUE TITLE
Spotify Web Player doesn't working

### ISSUE THREAD

**Issue by SaberAkiyama** [marcopixel/Monstercat-Visualizer#283]
### Description

When I play Spotify Web Player with WNP extension, it doesn't appear on Song, Artist, Playback state, Progress bar, etc. But Visualizer is okay.

### Versions

* Rainmeter Version: v4.3.1.3321
* OS Version: Windows 10 Version 1909 (64-bit)
* Skin Version: v2.1.0
* Spotify Version: Web Player on Google Chrome

### Additional notes/images

None

**Comment by marcopixel** [comment]
Please report the issues for WebNowPlaying here: https://github.com/tjhrulz/WebNowPlaying-BrowserExtension/issues
