### ISSUE TITLE
Enabling 'Hide skin when media player is not running' is not working

### ISSUE THREAD

**Issue by onlytanmoy** [marcopixel/Monstercat-Visualizer#288]
### Description

Under General, I clicked on Hide skin when media player is not running but that doesn't work. So even if media player is running, visualizer will remain hidden. Please can you fix this? Let me know if you require more info. Thx.

### Versions

* Rainmeter Version: Rainmeter 4.3.1.3321 (64-bit)
* OS Version: Windows 10 Home 1909 64-bit (build 18363) - English (2057)
* Skin Version: 2.1.0
* Spotify Version: N/A

**Comment by RefRec97** [comment]
I just tested it, and it worked. Can you say more about what you did? I had spotify and the Skin active, then closed spotify. That lead to the skin disapearing. After I opened Spotify and started music the skin reapeared.

**Comment by onlytanmoy** [comment]
hey, thanks for your response...this issue was opened a month back...lol...I moved to a diff visualizer..will close this issue.
