### ISSUE TITLE
Spotify not working at all

### ISSUE THREAD

**Issue by ASAPKush** [MarcoPixel/Monstercat-Visualizer#29]
My album cover shows AWD Winterride enhanced cover and I've never heard of it and when I click windows audio player it changes to the normal monstercat grey thing.. I reinstalled ran as admin reinstalled rainmeter and monstercat visualizer including all the dlls and refreshed everything nothings worked.

**Comment by MarcoPixel** [comment]
Duplicate of #27, closed.
