### ISSUE TITLE
Retrieve now playing information from Last.fm

### ISSUE THREAD

**Issue by fishstik** [marcopixel/Monstercat-Visualizer#292]
For choosing a media player, using a Last.fm profile would allow getting song information from any media player that supports Last.fm scrobbling (most media players).

**Comment by marcopixel** [comment]
Sadly that's not possible with the currently available plugins, since none of the used ones support metadata fetching from Last.fm. If there is one in the future, i'll might add it but right now it's out of scope.

Feel free to comment down below if something like this pops up in the future.
