### ISSUE TITLE
Have the ability to place the song name above the artist.

### ISSUE THREAD

**Issue by jzatarain** [marcopixel/Monstercat-Visualizer#295]
Just like in spotify, I would like to have the song name above the artists.
Probably a new variant would do.

Also, a variant to have it centered  would be nice too, depending on your background.

Could this be made?

**Comment by jzatarain** [comment]
What I did in the meantime was to change the fonts for the title and the song, so that the song stands out more, and changed the shadow properties.
![image](https://user-images.githubusercontent.com/20093580/82583931-62c9ac00-9b59-11ea-9573-91310feae5ec.png)

**Comment by marcopixel** [comment]
Since this is pretty easy to do yourself, i'll recommend anyone who wants to do this to just go into the specific skin file and just switch the measures between the two meters (so MeterArtist uses MeasureTrack and vice versa).

You can read more about on how rainmeter skins work here: https://docs.rainmeter.net/manual/getting-started/

**Comment by andre-paulo98** [comment]
For those looking for this, here's the things you need to change:
```diff
diff --git a/Right.ini b/Right-Flipped.ini
index a2c9445..451bfa0 100644
--- a/Right.ini
+++ b/Right-Flipped.ini
@@ -59,7 +59,7 @@ UpdateDivider=-1

 [MeterArtist]
 Meter=String
-MeasureName=MeasureArtist
+MeasureName=MeasureTrack
 X=#SkinWidth#
 Y=(30*#ScaleSongInformation#)
 FontFace=#Font1#
@@ -75,7 +75,7 @@ Group=GroupDynamicColors | GroupShadowMeters

 [MeterTrack]
 Meter=String
-MeasureName=MeasureTrack
+MeasureName=MeasureArtist
 X=#SkinWidth#
 Y=(-20*#ScaleSongInformation#)R
 FontFace=#Font2#
```

Or simply the Right file with the Title and Artist flipped:
[Right.txt](https://github.com/marcopixel/monstercat-visualizer/files/7180294/Right.txt)
*(you will need to change the extenstion to .ini)*
