### ISSUE TITLE
Spotify Integration Issues with Monstercat Visualizer

### ISSUE THREAD

**Issue by jakerigos** [marcopixel/Monstercat-Visualizer#297]
[IMPORTANT: Please remove or replace everything between two square brackets ( [ ] ) before posting your issue.]

### Description

I am new to this so apologies if I'm repeating anything. I installed WebNowPlaying and got the "Spotify is spiced up!" through powershell, so I didn't think it was an issue on that end. I've re-installed Spotify(as an exe) a couple of times, as well as uninstalled monstercat visualizer/WebNowPlaying/spicetify to see if that would solve anything.

I saw a number of fetch errors in the error log and was unable to figure out where the issue was from there.

I would appreciate any guidance that you have in relation to this issue. Thanks :D 

### Versions

* Rainmeter Version: 4.3
* OS Version: Windows 10 Pro 
* Skin Version: 2.1
* Spotify Version: 2.1.5

### Additional notes/images
Error log attached.
[If you have any additional infos you can give us, please write them down]
![image](https://user-images.githubusercontent.com/65639123/82737089-40bc5f00-9cfc-11ea-93d1-f561ee65104c.png)

**Comment by marcopixel** [comment]
Closing this issue, please create an issue on the [spicetify-cli](https://github.com/khanhas/spicetify-cli) repo for further help on spicetify.
