### ISSUE TITLE
Pulls window focus every 10 seconds

### ISSUE THREAD

**Issue by micahz3** [MarcoPixel/monstercat-visualizer#3]
Hello!

I've recently downloaded the newest update and decided to give it a try. Unfortunately, around every 10 seconds, rainmeter pulls window focus (bit of a pain when typing). It does this with all of the different players.

Unloaded the visualizer settings.ini and it stopped doing it. It doesn't seem to do it with any other rainmeter skin.

I'm on Win10 (Anniversary)
Rainmeter 4.0Beta

Hopefully this helps!

**Comment by MarcoPixel** [comment]
This is a bug caused by the spotify plugin trying to get data from the SpotifyWebHelper.exe and instead getting focus of the executable. Try to reinstall Spotify and see if it helped.

**Comment by micahz3** [comment]
This has fixed it! Thank you so much for your help!
