### ISSUE TITLE
Listen only for specific process

### ISSUE THREAD

**Issue by MaestroMagnifico** [MarcoPixel/Monstercat-Visualizer#30]
I use Monstercat-Visualizer for streaming. So I play Counter-Strike and music mostly plays from my browser. Visualizer picks up everything, including game sounds. I'm pretty sure there's no way to make it pick up sounds only from my browser. But is it possible to add this feature?

**Comment by MarcoPixel** [comment]
Thanks for your feedback!

Unless the AudioLevel plugin gets a rewrite or a plugin with similar features but with your feature included it will not be possible. This skin is heavily relying on this plugin so also if there will be a way to do it in the future it will probably need a full rewrite and that might also take a while.

I will close this issue for now and will reopen it when there is some progress/change in that area.
