### ISSUE TITLE
 My text is moving and i can't move it

### ISSUE THREAD

**Issue by nsrfontes** [marcopixel/Monstercat-Visualizer#300]
Hi, I was activating the Now Playing web and right after that the text went over the album art and I couldn't move it anymore.
ps: sorry my english

video of my problem
https://youtu.be/yyMtdL_Uvcs

Image 1
![Screenshot_1](https://user-images.githubusercontent.com/64340231/83555121-3102fe80-a4e4-11ea-9de4-da65def08374.png)

Image 2
![Screenshot_2](https://user-images.githubusercontent.com/64340231/83555182-45df9200-a4e4-11ea-9049-4e7d40e3a2db.png)

**Comment by Matter-Shifter** [comment]
Try to disable 'Keep on screen' option in Rainmeter setting, or **right click** at the song information **> Setting > Keep on Screen**. 
I guess it happened because as the visualizer scale increases, the length of the song information increases too.

**Comment by nsrfontes** [comment]
> Try to disable 'Keep on screen' option in Rainmeter setting, or **right click** at the song information **> Setting > Keep on Screen**.
> I guess it happened because as the visualizer scale increases, the length of the song information increases too.

Thx man, it worked
