### ISSUE TITLE
spotify errors/help

### ISSUE THREAD

**Issue by itachixhate** [marcopixel/Monstercat-Visualizer#301]
[IMPORTANT: Please remove or replace everything between two square brackets ( [] ) before posting your issue.]

### Description

after the initial install of spicetify using the power shell instructions everything worked great, the second day (today) it seems to have broken after a restart. when spotify starts it give an error of "spotify failed to migrate some of your data" and and spicetifys modifications to spotify seem to have dissapeared

### Versions

* Rainmeter Version: 4.4 r3350 beta
* OS Version: Windows 10 pro 1909 64-bit (build 18363) english
* Skin Version: 2.1.0
* Spotify Version: ---- not seeing spotify in the plugins list but 
WebNowPlaying.dll 0.4.0.0 (i will include a screen shot to be safe)

### Additional notes/images
![image](https://user-images.githubusercontent.com/66375202/83654854-ac6bbb00-a58b-11ea-868e-d74212b89692.png)

![image](https://user-images.githubusercontent.com/66375202/83654938-c9a08980-a58b-11ea-8f9e-de8763c43b26.png)

![image](https://user-images.githubusercontent.com/66375202/83655028-e50b9480-a58b-11ea-92b2-98b2227ad25c.png)

![image](https://user-images.githubusercontent.com/66375202/83655083-f785ce00-a58b-11ea-8a65-06b57d94b249.png)

**Comment by marcopixel** [comment]
Closing this issue, please create an issue on the [spicetify-cli](https://github.com/khanhas/spicetify-cli) repo for further help on spicetify.
