### ISSUE TITLE
Spotify Reverting Colors

### ISSUE THREAD

**Issue by PostItSkull** [marcopixel/Monstercat-Visualizer#304]
After running the spotify to spiceify commands in powershell, the entire spotify UI has inverted colors besides the album covers. It makes a lot of the text unreadable, how can this be fixed?

**Comment by jialid0830** [comment]
1. Completely exit and stop Spotify
2. Open PowerShell as Administrator
3. Run `spicetify config inject_css 0 replace_colors 0`
4. Run `spicetify update`
Once Spicetify is done, restart Spotify.

**Comment by marcopixel** [comment]
Closing this issue, please create an issue on the [spicetify-cli](https://github.com/khanhas/spicetify-cli) repo for further help on spicetify.
