### ISSUE TITLE
GPMDP plug in lagging+low res album art

### ISSUE THREAD

**Issue by therealdrtahir** [marcopixel/Monstercat-Visualizer#306]
[IMPORTANT: Please remove or replace everything between two square brackets ( [ ] ) before posting your issue.]

### GPMDP plug in lagging+low res album art

[I recently had to reset my pc, so this might be because my PC lacks direct x and a couple of other things rn, but I installed GPMDP and then the rainmeter monstercat visualizer. I was actually using 2.0 before this(didn't know about the update). But otherwise for me it was working seemlessly and without any issue. But since resetting my PC, the album art quality has gone way down, and everytime the song changes, it lags, almost as if it's having trouble loading the data for the visualizer. When I turned off the visualizer the songs played just fine. Not sure if I'm doing something wrong/did something during the process but can't remember now. Please]

### 2.1

[IMPORTANT: Please fill out the version numbers so we can properly look for your issue.]

[You can remove this section when posting an feature request]

* Rainmeter Version: [Latest Beta]
* OS Version: [You can check this here: https://docs.rainmeter.net/manual/user-interface/about/#VersionTab]
* Skin Version: [2.1]
* Spotify Version: [Don't have spotify on PC]

### Additional notes/images

[If you have any additional infos you can give us, please write them down]

**Comment by marcopixel** [comment]
Since Google Play Music will shut down in December and the issue is caused by GPMDP itself, i recommend you to check out **[YTMDesktop](https://github.com/ytmdesktop/ytmdesktop)** as an alternative which already works with the skin.
