### ISSUE TITLE
Support for Youtube Music

### ISSUE THREAD

**Issue by Ein6tein** [marcopixel/Monstercat-Visualizer#312]
Is it possible to add proper support for Youtube Music player (at least browser version)?

**Comment by remorsecodex** [comment]
It does support Google Play Music Desktop Player, which supports YTM (in beta currently but it works fine).

**Comment by Ein6tein** [comment]
There is desktop app? I only used browser version...

**Comment by remorsecodex** [comment]
It's unofficial, but high quality, open source, and supported by Monstercat Visualizer.

https://www.googleplaymusicdesktopplayer.com/

**Comment by TotallyNotInUse** [comment]
In case you use [YTMDesktop](https://github.com/ytmdesktop/ytmdesktop) there's support for it using WebPlayingNow

**Comment by marcopixel** [comment]
[YTMDesktop](https://github.com/ytmdesktop/ytmdesktop) added support for WebNowPlaying and is working fine with the current version.

Also the browser extension for [WebNowPlaying](https://github.com/tjhrulz/WebNowPlaying-BrowserExtension) also recently pushed some changes to the repo (but it's not published yet so it might take a while to release) so as soon as the extension receives it's update it will work right out of the box.

**Comment by Ein6tein** [comment]
Thanks for the update
