### ISSUE TITLE
Broken player controls for YouTube on cover art

### ISSUE THREAD

**Issue by eileenthg** [marcopixel/Monstercat-Visualizer#313]
Ever since chrome implemented [this feature](https://support.google.com/chrome/answer/9692215?hl=en), the cover art controls for Monstercat Visualizer has broken for YouTube.
**Enabling "attempt general script everywhere" does not fix it.

* What still works:
    * Unpausing a video
    * Skip to next video

* What partially works:
    * Pausing video: YouTube seems to detect your attempt to pause the video, then immediately resumes playing.

* What doesn't work (or work, but no effect shown):
    * Go back to previous video

### Versions
* Rainmeter Version: 4.3.1.3321
* OS Version: Windows 10 Pro 2004 64-bit (build 19041) - English (1033)
* Skin Version: 2.1.0
* Spotify Version: (Probably irrelevant, but) 2.1.5

* Chrome Version: 84.0.4147.125 (Official Build) (64-bit)

### Additional notes/images
The chrome feature appears when a media is playing. (Example, YouTube.)
![image](https://user-images.githubusercontent.com/40307498/90223800-4a5beb80-de41-11ea-9bba-63b31a233a77.png)

**Comment by marcopixel** [comment]
Please report the issues for WebNowPlaying here: https://github.com/tjhrulz/WebNowPlaying-BrowserExtension/issues
