### ISSUE TITLE
Visualizer Doesn't Work

### ISSUE THREAD

**Issue by DJFox11** [marcopixel/Monstercat-Visualizer#315]
Hi,
I have recently installed this visualizer but when I play any sort of music sound etc. Nothing happens. I've tried Spotify, YouTube, iTunes and Google Play Music. Absolutely nothing, I've also tried turning up the sensitivity but this nothing.
Thanks

**Comment by dryknucklesfan** [comment]
did you ever find a fix?

**Comment by tjhrulz** [comment]
https://github.com/marcopixel/Monstercat-Visualizer/wiki/Troubleshooting#the-visualizer-is-not-moving-or-not-working
