### ISSUE TITLE
Spotify Update Keeps Reverting Skin

### ISSUE THREAD

**Issue by Ledzeppigan7** [marcopixel/Monstercat-Visualizer#316]
[IMPORTANT: Please remove or replace everything between two square brackets ( [ ] ) before posting your issue.]

### Description

[I keep having to apply the spicetify backup because Spotify says it has to update which overwrites the spicetify code and reverts it back to normal so no visualizer.]

### Versions

[IMPORTANT: Please fill out the version numbers so we can properly look for your issue.]

* Rainmeter Version: [4.3.1.3321 (64-bit)]
* OS Version: [Windows 10 1903 64-bit]
* Skin Version: [2.10]
* Spotify Version: [1.1.40.508]

### Additional notes/images

[Basically, I had this skin for a while and then all of a sudden spotify would auto-update and overwrite the code, so I'm wondering if there's a newer version of the skin or an update I can input to keep spotify updated and also have spicetify visualizer work, which is what I care about most.]

**Comment by marcopixel** [comment]
Closing this issue, please create an issue on the [spicetify-cli](https://github.com/khanhas/spicetify-cli) repo for further help on spicetify.
