### ISSUE TITLE
Request: Support for devices streaming audio to PC via Bluetooth

### ISSUE THREAD

**Issue by Razwerkz** [marcopixel/Monstercat-Visualizer#319]
Windows is able to pull track data from Bluetooth devices.  Would it be possible to apply this to Monstercat Visualizer?

**Comment by marcopixel** [comment]
Sadly it's not officially possible to fetch this data from Windows and there is currently no plugin made which makes this avaliable for Rainmeter. You can read more about this here on the forums: https://forum.rainmeter.net/viewtopic.php?f=4&t=35769#p180882
