### ISSUE TITLE
Additional ID3 Tags for Dynamic Coloring

### ISSUE THREAD

**Issue by iamdrake** [marcopixel/Monstercat-Visualizer#323]
[]

### Description

[I would like to add additional ID3 tags to be identified when using iTunes as my media player and streaming music online]

### Versions

[2.1.0]

### Additional notes/images

[I attempted to adjust the variables.ini file but can't get any genres to work and I can't find any music with the provided genres to test the functionality in iTunes]

**Comment by marcopixel** [comment]
The colors in **varables.ini** are just for easy access to change the colors & they don't affect the genre matching at all.

You can add additional ID3 tags under **[@Resource/include/MeasureStyling.inc](https://github.com/marcopixel/Monstercat-Visualizer/blob/master/%40Resources/include/MeasureStyling.inc#L33-L80)**  by adding new _IfMatchX_ & _IfMatchActionX_ for the wanted ID3 tags.

You can find the documentation for the IfMatchAction options here:  https://docs.rainmeter.net/manual/measures/general-options/ifmatchactions/

Here's an example:
```ini
[MeasureGenre]
Measure=NowPlaying
PlayerName=#PlayerName#
PlayerType=Genre
; You can add your own genres here.
; Use | as dividier and replace spaces with \s (otherwise it won't work)
; Electro
IfMatch=Electro
IfMatchAction=[!SetVariable GenreColor "#Electro#"]
; Electronic/EDM
IfMatch2=EDM|Electronic|Breaks|Chillout|Bounce|Chill|Techno
IfMatchAction2=[!SetVariable GenreColor "#EDM#"]

...

; Future Bass
IfMatch12=Future|Future\sBass
IfMatchAction12=[!SetVariable GenreColor "#FutureBass#"]

; Here is an example for an custom genre. Colors need to be rgb(a) values.
; 
IfMatch13=Mashup|Mash\sUp
IfMatchAction13=[!SetVariable GenreColor "192,255,99"]

Substitute="":"#Color#"
OnChangeAction=[!UpdateMeasure "CalcColors"]
Disabled=1
```
