### ISSUE TITLE
Spicetify-CLI won't install to get Monstercat visualizer album art working (Windows 8.1)

### ISSUE THREAD

**Issue by redandvidya** [marcopixel/Monstercat-Visualizer#328]
### Description

I'm having this weird issue where I can't install spicetify-cli to get monstercat-visualizer fully working, weird. I'm following all the instructions and everything seems fine until I get THIS error: "Expand-Archive is not recognized as the name of the etc etc"
(full error is attached)
![im reporting ummm](https://user-images.githubusercontent.com/52748717/96273404-e51fa480-1001-11eb-9d9c-e3e4831ed99b.jpg)

 
I'm posting here because this seems to be more of a monstercat issue than spicetify, plus I'm only downloading spicetify for this specific problem.

### Versions

    Rainmeter Version: 4.3.1
    OS Version: Windows 8.1 Embedded Industry Pro (don't judge, I got it for free through Microsoft Azure)
    Skin Version: 2.1.0
    Spotify Version: I installed it literally today (Oct 16 2020) so I'm pretty sure it's the latest.

### Additional notes/images

**Comment by marcopixel** [comment]
Closing this issue, please create an issue on the [spicetify-cli](https://github.com/khanhas/spicetify-cli) repo for further help on spicetify.
