### ISSUE TITLE
Visualizer not working with Razer Kraken USB

### ISSUE THREAD

**Issue by raimkras97** [MarcoPixel/Monstercat-Visualizer#33]
Im using Razer Kraken USB headphones and Monstercat-Visualizer for rainmeter

http://marcopixel.deviantart.com/art/Mo ... -486330771 

Normally when i listen music with speakers witch are plugged in my motherboards audio drivers output - spectrum works, but when i change the playback device - music is playing on headphones, skins tray works but the spectrum stops visualizing i created my own skin and still the same thing. I don't know if this is a bug.

Speakers > http://prntscr.com/ektoy4 

Headphones > http://prntscr.com/ektrv1

**Comment by MarcoPixel** [comment]
Did you already check out the [Troubleshooting AudioLevel plugin](https://forum.rainmeter.net/viewtopic.php?p=123883#p123883) post on the official forums?

If none of these work, press **WIN + R** and enter **msconfig**. After pressing Enter it should open a new window with a tab called **Startup** and in there you should disable **Krakenhelper.exe** or **KrakenChroma71helper.exe** (depending on your headset).

After that restart your computer and it should work although a little bit loud as first. The only drawback is that you can't choose which programs you can run in 2.1 or 7.1.

Please report back if it worked!

Source: https://forum.rainmeter.net/viewtopic.php?f=103&t=22364&p=118329&hilit=Visualizer+work#118333

**Comment by raimkras97** [comment]
Tnx it worked! Also its way louder than before. But for some reason the device in Control Panel > Hardware and Sound > Devices and Printers - headphones are specified as ''Unspecified'' any clue why?

**Comment by MarcoPixel** [comment]
I don't have that headset i have to guess that the executable is adding some sort of metadata to the audio device list and by disabling​ it you loose that data. But it should work anyway as the program is only for some extra stuff you don't need most of the time.

It seems that your issue got fixed so i'm gonna close it now.
