### ISSUE TITLE
Position of Title and Description with Youtube when switching away from video

### ISSUE THREAD

**Issue by Cabola** [MarcoPixel/Monstercat-Visualizer#330]
### Describe the bug
If you use the Webplayer and watch a youtube video, then click away from the video to "Home" aka Youtube Index or the "Subscriptions" page. Basically a page where you find a list of videos to view. The title and description of the video you were watching before switching to the video list remains. The Title is displayed twice and the Description once, but further down than the position normally is.

### To Reproduce
Use webplayer and watch a YT video then click the YT logo to be taken to the index page.

### Screenshots
This is how it looks like when you're watching a YT video:
![normal](https://user-images.githubusercontent.com/19853946/99152223-b815ee80-26a0-11eb-8d97-76fe5d9087d5.png)
This is how it looks like after you switch to the index page of YT:
![bug](https://user-images.githubusercontent.com/19853946/99152222-b77d5800-26a0-11eb-8df8-e3a03de88aa3.png)

### System information
* **Rainmeter Version:** 4.4.0.3350 beta (64-bit)
* **OS Version:** Windows 10 Pro 2009 64-bit (build 19042) - English (1033)
* **Skin Version:** 2.1.0
* **Spotify Version:** The SpotifyPlugin.dll is version 1.9.3.0

### Additional context / media
It's not related to a rainmeter or windows version as it has always been this way. Just never bothered to report it as it's not anything serious. Would just be nice to see a fix by ex. having it hidden instead.

**Comment by marcopixel** [comment]
Please report the issues for WebNowPlaying here: https://github.com/tjhrulz/WebNowPlaying-BrowserExtension/issues
