### ISSUE TITLE
Text colour changes with visualiser colour and cannot be changed

### ISSUE THREAD

**Issue by ndv99** [MarcoPixel/Monstercat-Visualizer#339]
# Update

I've done some playing and I've found out a more precise way to reproduce the bug.

### To reproduce:
1. Choose a colour for the visualiser
2. Pick any colour for the text (except the colour of the visualiser)
3. Observe as the text changes to the colour you set for the visualiser*

* If you're setting a custom colour, you'll need to manually refresh the widgets first to see this effect. Restarting your PC naturally refreshes the widget, which is how I first discovered this issue, since I wanted a custom colour for the bars but default white was fine for the text.

# Original Issue:

### Describe the bug
I changed the visualiser colour to a custom colour, and set the text colour to white. The visualiser changed colour correctly, but the text changed colour with it.

### To Reproduce
On a fresh installation of the visualiser:

1. Set the visualiser bars to a custom colour
2. Ensure the text is set to white 
2. Play something (I used spotify, having followed all the instructions to get it working. It works correctly)
3. Exit spotify (the visualiser is set to hide when music is not playing)
4. Re-open spotify and start playing something

### Screenshots
https://imgur.com/qtRMXRc <-- Text should be white, not red
https://imgur.com/a/ufjCFYc <-- Dynamic colouring definitely off, white clicked multiple times, also tried setting through the "More..." option.

### System information
* **Rainmeter Version:** 4.2.1.3321 (64 bit)
* **OS Version:** Windows 1o Pro 2009 64 bit (build 19042) English (2057)
* **Skin Version:** Version 2.1.0
* **Spotify Version:** Spotify version 1.1.48.625.g1c87c7f7 (Desktop, not store)

**Comment by scottie** [comment]
can confirm and can replicate.

**Comment by ndv99** [comment]
SOLVED: Make sure you disable "Use dynamic color for song title and artist", since this forces the text to use the same colour as the visualiser
