### ISSUE TITLE
Option for Outline Song Title

### ISSUE THREAD

**Issue by Matuir** [MarcoPixel/Monstercat-Visualizer#34]
I cannot seem to find a good background for the song title. Not the way I want it atleast. They all have some white where I want the song title located (sky area). I'm requesting the ability to have a outline and maybe able to change the size of the outline

**Comment by MarcoPixel** [comment]
Added with 82ab0b95adedbac5061cef51d65982151b06382a, will be in the next release.

If you want to use it now, you have to clone this repository and place the files in **Documents/Rainmeter/Skins/Monstercat-Visualizer** and then you can enable it under the settings tab Styling.
