### ISSUE TITLE
Google Music Player does not show album art or name

### ISSUE THREAD

**Issue by MysticNynja** [MarcoPixel/Monstercat-Visualizer#347]
[ **IMPORTANT: Please remove or replace everything between two square brackets ( [ ] ) before posting your issue.** ]

### Describe the bug
When I use the Google Play Music player it does not show the name/artist/album of the song playing.

### To Reproduce
Open Rainmeter
Load Visualizer
Choose Google Play Music as Media player
Play Song on either GPDMP or https://music.youtube.com/
Visualizer works, but album art is just the monster cat (Note: Replace album art with Monstercat logo  is not checked)

### Screenshots
![image](https://user-images.githubusercontent.com/11483359/108561013-292df900-72c3-11eb-95d6-08a837c5a594.png)
![image](https://user-images.githubusercontent.com/11483359/108561029-2f23da00-72c3-11eb-87a8-94fa807ca53f.png)
![image](https://user-images.githubusercontent.com/11483359/108561047-34812480-72c3-11eb-93a9-dc959172abd5.png)
![image](https://user-images.githubusercontent.com/11483359/108561069-3fd45000-72c3-11eb-9297-888531f4edc0.png)
![image](https://user-images.githubusercontent.com/11483359/108561085-4662c780-72c3-11eb-95b8-8431278eb1a5.png)
![image](https://user-images.githubusercontent.com/11483359/108561206-714d1b80-72c3-11eb-9213-c222ed19197b.png)

### System information
* **Rainmeter Version:** 4.3.1.3321 (64-bit)
* **OS Version:** Windows 10 Pro 1909 64-bit (build 18363)
* **Skin Version:** 2.1.0
* **Spotify Version:** Not about Spotify

### Additional context / media
GPMDP.dll is up to date as well 
https://github.com/tjhrulz/GPMDP-Plugin/releases

I placed the plugin in the AppData/Roaming\Rainmeter\Plugins folder as well as the C:\Program Files\Rainmeter\Plugins directory.

Both locations do not give the desired affect.

**Comment by DurekuRyuu** [comment]
Reccomend switching to Youtube Music Player standalone and enabling WebNowPlaying integration as a solution, as Google Play Music Player Desktop Seems to be abandoned.

**Comment by MysticNynja** [comment]
I didn't even know that GPDMP was abandoned. I found the player you mentioned so I will try that.

Thanks
