### ISSUE TITLE
Dynamic Coloring Cover setting picks very dull colors

### ISSUE THREAD

**Issue by feephoenixx** [MarcoPixel/Monstercat-Visualizer#354]
### Is your feature request related to a problem? Please describe.
The Cover setting for Dynamic Coloring doesn't pick very vibrant colors, sometimes picking very dull or dark colors that can blend in with dark backgrounds. Plus, it's generally frustrating when an album that is mostly red, for example, has bars that are just colored black/brown/gray. 

### Describe the solution you'd like
At least some sort of option to customize what colors Cover mode would pick for dynamic coloring. 

### Additional context
Some examples below:
![image](https://user-images.githubusercontent.com/82619616/114949330-6a034380-9e16-11eb-9a5b-ba7bc41bbdec.png)
![image](https://user-images.githubusercontent.com/82619616/114949477-b6e71a00-9e16-11eb-9a52-2a762c9f921c.png)
![image](https://user-images.githubusercontent.com/82619616/114949582-ee55c680-9e16-11eb-87e7-6ee8693def5b.png)

**Comment by LaaZa** [comment]
This can be improved by changing line 22 in MeasureStyling.inc from `Color=Background1` to `Color=Foreground1`

Or any of these:

- Background1
- Foreground1
- Background2
- Foreground2
- Light1
- Light2
- Light3
- Light4
- Dark1
- Dark2
- Dark3
- Dark4
- Average
- Luminance
