### ISSUE TITLE
Monstercat Rainmeter Visualizer Skin

### ISSUE THREAD

**Issue by Rainmeterbase** [MarcoPixel/Monstercat-Visualizer#362]
Hello,
Monstercat Visualizer is among my favorite Rainmeter Visualizer Skins. I really love this skin. I have a site where I share [Rainmeter skins](https://rainmeterbase.com/skins). The address is [https://rainmeterbase.com](https://rainmeterbase.com), can I share your skin on this site under the [Rainmeter Visualizer Skins](https://rainmeterbase.com/skins/visualizer) category?

**Comment by marcopixel** [comment]
You are allowed to share the skin on your site, but you have to link them to the official download link and not reupload the .rmskin file.

Download link: `https://github.com/marcopixel/monstercat-visualizer/releases/latest`
