### ISSUE TITLE
Spotify update broke it?

### ISSUE THREAD

**Issue by Zubbbz** [MarcoPixel/Monstercat-Visualizer#367]
### Describe the bug
After updating my Spotify installation, I found that my rainmeter integration no longer seemed to work. I tried selecting a different client and then webnowplaying again in the options, but that didn't help. When I try to reinstall webnowplaying with spicetify, all goes well except for on the last command.
### Screenshots
![CMD](https://i.imgur.com/fa6l1zK.png)
[YouTube video](https://youtu.be/MVdQGKgshJI) of me reinstalling everything and it still failing.

### System information
* **Rainmeter Version:** 4.4.0.3508 beta (64-bit)
* **OS Version:** Windows 10 Pro 2009 64-bit (build 19043) - English (1033)
* **Skin Version:** 2.1.0
* **Spotify Version:** 1.1.67.586.gbb5ef64e

**Comment by brenmadeit** [comment]
im having this issue as well

**Comment by Zubbbz** [comment]
### Solution:
I was able to fix by deleting everything related to Spicetify, and reinstalling Spotify.

This can be done by:
1. Delete the folders at: C:\Users\{your username}\.spicetify and C:\Users\{your username}\.spicetify-cli.
2. Uninstall Spotify. This consists of going to add or remove programs inside of the settings app, right clicking spotify and clicking uninstall.
3. Reinstall Spotify, and then do the [steps to install WebNowPlaying](https://github.com/marcopixel/monstercat-visualizer/wiki/WebNowPlaying-Spotify) support for Spotify.

Edit: I garbled a script together that automatically installs spicetify and webnowplaying. all you have to do after steps 1-2 is just run [this](https://pastebin.com/rFp8Knt2) in powershell as admin and monstercat-visualizer should work.

Note: I did not mess with anything rainmeter. As long as you have monstercat-visualizer installed and set to webnowplaying, it should work.
