### ISSUE TITLE
Not retrieving Spotify metadata

### ISSUE THREAD

**Issue by TheGreyfish** [MarcoPixel/Monstercat-Visualizer#38]
I recently updated the plugin and now the visualizer displays an incorrect cover art and cannot retrieve metadata from my Spotify player. https://gyazo.com/3384f01cd4115934413c555ebf9e82e3

This issue does not occur when I use another media player such as Foobar.

**Comment by MarcoPixel** [comment]
Could you please send a screenshot from the debug log of Rainmeter (https://docs.rainmeter.net/manual/user-interface/about/) and post it in here.

Also please write down your OS version, Rainmeter version and skin version.

And then try the different troubleshooting steps I posted in #18 and report back if anything worked.

**Comment by TheGreyfish** [comment]
Sure thing.

https://gyazo.com/0c76c97fdf4a155d6957f25f67467ca6 <- Log. I don't see much related to Spotify, though I did get some Chameleon errors.

I was **not** able to retrieve a Spotify token. I get DNS_PROBE_FINISHED_NXDOMAIN. https://gyazo.com/37bed4506cf2ff12a95f3ea0e69eac11

Reinstalling Rainmeter did not solve the issue nor did reinstalling NET Framework 4.

OS Version: Windows 10 Pro 64-Bit (Build 14393)
Rainmeter Version: 4.0.0 r2746 
Visualizer Skin Version: 1.6.0

**Comment by MarcoPixel** [comment]
Okay, something seems to block the Spotify token which is required to get the metadata. Are you on a public or school network? 

If not, check your firewall is Spotify is allowed, change your [DNS server](https://www.howtogeek.com/164981/how-to-switch-to-opendns-or-google-dns-to-speed-up-web-browsing/) and reinstall the skin with the Spotify plugin checked.

**Comment by TheGreyfish** [comment]
I moved to a private network and cleared my hosts file. Seems to have work. I think one of my other applications may have put the token location on the file, thus making me not able to retrieve the token url. Thank you!

**Comment by MarcoPixel** [comment]
Great, glad that i could help you! :)
