### ISSUE TITLE
Latest Release Missing?

### ISSUE THREAD

**Issue by alberthaladay** [MarcoPixel/Monstercat-Visualizer#380]
![image](https://user-images.githubusercontent.com/75808248/160407902-f40a5e03-8d7a-4743-a79c-27e61b5764fa.png)
For some reason my version of the visualizer thinks the latest version is a previous release.
I assume this is because the latest release was removed or something?
Hope this helps.

**Comment by alberthaladay** [comment]
After looking at it, [MeasureWebParser] in MeasureUpdateChecker.inc, checks [https://github.com/MarcoPixel/Monstercat-Visualizer/releases/latest](https://github.com/MarcoPixel/Monstercat-Visualizer/releases/latest).

Which appears to be 2.0.2 instead of 2.1.0. Did the latest release just go missing?

**Comment by nikizslick** [comment]
I was wondering why 2.0.2 was showing. I wasn't paying attention and installed it before I realized what happened. I don't see anything in the releases past 2.0.2. Luckily I still had the download file for 2.1.0 in case I needed to reinstall

**Comment by turannul** [comment]
what's the difference Should I upgrade?

**Comment by marcopixel** [comment]
Huh, interesting...

It seemed like GitHub did "hide" the latest release for some unknown reason, but not remove it entirely.
Anyways, it should be fixed now :)
