### ISSUE TITLE
Visualizor malfuntion? pls halp?

### ISSUE THREAD

**Issue by owoMermaid** [MarcoPixel/Monstercat-Visualizer#381]
### The Bug
The visualizer bar doesn't react to the current song playing. Everything else works perfectly, even customization of the visualization bar. Did I do something wrong? Also tested multiple songs, messed with the customization, refreshed the skin and restarted Spotify

### To Reproduce
Problem was present from first launch; have no idea how to reproduce

### Screenshots
![image](https://user-images.githubusercontent.com/48803539/161420210-78c9dcab-5dbf-4496-b02c-e5f3c125571a.png)

### System information
Rainmeter Version: 4.5.13.3632 65bit
OS Version: Windows 10 Home 2009 64-bit (build 19043)
Skin Version: Version: 2.1.0
Spotify Version: 9.1. 57

**Comment by mermaidexe** [comment]
Also tested multiple songs, messed with the customization, refreshed the skin and restarted Spotify

**Comment by owoMermaid** [comment]
So I found out that having Razer's 7.1 Surround Audio set as my default device for output (for Desktop Speakers) and TXH Spatial Audio (which is used instead of the Headset to increase audio fidelity and clarity) PREVENTS the visualizer from interacting with the sound. >:( 
So setting it to the speakers themselves restores the functionality. WTF >:( Sorry for posting an Issue, just found the solution.
