### ISSUE TITLE
Spotify plugin not returning any data

### ISSUE THREAD

**Issue by chucklez32** [MarcoPixel/Monstercat-Visualizer#40]
Tried uninstalling and reinstalling spotify and plugin but I am left with the same album cover with no song information. This is what it looks like http://imgur.com/a/GMPFC

The visualizer works just not the song title and info with Spotify, and yes I did check that I am using the latest spotify plugin and latest rainmeter.

**Comment by MarcoPixel** [comment]
Could you please send a screenshot from the debug log of Rainmeter (https://docs.rainmeter.net/manual/user-interface/about/) and post it in here.

Also please write down your OS version, Rainmeter version and skin version.

And then try the different troubleshooting steps I posted in #18 and report back if anything worked.

**Comment by chucklez32** [comment]
Okay so for post #18 ; I have tried everything besides completely reinstalling rainmeter, I did however redownload the 4.0 release and installed that to make sure that rainmeter was running the 4.0 version but I did not do a complete uninstall and reinstall.

As for the debug here ya go; 
![rainmeter2](https://cloud.githubusercontent.com/assets/17074148/24816448/c9468d62-1ba6-11e7-8fd9-b10ade845092.png)

Windows 10 64bit, Latest 4.0.0 r2746, Latest 1.6

**Comment by MarcoPixel** [comment]
Add the following code bit to the visualizer.ini and refresh Rainmeter:
```
[MeasureDEBUG]
 Measure=Plugin
 Plugin=SpotifyPlugin.dll
 Type=DEBUG
 Verbosity=0
```

It should open an console and in there you should see the errors which causes the Spotify plugin not to run.

**Comment by tjhrulz** [comment]
I dont know why raptor doesn't just use the built in rainmeter debugging.

Also do you have the Left or Right skin activated? It should be showing N/A even if spotify isn't working and I see in your debug info that ActivateConfig threw an error.

**Comment by chucklez32** [comment]
Okay so I put in that code and its a constant updating stream of info in the console but when I freeze it and screenshot it I get this;
![rainmeter3](https://cloud.githubusercontent.com/assets/17074148/24817602/224223aa-1bab-11e7-8dc7-bc975af3980b.png)

Also @tjhrulz I dont know if I have either activated to be honest? I went through the setup again (The visualizer setup) and dont see anything about Left or Right skin.

**Comment by MarcoPixel** [comment]
@chucklez32 Your system setup blocks the DNS server of the plugin. Try disabling your antivirus, check if Rainmeter and Spotify are allowed in the firewall and check your [hosts file](http://www.thewindowsclub.com/hosts-file-in-windows) if there are any blocked spotify servers.

**Comment by chucklez32** [comment]
@MarcoPixel I dont have a antivirus just windows defender. I looked into my firewall settings and Spotify is there and allowed but I did not see rainmeter so I added it to allow it. Refreshed and saw no change. Finally I looked at my hosts files and nothing there shows any blocking of spotify servers. Whats weird is this is on my laptop running Windows 10 but on my desktop running the same OS the visualizer and song info works perfectly.

**Comment by MarcoPixel** [comment]
Hmm, could you try changing the DNS server to the [Google DNS ](https://www.howtogeek.com/164981/how-to-switch-to-opendns-or-google-dns-to-speed-up-web-browsing/) and check if you can access https://open.spotify.com/token with these settings.

**Comment by chucklez32** [comment]
@MarcoPixel That did it! Changing my DNS to Google's worked! Funny enough I do remember changing my desktops DNS to use googles a while ago for other reasons but that might of helped prevent this issue on there. Weird issue but thanks for the help! :)

**Comment by tjhrulz** [comment]
@chucklez32 You will have to manually activate the left or right skin, they are no longer included in the cover skin. @MarcoPixel Should we maybe activate left by default to fix that confusion in the future?

**Comment by MarcoPixel** [comment]
@chucklez32 Great that it worked. Gonna add this solution to the troubleshooting page soon, thanks for your cooperation.

@tjhrulz It should be activated via the Intro.ini skin which gets activated the first time installing the skin. Maybe @chucklez32 disabled the skin loading after installing the skin or it got closed somehow. But normally it should activate at first installation.

As this issue is fixed, i will close this issue. If there are any more issues with your system, please reopen this issue.
