### ISSUE TITLE
Unable to get album art

### ISSUE THREAD

**Issue by agentn645** [MarcoPixel/Monstercat-Visualizer#403]
### Describe the bug
[Hi, I'm having an issue where my cover art suddenly stopped working and only shows the monstercat logo. The song title and artist work and update though, currently I'm on 1.2.17 Spotify and the latest version of Rainmeter.

I was on 1.2.19 for Spotify, downgraded to 1.2.18, still didn't work, downgraded to 1.2.17 still doesn't work. I restarted my computer. I uninstalled spicetify altogether and reinstalled it, I've uninstalled the visualizer and reinstalled it, none of these have worked. The song title and artist are updated and recognized so it's not an issue of the visualizer not connecting to spicetify it only does not show the album cover specifically. ]

### Screenshots
[ If applicable, add screenshots to help explain your problem. https://imgur.com/a/kFiVd7L ]

### System information
* **Rainmeter Version:** [Rainmeter 4.5.18.3727 (64-bit)]
* **OS Version:** [You can check this here: Windows 10 Pro 22H2 (build 19045.3448) 64-bit - English (1033)]
* **Skin Version:** [Version=2.1.0]
* **Spotify Version:** [1.2.17.832.g15fa351e]

### Additional context / media
[ In the rainmeter log it says Unable to get album art from: https://i.scdn.co/image/ab67616d0000b2738c489aa548f8ad7a4f078abd for each song ]

**Comment by MatiPlayzzYT** [comment]
having the exact same issue, haven't found a fix yet

**Comment by Blimply** [comment]
This skin bundles an unmaintained version of WebNowPlaying. Installing the Rainmeter Skin for WebNowPlaying-Redux (latest release at time of posting at https://github.com/keifufu/WebNowPlaying-Redux-Rainmeter/releases/tag/2.0.7 ) to update the plugin fixed this issue for me.

I also needed to update spotify and reapply spicetify after installing WebNowPlaying-Redux.

**Comment by agentn645** [comment]
> This skin bundles an unmaintained version of WebNowPlaying. Installing the Rainmeter Skin for WebNowPlaying-Redux (latest release at time of posting at https://github.com/keifufu/WebNowPlaying-Redux-Rainmeter/releases/tag/2.0.7 ) to update the plugin fixed this issue for me.
> 
> I also needed to update spotify and reapply spicetify after installing WebNowPlaying-Redux.

this worked!!!! thanks so much !!

**Comment by fuzzstrings** [comment]
ran 'spicetify upgrade' as well and a new version (2.23.2) was available. updated spotify and then ran 'spicetify restore backup apply' and we're back in business!
