### ISSUE TITLE
How to change order of visualizer bars?

### ISSUE THREAD

**Issue by pacificapilot** [MarcoPixel/Monstercat-Visualizer#45]
I am trying to get two instances of the visualizer running side by side, with the one on the right being reversed so that the bass is on the right, and the treble is on the left, but whenever I modify one of the .ini files, it reverts back automatically. Is there a way I can accomplish my goal here, whether it be by saving the files successfully, or by having some other method to reverse the visualizer?

**Comment by tjhrulz** [comment]
What is your file setup like? You need to make sure both copies of the monstercat visualizer are in different folders under your ~/documents/rainmeter/ or they will share the same variables file.

**Comment by pacificapilot** [comment]
I already have them in separate folders. Screenshot:
![screenshot 4](https://cloud.githubusercontent.com/assets/27872830/25301102/6c5485b6-26e4-11e7-8c83-091bab8992a9.png)

**Comment by tjhrulz** [comment]
Alright next question how are you changing the order so the order of the visualizer, are you modifying the builder or the .inc file? Because the .inc file gets rewritten on every refresh

**Comment by pacificapilot** [comment]
I was attempting to edit the .inc file. What file should I be modifying to get what I want? The other .ini files don't seem to have anything that I can modify to solve my issue...

**Comment by tjhrulz** [comment]
In the Visualizer.ini on line 51 is the section [ScriptFactoryBars] that will set the options for every bar in the MeterBars.inc file. Use %% for counting and enclose it in {} if you need to do math. 

If you are just reversing the order of the bars give me a minute and I will edit this with the code I gave someone in the discord chat a few days ago.

**Comment by pacificapilot** [comment]
This did not work. I changed the value, and first all the bars accumulated into a single space. I fixed that by changing it to:  Value3=MeasureAudioSmoothed{#BarCount#-%%-1}R
However, the bars did not reverse, and now there is no spacing between them, which cannot be modified in the normal settings window built into the skin.

**Comment by tjhrulz** [comment]
Sorry for the delay getting back to you. 

My guess is that code I gave you referred to the line number and variable name from a newer version of the monstercat visualizer than the one you are looking for two lines in a row that should look like this 

Option2=MeasureName
Value2=MeasureAudioSmoothed{%%}

The number that comes after option and value does not matter just keep it the same and change the end of that second line to =MeasureAudioSmoothed{#BarCount#-%%-1}

**Comment by tjhrulz** [comment]
@MarcoPixel Also since I have seen multiple people request flipping the order of the measure bars like this maybe this should be added to the settings?

**Comment by pacificapilot** [comment]
Thanks so much for the help! I got it working, and it looks legit. Finished product: 
![screenshot 9](https://cloud.githubusercontent.com/assets/27872830/25468762/9364652a-2add-11e7-88b2-4d820238da3a.png)

**Comment by tjhrulz** [comment]
Nice, glad to see we could get it working.
