### ISSUE TITLE
Mouse sliders in settings not changing settings

### ISSUE THREAD

**Issue by Cryptikz** [MarcoPixel/Monstercat-Visualizer#47]
Only changing the color of the visualizer works, scale and sizes for things, do not.

**Comment by Cryptikz** [comment]
Windows 10, Rainmeter 4.0

**Comment by GMR516** [comment]
Can confirm issue.

**Comment by MarcoPixel** [comment]
Hmm, weird. It working on my system with the current beta version of Rainmeter (4.1.0 beta r2793) with the latest release and also working with the current repo source.

Could you please send a screenshot from the debug log of Rainmeter (https://docs.rainmeter.net/manual/user-interface/about/) and post it in here.

Also please write down your OS version, Rainmeter version and skin version.

**Comment by tjhrulz** [comment]
Are you using the new settings with the slider for this? Unfortunately the way the plugin works right now you can not just click where you want it to be set but must click and drag for it to set.

**Comment by Cryptikz** [comment]
https://puu.sh/vOXLX/198b0cde95.png this is what it currently looks like... Can't move any of the bars no matter the method...

**Comment by Cryptikz** [comment]
https://puu.sh/vOXX1/3637aeaa2a.png here is my Log

**Comment by Alipoodle** [comment]
I've also had this problem, along with a few others (Which i'll put in another issue)
The settings does become unresponsive, still displays, even after Refresh.

Some of the other settings have got me confused, this was mainly noticed within the Visualiser section where i would have to double click to get something to edit. Other objects update, but the settings does not seem to update.

**Comment by tjhrulz** [comment]
I am also encountering some these issues. Unfortunately fixing some of them is going to require a rewrite, until then to mitigate just only mouse down and up on the same settings bar and don't leave it while changing it. (Also note just clicking will not work you have to move your mouse after mouse down due to mouse slider limitations)

**Comment by Cryptikz** [comment]
Oh..... I see now.... You use the mouse wheel! I didn't realize that's how it worked... I would recommend maybe putting that somewhere in the settings design, I would have never known...

**Comment by tjhrulz** [comment]
Actually it does not exclusively use mouse wheel, you should be able to do both.

**Comment by Cryptikz** [comment]
Oh, only mouse wheel works for me, I'm just saying other people may have the same problem I do, and the multiple ways to change settings should be advertised.

**Comment by tjhrulz** [comment]
Alright guy if you wanna try the new settings tweaks I did to see if they are working for you, feel free. Just 
install 1.7.0 normally if you have not already and then download this zip https://github.com/MarcoPixel/Monstercat-Visualizer/archive/Performance.zip with any luck this should resolve almost all your problems.

**Comment by tjhrulz** [comment]
@MarcoPixel The rotation angle in the settings do you want that to be a float or an int? I made it an int since you have it displaying that way and so people dont get mad it is off by 0.5 degrees, if you want to keep it as a float I would recommend that we display it as one as well.

**Comment by MarcoPixel** [comment]
@tjhrulz Sorry for the late response. The rotation angle should be an integer too because there is no need for such fine adjustments for the angle.

**Comment by tjhrulz** [comment]
Alright @MarcoPixel I'll leave that as an integer, I have also finished adding support for mouse click and drag on the progress bar if you want to try that as it is slightly related to this bug.

**Comment by tjhrulz** [comment]
Also I have not yet added to ignore clicks if spotify is the player as it seems .raptor is [adding support for seeking](https://forum.rainmeter.net/viewtopic.php?p=135122#p135122). Do you want me to go on ahead and look into supporting it? It uses a different command so I will need to do some calculations, I also requested he make support for the standard SetPosition bang.

**Comment by MarcoPixel** [comment]
@tjhrulz Let's keep it out for now as it is not a finished release and might contain some bugs. As soon it got released we can include it and implement it into the skin.

**Comment by tjhrulz** [comment]
Alright, I'll make it throw away the spotify clicks now, once I do that do you want me to merge my branch to master?

**Comment by MarcoPixel** [comment]
@tjhrulz If it works, create an pull request and merge it 👍

**Comment by tjhrulz** [comment]
Submitted pull request.

**Comment by Jazzxhands** [comment]
Kinda late to the party, but I'm also having this issue, and have noticed that if I drag my cursor far to the left of the slider, then it will update. I suspect this could be because I have a high dpi screen

**Comment by MarcoPixel** [comment]
@Jazzxhands I will release an update today with all the fixes @tjhrulz made.

**Comment by MarcoPixel** [comment]
This should be fixed with 1.7.1 release, please redownload and report back if it worked.

**Comment by Jazzxhands** [comment]
Works for me! Thanks

**Comment by MarcoPixel** [comment]
Okay, great. Gonna close this issue now :)

**Comment by FirstTimerGaming** [comment]
Same problem but Im on a tablet pc. Plugging a mouse dosent help either. I didnt know youvcould use the scrool wheel.
