### ISSUE TITLE
Possibility of Groove Music Support

### ISSUE THREAD

**Issue by jonseppanen** [MarcoPixel/Monstercat-Visualizer#56]
Groove music is now quite a good music player, especially with the free onedrive with a sub. Is it possible to get support for this?

**Comment by MarcoPixel** [comment]
Hello @jonseppanen,

thanks for your request.

Currently it's not possible to include the Groove Player into the skin, as the player itself is not compatible with Rainmeter. To use the Groove player either the Rainmeter developers or a crafty plugin creator have to make a plugin or an implementation directly first.

I would recommend you posting a feature request on the official forums (https://forum.rainmeter.net/viewforum.php?f=14).

I will close this issue as this is a feature which cannot be implemented right now.

**Comment by tjhrulz** [comment]
While I make no promises that it will ever be finished/added I am looking into either making a standalone plugin or adding Groove to the list of supported NowPlaying players.
