### ISSUE TITLE
No dynamic genre color with CAD/MusicBee with 1.7.0+

### ISSUE THREAD

**Issue by cab13140** [MarcoPixel/Monstercat-Visualizer#57]
Hey !
Found this when updating. All my genres are well tagged. Was working fine also before the update. I have not tested with another player, just with MusicBee with CAD plugin enabled.

**Comment by tjhrulz** [comment]
I'm away from a computer for the rest of the day but I must have broken this somehow with my color changes. I'll try to get on to check it out tonight when I get to relatives house. 

My bet is that the set option command to refresh the colors is not running on genre change.

**Comment by tjhrulz** [comment]
Well I am a giddy goat. I forgot to turn on dynamic variables in the measure that handles the switching between genre and cover colors. Since genre used a variable and not a measure it would not update correctly. Once I get my dev machine online I'll push a commit.

**Comment by cab13140** [comment]
Can you link the specified commit to quick-fix on my local files, or at least to push a pr ?

**Comment by MarcoPixel** [comment]
He linked with the closing commit. check d98b987697ce75a31080d0178e43836d8a032a5f.

**Comment by tjhrulz** [comment]
The commit gets linked automatically when I closed the issue in the commit but if you need a link because your GitHub app doesn't support/show it it's https://github.com/MarcoPixel/Monstercat-Visualizer/commit/d98b987697ce75a31080d0178e43836d8a032a5f

Also for future reference you can merge changes from here to your repo without any action on our end.

**Comment by cab13140** [comment]
Will clone that. Thanks for the quick fix

**Comment by tjhrulz** [comment]
Well given it existed for a month without anyone knowing I wouldn't call it quick 🤣 thanks for reporting it
