### ISSUE TITLE
iTunes music without local copy has no album art

### ISSUE THREAD

**Issue by jdliebs52711** [MarcoPixel/Monstercat-Visualizer#58]
Sorry i am a newbie with Rainmeter and i love your visualizer it's awesome but when i use it with iTunes it won't show the cover art. it works fine in Spotify but i seem to be missing a step i think. Any help would be awesome. thanks. I attached a picture.

Josh
![capture](https://user-images.githubusercontent.com/29279644/26932719-5abd2f88-4c32-11e7-8ce2-681bc694148d.JPG)

**Comment by tjhrulz** [comment]
If using music that is not local on your machine but in your iCloud it will not show a cover for it as rainmeter can only show copies of pictures on disk. Is the music in your iCloud?

**Comment by jdliebs52711** [comment]
I subscribe to Apple Music premium but I download the music so that I have it available when offline so that’s probably why. But Spotify shows up just fine and isn’t that generally the same as apple music?

Joshua D. Lieberman
25231 Orchard View Terrace
Chantilly, VA 20152
571.294.9798.
joshuadlieberman@outlook.com

**Comment by tjhrulz** [comment]
It may be a big with now playing then not pointing to the cover location correctly, our iTunes info API may not support grabbing album art of music you don't own (Music companies can be weird about that kind of stuff sometimes)

To help figure out what's up listen to one of the songs that does not work, right click on the icon for rainmeter and go to about. A new window should pop up, clock on the skins tab. In the left pane click on Monstercat-Visualizer\Song Information\Cover. In the right pane now find a measure called measure cover and copy paste/screenshot what it's value is.

**Comment by jdliebs52711** [comment]
It’s now working. I think it was just that I was playing music that simply had not been downloaded. Not sure how I missed that!!

Anyway, thanks for this awesome skin!
Take Care!
Josh

**Comment by tjhrulz** [comment]
Would you still be willing though to play one that is not downloaded and tell me the results of that? Because it may be possible that we can add support for that

**Comment by jdliebs52711** [comment]
Ok, with apple music/itunes the icloud track plays without the album art (the song information is still available) and then I checked with an online song in Spotify and that does show the album art. Then I just went back to iTunes and played a downloaded song and the album art did show up again.

I hope that’s helpful.

**Comment by tjhrulz** [comment]
Can you do the steps I outlined above when you have a song from online in iTunes. 

Also Spotify support does works just fine with online because of how the plugin works, iTunes is the one that does not

**Comment by jdliebs52711** [comment]
Is this what you are looking for?

**Comment by tjhrulz** [comment]
Was there supposed to be an image attached with that post?

**Comment by jdliebs52711** [comment]
Yeah sorry. The 2nd time this week that has happened to me!

Joshua D. Lieberman
25231 Orchard View Terrace
Chantilly, VA 20152
571.294.9798.
joshuadlieberman@outlook.com

**Comment by tjhrulz** [comment]
Still no image, since you are replying from email I don't think it adds attachments.

**Comment by jdliebs52711** [comment]
How about now? It should be an attachment

**Comment by tjhrulz** [comment]
Nope, just post it on the GitHub issue page or upload to imgur and post a link

**Comment by jdliebs52711** [comment]
![capture](https://user-images.githubusercontent.com/29279644/26947622-63b688a8-4c61-11e7-9668-e6c6eeb3a170.JPG)

**Comment by tjhrulz** [comment]
Okay yeah this is a bug/feature issue with the nowplaying plugin. I'll talk to Azack or someone and see if we can add support for it tonight.

**Comment by jdliebs52711** [comment]
Awesome thank you sorry for the 3 messages with no image!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by tjhrulz** [comment]
It's all good man

**Comment by tjhrulz** [comment]
I have isolated the cause of the issue in the NowPlaying plugin and have fixed it but I am not 100% sure of what the intent of the code that stopped it from being used was for. I will talk to Brian or someone and try to get it commited into rainmeter before the next rainmeter beta comes out.

**Comment by tjhrulz** [comment]
I have submitted the changes to the NowPlaying plugin to fix this bug. You can track the status of the pull request here: https://github.com/rainmeter/rainmeter/pull/107

**Comment by tjhrulz** [comment]
The request has been merged and will be in the rainmeter beta

**Comment by jdliebs52711** [comment]
Awesome!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
