### ISSUE TITLE
Visualizer Not Visualizing

### ISSUE THREAD

**Issue by TheSecksyElf** [MarcoPixel/Monstercat-Visualizer#60]
Hey, I'm a fairly new Rainmeter user, so I'm not entirely sure if this is a me problem, or it has something to do with rainmeter or the visualizer.

When I set up the visualizer, it worked fine and all the parts worked the way I wanted it to. Recently, however, when I play music, the visualizer won't work. And it's not that it just doesn't work, but right-clicking and alt-right clicking doesn't even bring up the rainmeter option menu. In the rainmeter menu, it shows the skin is loaded and only has the option to unload. I've tried to unload/reload/refresh the skin, and it does nothing.

 I do also have a couple of other skins running along with it.
Any ideas?

**Comment by tjhrulz** [comment]
Did you try restarting or reinstalling rainmeter?

**Comment by TheSecksyElf** [comment]
Restarting rainmeter didn't work. but reinstalling rainmeter isn't a thing I tried. I am currently reinstalling the visualizer from scratch, and it seems to be working fine that way. I'll get back to you if it happens again (and with the results of a rainmeter re-installation).

**Comment by tjhrulz** [comment]
Yeah I would say maybe it was related to a bug I had a while back but you tried unoading and reloading it. Either way glad it's working now. I'm gonna go on ahead and close this issue, if it happens again just reopen this issue.
