### ISSUE TITLE
[Request] Pull music information from Windows music controls

### ISSUE THREAD

**Issue by Kdriadon** [MarcoPixel/Monstercat-Visualizer#61]
When using different sources such as spotify, groove, pandora, they all have different apps but they all use the windows media controls. If you could pull the song information from there you wouldn't have to select one input source, but instead could use multiple apps.

**Comment by tjhrulz** [comment]
Marco's stance on this is that there has to be a plugin for this kind of stuff.

However when I last checked it is impossible to retrieve that information as there is no windows function for that and it can not be overloaded to send that info to rainmeter.

Everything I can think of except groove support though either a plugin exists for or will be added with my WebNowPlaying plugin though.

**Comment by Kdriadon** [comment]
Thank you for the quick reply and information
