### ISSUE TITLE
Song information clipping on wrong side of right song info

### ISSUE THREAD

**Issue by K-guy** [MarcoPixel/Monstercat-Visualizer#62]
The beginning of titles and artist names in is clipped at the start. Kind of bugging me out, cause it could have just clipped at the end only (I put on that setting too)
I don't know whether it is a bug or you decided to put it that way
I use MediaMonkey
![screen](https://user-images.githubusercontent.com/29385739/27053681-6d126bb4-4fbe-11e7-9f58-2b935df4be81.JPG)

**Comment by tjhrulz** [comment]
So this seems to be caused whenever song information scale is smaller than visualizer scale. @MarcoPixel I think something is wrong with in the right align's math

**Comment by K-guy** [comment]
Changed the scale to below the visualizer's scale, and it's okay.
Thanks
![desk2](https://user-images.githubusercontent.com/29385739/27093846-729c6a4e-5068-11e7-897a-7a811b2482e4.JPG)

**Comment by MarcoPixel** [comment]
I'm still not that satistfied with the right-aligned song information so i might rework it in the next few days.

I'll keep this issue open for any progress on the issue.

**Comment by tjhrulz** [comment]
I have some old code I wrote to right align am older version of the visualizer, let me see if I can find it when I get back to hotel tonight and see if it works better.

**Comment by tjhrulz** [comment]
Marco I just noticed today this may have something to do with the bounding box for the visualizer being smaller than the bars are, this also causes clipping with the last bar when rotating. I don't know if it never got fixed but the old glitch with the pixel gap being one larger than specified seems to still exist and may be the cause of it.

![image](https://user-images.githubusercontent.com/4722934/28952304-45bb50e0-789e-11e7-8de5-8e38cba92e26.png)
