### ISSUE TITLE
Change border color to be inverted depending on wallpaper

### ISSUE THREAD

**Issue by MarcoPixel** [MarcoPixel/Monstercat-Visualizer#66]
Requested by jsherry47 on DeviantArt.

Change the color of the border accodingly to the background. This could be done via the Chameleon plugin.

**Comment by tjhrulz** [comment]
Not sure the fesability but would it be possible to generate a complentary color based on the region of the wallpaper it is in? It may match better

**Comment by MarcoPixel** [comment]
It would technically possible, but it might use a lot more CPU since it has to crop it first.

> You might find it useful to only grab colors from a cropped region of an image. You can do so with the CropX, CropY, CropW, and CropH options. These set the position and dimension of the rectangle to crop out.
https://github.com/socks-the-fox/chameleon

**Comment by tjhrulz** [comment]
I would have to look at Sox's code to be sure but it may be faster since it has to iterate over a smaller section of the image. 

The bigger issue would be we would actually have to calculate the complentary color and it may look out of place sometimes I guess. Shame chameleon does not have color palette options similar to Android.

**Comment by tjhrulz** [comment]
Marco what if we replaced chameleon with an in house color gen that generated colors similar to android palette system? I have thought about making one like that in the past and it may generate a better foreground color than chameleon and would also generate a complementary color which will help make sure it does not blend in too much.

Example: http://jariz.github.io/vibrant.js/

**Comment by MarcoPixel** [comment]
I'm gonna close this one as this is currently not possible without a new plugin as Chameleon doesn't take dynamic variables as CropX and CropY.

If we are gonna change the plugin in the future, we will reopen this issue to keep track of it.
