### ISSUE TITLE
Add Support for Dopamine

### ISSUE THREAD

**Issue by Sleetui** [marcopixel/Monstercat-Visualizer#67]
Which you mind adding support for all your visualizers for Dopamine :)

https://github.com/digimezzo/Dopamine

**Comment by EMLVIRUS** [comment]
@Sleetui Dopamine has not any necessary API to support rainmeter yet. And it's audio play's duty to implement such a support.

**Comment by tjhrulz** [comment]
We could always go the old Spotify route, does it display the song info in the window title?

But yeah if it has an API that would make making a plugin much better

**Comment by MarcoPixel** [comment]
https://github.com/digimezzo/Dopamine/issues/252 - Here is the issue on the Dopamine repo.

**Comment by EMLVIRUS** [comment]
So now, external control is rather stable now though the sample is of C# instead of C++. Maybe it's now the time to take a look into this?

**Comment by tjhrulz** [comment]
Yeah I'm on it, I'll look into seeing if we can integrate it into the official now playing plugin tonight. If we can not I will make a standalone plugin when I get the time to.

**Comment by tjhrulz** [comment]
Just to kinda post an update I have been busy on other more important projects and have decided that instead of rolling out a standalone plugin for dopamine it will be part of my merged music plugin. Probably will be a few weeks before I get around to it.

**Comment by tjhrulz** [comment]
I have started work on my UnifiedNowPlaying plugin. Given the scale of it it will probably 2 weeks before it is beta ready and 3 or 4 before I can have it ready to implement in Monstercat Visualizer if Marco will allow me.

**Comment by marcopixel** [comment]
I will close this issue for now until there is a plugin which supports Dopamine.

Please comment down below if there is any progress made!
