### ISSUE TITLE
Mirror bar order and progress bar options?

### ISSUE THREAD

**Issue by tjhrulz** [MarcoPixel/Monstercat-Visualizer#70]
A lot of people seem to always ask me how to reverse the order of the bars. Since it is a pretty simple change why do we make mirroring that and the progress bar options. 

This will be nice for those who found the rotate options a step back since everything was backwards at180°

**Comment by tjhrulz** [comment]
To reverse the order of the bars in the current dev version change line 70 in visualizers.ini from
`Value3=MeasureAudioSmoothed{%%}`
to
`Value3=MeasureAudioSmoothed{#BarCount# - %% - 1}`

**Comment by MarcoPixel** [comment]
It works, but the only issue remaining is that the skin needs to be refreshed twice to apply those changes. We might be able to do it with a measure though, so i need to further test that out.

**Comment by tjhrulz** [comment]
At least flipping the bar around is as easy as an option
