### ISSUE TITLE
Keep visualizer bars at 0 instead of hiding when media player closed

### ISSUE THREAD

**Issue by tjhrulz** [MarcoPixel/Monstercat-Visualizer#71]
Just a thought I had it might be useful to make it that instead of hiding the visualizer it ignores all sound. I'm not at a computer right now but I think it would be pretty simple to write a always return 0 if player state is 0 if condition. Then just having it either on top of or replace the current hide method.

**Comment by MarcoPixel** [comment]
Not working with Spotify - needs some small modifications because Spotify is returning PlayerState wrong

**Comment by tjhrulz** [comment]
Found the cause, seems to be the PlayerSpotify.cpp file calculates the playing status wrong.
It is currently
```
if (track != m_Title || artist != m_Artist)
{
	m_State = STATE_PLAYING;
	m_Title = track;
	m_Artist = artist;
	++m_TrackCount;

	if (m_Measures & MEASURE_LYRICS)
	{
		FindLyrics();
	}
}
```
So the state playing is only changed on song change or when it is paused. I can submit a PR but given that this would then only exist in the 4.1 beta how do we want to proceed? We could either raise the minimum version or switch to getting the play state from the spotify plugin but it seems to work differently and not differentiate between stopped and paused and then we have no way to use the now playing bangs. 

As I mentioned before I could implement the code to replace the spotify plugin in webNowPlaying but that probably is at least a week away and to fully replace it was not my original intention.

**Comment by tjhrulz** [comment]
Did not hear back from any devs so I just sent a patch in https://github.com/rainmeter/rainmeter/issues/115

**Comment by brianferguson** [comment]
[Committed](https://github.com/rainmeter/rainmeter/commit/06840fc7a6d049b3e59420c49ae034ebe957afee).

-Brian

**Comment by tjhrulz** [comment]
Fixed in latest rainmeter beta.
