### ISSUE TITLE
 Visualizer not working - Failed to Initialize Audio Client

### ISSUE THREAD

**Issue by MrVincentC** [MarcoPixel/Monstercat-Visualizer#72]
Howdy,

I recently downloaded Rainmeter and the Monstercat Visualizer onto my computer and have been having issues with the bars not responding to music at all. The Track Info and Album Cover skins work perfectly, however the visualizer bars remain at zero despite music playing through the speakers. I am playing music from the Spotify Desktop App.

After checking the Rainmeter log, I am constantly receiving this Warning while the Visualizer skin is loaded: "Failed to initialize audio client" 
http://imgur.com/gallery/I3zxS

Things I have tried:
- Updating my audio driver of my Motherboard
- Reinstalling Rainmeter, Spotify, and the visualizer skin
- Adjusting sensitivity, checking to see if Rainmeter is muted in volume mixer, setting my speakers to default.
- Everything on the troubleshooting guide (https://forum.rainmeter.net/viewtopic.php?p=123883#p123883) except for putting my device ID into the skin due to lack of knowledge on how to do so. I downloaded the ExampleAudioLevelSpectrum skin but it didn't do anything when loaded except give a few gray bars.

Something I noticed: In the Monstercat Visualizer settings I can choose to change the audio device in the General tab, but nothing shows up on the current audio device next to it. I also noticed when using the Audio Device Information skin from step 6 of the troubleshooting list that nothing is registered as my Default Output Device, despite having it set as my speakers in Windows. Here is a picture of what I mean: http://imgur.com/gallery/oUIL4

I am running Windows 10, Rainmeter Version 4.0.0 r2746 64-bit, and Monstercat Visualizer Version 1.7.1

Thank you in advance for helping and let me know if you need any other information

**Comment by MrVincentC** [comment]
One other comment I forgot to add: I have tried using other visualizers to check (Radian's LinearVisualizer to be exact) and the bars also do not respond to music.

**Comment by tjhrulz** [comment]
This is clearly an issue with the audio plugin so not a lot we could do here.

However if I had to guess it may be that the name of one of your audio devices is causing an issue. Wanna screenshot your windows audio devices window? Preferably show disabled and disconnected devices when you do it.

If it is not that try uninstalling and installing any drivers for any audio devices in there or disabling all but one of the audio devices and restart rainmeter (fully exit and relaunch rainmeter not just the skin) and see if you can even get that menu to see anything.

**Comment by MrVincentC** [comment]
Thanks for the reply! 

I had a feeling it was a problem with the audio plugin and not the skin itself, I just didn't know who else to ask help from and a Google search didn't help that much. Below is the screenshot of the audio devices I have right now. The speaker is an old iHome speaker connected to the rear audio jack via 3.5 mm cable. I'll see what I can do about updating audio drivers on this thing (I tried updating it by updating them through the device manager, but still nothing).

![audio devices](https://user-images.githubusercontent.com/30558916/28803938-a3566576-7625-11e7-89e0-336f72de4b83.PNG)

**Comment by tjhrulz** [comment]
Can you scroll down to see the rest and screenshot it? But yeah I am not seeing anything out of place with those devices and I doubt the rest of them will be any different. 

Try though the disabling them all but the speakers you are using thing and rebooting rainmeter and see what that does.

**Comment by tjhrulz** [comment]
As for where to go try just going to the rainmeter forums and posting there since it is an official part of rainmeter these days.

**Comment by MrVincentC** [comment]
The last two things on the list were just two more "NVIDIA Outputs."

I'll try to disable everything and will get back to you if it works. I think I'll also post this issue on the rainmeter forums like you said. 

Once again, thanks for the help and quick replies!
![audio devices 2](https://user-images.githubusercontent.com/30558916/28806225-66dc12b2-7634-11e7-9b8f-3ce19456a323.PNG)

**Comment by tjhrulz** [comment]
Found this today, seems close to your issue. https://forum.rainmeter.net/viewtopic.php?f=14&t=25735

**Comment by tjhrulz** [comment]
Any luck getting it to work? If I dont hear back in a few days I will go on ahead and close this issue.

**Comment by MarcoPixel** [comment]
I'm gonna close this issue, @MrVincentC please write a comment below if you still got the issue and you want to reopen it.

**Comment by lenscreamo** [comment]
im using realtek, n after some hours of frustration i found out that when i use my bluetooth speaker (external audio) the visualizer works, but when i return on using my laptop (realtek) speaker, it just stop working and the 'failed to initialize audio client' popped back, i tested by removing my bluetooth speaker, restarted back my laptop so that it return to using the laptop's speaker (the same thing as if you just put your default laptop speaker which in my case is realtek back as default speaker), the visualizer doesnt work, so i can assume for now that anyone whos using the latest buggy realtek should opt to using external audio or simply downgrade realtek, although the last time i downgraded it, the visualizer still wont work, its a hassle though, but for now i would just opt to using my external bluetooth speaker ^^ hope it helps others, btw if someone found out which realtek version work without using external audio please do share, thx!

**Comment by dongtvse05344** [comment]
Go to Device Manager and Uninstall Speakers devides. Restart computer and it works for me.
