### ISSUE TITLE
Mouse.dll update seems to have messed up sliders

### ISSUE THREAD

**Issue by tjhrulz** [MarcoPixel/Monstercat-Visualizer#73]
It seems that in updating from 3.1 to 3.2 since Jon changed the way the plugin works it seems to have caused some issues. I will look into it tonight and see what is the issue.

**Comment by tjhrulz** [comment]
I take it back slightly, seems just the bar gap slider is messed up and looking at the documentation NeedsFocus seems to have been removed and seems to act like it is always enabled.

**Comment by MarcoPixel** [comment]
Was already fixed with cd35a0792e1d1e2d4d8193462da5573f1c2d388a.
