### ISSUE TITLE
Russian character

### ISSUE THREAD

**Issue by Scronheim** [MarcoPixel/Monstercat-Visualizer#74]
Russian character not displayed. Please add support the russian character
[screenshot](https://imgur.com/a/vty7g)

**Comment by Scronheim** [comment]
Should be "После"

**Comment by tjhrulz** [comment]
What media source are you using? It is either from NowPlaying or a font issue, likely a font issue.

**Comment by tjhrulz** [comment]
Try removing from the left and right .ini files anywhere where it says 
`FontFace=#Font1#` or `FontFace=#Font2#`

**Comment by MarcoPixel** [comment]
This is an issue with the font as it doesn't support cyrillic characters. 
This is not something we can fix as the font currently used is the nearest free alternative to the Gotham font face.

The best fix for you would be to obtain the **Gotham Bold** and **Gotham Light** font and replace them in variables.ini under the **Font1** and **Font2** variables.

I'm gonna close this issue for now till there is an alternative font which is free and similar to the current one.

**Comment by Scronheim** [comment]
oh, sorry. Thx for solution

**Comment by MarcoPixel** [comment]
No need to be sorry :)

Just get the Gotham Font from somewhere and you should be good to go :)
