### ISSUE TITLE
Filled Wave visualizer variant

### ISSUE THREAD

**Issue by dragonshardz** [MarcoPixel/Monstercat-Visualizer#75]
N/T. VisBubble has this, and while I don't mind colored bars, I'd like a variant that is a smooth wave with a defined border line and a filled region as well. I'm going to experiment a bit and see if I can knock it together myself, but I'm also making the request here because I don't fully understand how this skin works.

**Comment by tjhrulz** [comment]
This is outside the scope of this project as we want to recreate the Visualizer in the monstercat videos. You are welcome to make your own or use one from another project but it will not be merged into this.

**Comment by MarcoPixel** [comment]
Thanks for your request.

As @tjhrulz already said, this is something we don't want to do with the Monstercat Visualizer as this skin tries to keep it as similar to the videos.

If you search a visualizer with waves, try [ProteusChroma by MinerVaxcel](https://minervaxcel.deviantart.com/art/ProteusChroma-684655618).

_Sent from my Sony F8331 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
