### ISSUE TITLE
Not getting spotify metadata

### ISSUE THREAD

**Issue by Arynthesizer** [MarcoPixel/Monstercat-Visualizer#77]
Hello! I have checked the other issues from people that had a similar problem to me, but I could not fix this issue. The album art is incorrect, and I get N/A for the song title/artist. I have changed my DNS info to Google's DNS (i think, i am not too familiar with this stuff), I have restarted my computer, reinstalled both spotify and rainmeter. The metadata/album arts does not work for other visualizer plugins on Rainmeter either. It visualizes just fine, but I do not get proper album arts and song info.

I have tried the spotify token link, and get a long string of letters & numbers. NET Framework 4 is installed on my OS. I'm not in private or offline mode on Spotify.

I really appreciate any help!

EDIT: I also checked my host file. Every line has a # in front of it, so I presume that spotify is not blocked there.

![screenshot](https://user-images.githubusercontent.com/31020677/29295745-0320c1fa-8124-11e7-8034-a6d4f353d3d3.png)

**Comment by MarcoPixel** [comment]
Please download this file and replace it with your visualizer.ini:
https://gist.github.com/MarcoPixel/6575bc71c012934f087891fffb534145

After that, please refresh your Rainmeter skins by **Right-click -> Refresh** all and a command window should appear. Please make a screenshot/copy the log and post it in here.

Also please send a screenshot from the debug log of Rainmeter (https://docs.rainmeter.net/manual/user-interface/about/), your OS version, Rainmeter version, spotify plugin version and skin version so we can propertly check what the issue is.

**Comment by Arynthesizer** [comment]
After refreshing all my skins and waiting a while, the command window only says "console window activated!" twice every time I refresh the main visualizer.

![console](https://user-images.githubusercontent.com/31020677/29315160-a232a68a-818f-11e7-8897-a7dab7ac05fa.png)

The debug log has this one error message, that keeps popping up every 10 seconds.

![log](https://user-images.githubusercontent.com/31020677/29315189-d46c4ea8-818f-11e7-8b24-e76df832e113.png)

Running 64 bit windows 8 (build 9600), rainmeter beta 4.1.0 r2822, spotify plugin 1.3.0.1.

What is kind of weird is that the version is displayed in rainmeter as 1.7.0, but I have downloaded 1.7.1 and am reinstalling the skin using the 1.7.1 rmskin.

![screenshot_44](https://user-images.githubusercontent.com/31020677/29315380-0610118c-8191-11e7-991e-f71ded92ce67.png)

**Comment by MarcoPixel** [comment]
Yeah, it seems that it has issues connecting to the local webserver for Spotify. 

Could you try adding **http://spotifyplugin.spotilocal.com:4380/** to your exceptions in your antivirus software?

**Comment by Arynthesizer** [comment]
Ah, it works perfectly after I added the exception in my antivirus. Thanks for the quick response & help.
