### ISSUE TITLE
Artist name is cropped at the bottom on Japanese text

### ISSUE THREAD

**Issue by Ricardo1991** [MarcoPixel/Monstercat-Visualizer#78]
Rainmeter 4.1.0 beta r2838 64-bit (Jul 28 2017)
Windows 10 Pro Insider Preview 64-bit (build 16257)

![](http://i.imgur.com/1pNE26b.png)

Artist name: 目黒将司
Track Title: 母のいた日々

**Comment by buddywut** [comment]
![btscutoff](https://user-images.githubusercontent.com/31027389/29302615-aa6a44e8-8153-11e7-9b61-5c9366b073c2.png)

same thing with Korean text
(same build and windows)

Artist: 방탄소년단

**Comment by MarcoPixel** [comment]
Should be fixed and included in the next release! 

If you don't want to wait, please follow the manual installation instructions at the main page of this repo.
