### ISSUE TITLE
Visualizer displaying N/A as song and artist name even when a song is playing [iTunes]

### ISSUE THREAD

**Issue by pixelsandbacon** [MarcoPixel/Monstercat-Visualizer#79]
Title says it all

**Comment by MarcoPixel** [comment]
Could you please send a screenshot from the debug log of Rainmeter (https://docs.rainmeter.net/manual/user-interface/about/) and post it in here.

Also please write down your OS version, Rainmeter version and skin version.

**Comment by tjhrulz** [comment]
Closing issue due to no response.
