### ISSUE TITLE
Visualizer and Song Info Scale are not sanity checked

### ISSUE THREAD

**Issue by tjhrulz** [MarcoPixel/Monstercat-Visualizer#8]
Rainmeter does not support decimals without a leading 0, thus if the user does not know this and enters .8 instead of 0.8 in the settings ui the scaled content will disappear and cause rainmeter CPU usage to max.
<br />
<br />Not sure if the input from settings ui can be sanity checked easily, if not just slap a warning on it somewhere.

**Comment by tjhrulz** [comment]
I also totally didn't just accidentally do this and spend a minute wondering why my rainmeter was lagging all the sudden.

**Comment by MarcoPixel** [comment]
Bug was fixed with the commit 89f2b43e306175b8751ebb142a6e43371171b06e.
