### ISSUE TITLE
The Shadow Didn't Inverted

### ISSUE THREAD

**Issue by Matter-Shifter** [MarcoPixel/Monstercat-Visualizer#85]
I recently updated your visualizer and I found something messed up. Here.
![image](https://user-images.githubusercontent.com/28915146/29752429-6293bb58-8b90-11e7-93fc-9641eda734a6.png)

Kinda disturbing... The shadow didn't inverted somehow...

and there's some error too...
![image](https://user-images.githubusercontent.com/28915146/29752446-ae110de2-8b90-11e7-8dae-54a0867df17a.png)

**Comment by MarcoPixel** [comment]
Will be added in the next release, probably tomorrow or tuesday.

**Comment by Matter-Shifter** [comment]
Great. Thanks! 😄

**Comment by MarcoPixel** [comment]
Fixed in [1.8.1](https://github.com/MarcoPixel/Monstercat-Visualizer/releases/tag/1.8.1).
