### ISSUE TITLE
Everything but the visualizer is working

### ISSUE THREAD

**Issue by PBandZee** [MarcoPixel/Monstercat-Visualizer#86]
I'm on 4.1 Beta and installed everything correctly.  The album art, controls, and song information all work fine, even the progress bar!  The only thing not working is the actual visualizer which no matter what audio source I use does not move at all.  I updated my sound drivers, tried reinstalling, am listening on the correct sound device, and have done everything troubleshooting has told me to.  Please help!

**Comment by MarcoPixel** [comment]
Are you using Realtek drivers? Cause there is a bug currently that the newest drivers will not work with the Audiolevel plugin.

Try to remove any audio drivers and let windows redownload them, also try to remove any audio enhancers which might affect the audio output.

If it is still not working, please post your issue to the forums so i might get more attention of the developers:

https://forum.rainmeter.net/viewtopic.php?f=103&t=26499
