### ISSUE TITLE
visualiser picks up all audio

### ISSUE THREAD

**Issue by moo-sek-freak** [MarcoPixel/Monstercat-Visualizer#87]
is there any way around this? i want to have foobar open all the time but the visualiser on my other screen is distracting while watching youtube or other things

**Comment by tjhrulz** [comment]
Chose one of these two options. 
![image](https://user-images.githubusercontent.com/4722934/29996855-4b869a46-8fd4-11e7-94c5-cca5bde1369c.png)

**Comment by moo-sek-freak** [comment]
i had an older version
