### ISSUE TITLE
Add progress bar

### ISSUE THREAD

**Issue by MarcoPixel** [MarcoPixel/Monstercat-Visualizer#9]
Older request i forgot who it was from.

Add a progress bar on the bottom of the visualizer.

**Comment by tjhrulz** [comment]
are you planning on adding the ability to seek the song on click

**Comment by MarcoPixel** [comment]
First implementation of the progress bar added to [gpm](https://github.com/MarcoPixel/Monstercat-Visualizer/tree/gpm) branch with the commit c4648dc551bd02d233e3d298c46ec4e4fe212ab1.

**Comment by MarcoPixel** [comment]
Merged to [master](https://github.com/MarcoPixel/Monstercat-Visualizer/tree/master) with commit de3a2c49520586fee10ebb6aeffed43617dbd2cb.
