### ISSUE TITLE
Bar Width setting can't be changed

### ISSUE THREAD

**Issue by Thillonoz** [MarcoPixel/Monstercat-Visualizer#90]
Tried changing the bar width in the settings GUI and now it's stuck on 0px, refreshing / unloading & loading hasn't helped.

On RainMeter 4.0 r2746, Windows 7
This log is from loading the skin and the warnings at the top is from trying to change the value of "bar width" in the settings.
![monstercat rainmeter bug](https://user-images.githubusercontent.com/31669883/30080672-ae879624-9284-11e7-90b2-23c9a787c1e5.PNG)

EDIT: I am using Spotify and it did work until I touched the bar width setting.

**Comment by tjhrulz** [comment]
All your plugins seems to have not loaded. Try reinstalling the skin.

**Comment by Thillonoz** [comment]
OK I've figured it out. I made an error installing the plugins, they were under \AppData\Roaming\Rainmeter\Plugins\x64 , instead of being straight in the \Plugins folder. Weird thing is changing all the other parameters worked but changing the Bar width value crashed it.
