### ISSUE TITLE
Downloaded skin opens as an PDF file

### ISSUE THREAD

**Issue by alpharb** [MarcoPixel/Monstercat-Visualizer#91]
when I download the visualizer it keeps opening up as a pdf and not an application

**Comment by MarcoPixel** [comment]
https://github.com/MarcoPixel/Monstercat-Visualizer/releases/download/1.8.1/Monstercat.Visualizer.for.Rainmeter_1.8.1.rmskin

Download this file and try executing it. If it is still opening as an PDF, try reinstalling Rainmeter and check if Windows set the PDF reader as default applications for .rmskin files.

Here is an guide on how to change it: 
https://www.digitaltrends.com/computing/how-to-set-default-programs-and-file-types-in-windows-10/

**Comment by alpharb** [comment]
Thank you, it is now working
