### ISSUE TITLE
Can't get Spotify to work [N/A]

### ISSUE THREAD

**Issue by xFlushi** [MarcoPixel/Monstercat-Visualizer#92]
hello, i know this has been asked multiple times round here but i just can't get the plugin to work, i get this everytime i want to listen something on spotify:

![](https://image.prntscr.com/image/kuPVqQU7RTiF_lHDr0CFeg.png)

i already did a lot of things.
i switched to Google DNS, disabled antivirus,  added http://spotifyplugin.spotilocal.com:4380/ to my antivirus exceptions, added 127.0.0.1 spotifyplugin.spotilocal.com to my hosts file, disabled firewall, reinstalled rainmeter like 5 times, installed the new version of https://forum.rainmeter.net/viewtopic.php?f=18&t=17077

but absolutely nothing seems to work :(
thanks!

**Comment by tjhrulz** [comment]
Try removing that from your hosts file as it should not be needed and then doing a full reboot. Also you probably already did this and it should be set out of the box but in the settings menus for Monstercat Visualizer under player try selecting spotify

**Comment by xFlushi** [comment]
just did both things and none of them worked :(

**Comment by tjhrulz** [comment]
Oops my editied comment never posted. Check out these issues for more help https://github.com/MarcoPixel/Monstercat-Visualizer/issues/40
https://github.com/MarcoPixel/Monstercat-Visualizer/issues/77

**Comment by xFlushi** [comment]
#40 solution is changing my DNS to the google one and didn't worked
#77 solution is adding the exception to antivirus but it didn't work either

**Comment by tjhrulz** [comment]
alright can you please add the debug statement that was shown in those and post a picture of the info it gives you?

**Comment by xFlushi** [comment]
do you mean this?


![](https://image.prntscr.com/image/m1SCHC5XQDGmoxQhjViggA.png)

**Comment by tjhrulz** [comment]
That is not what I meant but that gave away the issue.
Why are you using the beta version of the spotify plugin? That thing is horribly broken right now and .raptor seems to not want to fix it.

**Comment by xFlushi** [comment]
done.
it seems like this thing hates me

![](https://image.prntscr.com/image/UogqxoF-RBuPy3aaa0_z5Q.png)

**Comment by tjhrulz** [comment]
Alright post the log again if you could. 

Also what I was talking about before was to download this file https://gist.github.com/MarcoPixel/6575bc71c012934f087891fffb534145 and replace your visualizer.ini with that and post a screenshot of the log that that then brings up.

**Comment by xFlushi** [comment]
done, i'm getting a console now but nothing changed
![](https://image.prntscr.com/image/-bX4B37RRgGnvpJpZtxSpg.png)

![](https://image.prntscr.com/image/5LmilLTSQJqS86D3GrsA-w.png)

**Comment by tjhrulz** [comment]
Are you using the desktop version of spotify?

**Comment by xFlushi** [comment]
yup, i'm using the desktop version downloaded from here
https://www.spotify.com/cl/download/other/

**Comment by tjhrulz** [comment]
Hmmm, maybe it is because you are using it in another language? @MarcoPixel any ideas or are we going to have to send him off to raptor and pray he will actually help?

**Comment by xFlushi** [comment]
i thought about that too so i put my spotify in english but nope, still getting this N/A thing.
definitely this plugin hates me and my whole pc. (which i formated like a week ago)

**Comment by tjhrulz** [comment]
Do you try downloading the english version?

**Comment by xFlushi** [comment]
i'll try it right now

**Comment by xFlushi** [comment]
![](https://image.prntscr.com/image/a-5Y8cX1QISuvLXfS5ZSlA.png)

okay funny thing now.
i downloaded the english version and it worked, but i realized something else...
I WAS USING THE OFFLINE MODE WITH DOWNLOADED SONGS ALL THIS TIME AND PROBABLY THAT WAS THE ERROR

i'm sorry for being stupid all this time and wasting your time.
maybe other people who have/had the same issue also use the offline mode, i'd recommend putting this as a fix so it won't happen to anyone else.

thanks you mate

**Comment by tjhrulz** [comment]
Hmmm, that is quite the oversight in the spotify plugin. I will make sure we add that to the list of possible issues, thanks. Glad we could get this working.
