### ISSUE TITLE
failed to initialize audio client.

### ISSUE THREAD

**Issue by lenscreamo** [MarcoPixel/Monstercat-Visualizer#93]
for a moment, it work, but then after a restart it doesn't work anymore, and when i check at the about section in rainmeter, the warning message came to say ' failed to initialize audio client '

**Comment by tjhrulz** [comment]
If you are using Realtek drivers there is a bug with the latest version, uninstall or downgrade them (preferable uninstall and use the windows drivers as realteks do nothing really).

Check out https://github.com/MarcoPixel/Monstercat-Visualizer/issues/72 for other fixes that may help you.

**Comment by lenscreamo** [comment]
hey thx for the reply, yeah, im using realtek, n after some hours of frustration i found out that when i use my bluetooth speaker (external audio) the visualizer works, but when i return on using my laptop (realtek) speaker, it just stop working and the 'failed to initialize audio client' popped back, i tested by removing my bluetooth speaker, restarted back my laptop so that it return to using the laptop's speaker (the same thing as if you just put your default laptop speaker which in my case is realtek back as default speaker), the visualizer doesnt work, so i can assume for now that anyone whos using the latest buggy realtek should opt to using external audio or simply downgrade realtek, although the last time i downgraded it, the visualizer still wont work, its a hassle though, but for now i would just opt to using my external bluetooth speaker ^^ hope it helps others, btw if someone found out which realtek version work without using external audio please do share, thx!

**Comment by tjhrulz** [comment]
Just uninstall their drivers and use the windows one instead as they are just as good.
Also make sure you refresh the skins when you changing default audio sources.
