### ISSUE TITLE
Song progress time and progress bar continues counting with each song played until next button is pressed

### ISSUE THREAD

**Issue by AMDSY3D** [MarcoPixel/Monstercat-Visualizer#94]
The song progress time and bar continue going up even when a new song plays. Like let's say a song is 3:40, it finishes and the next song comes on. The progress time and bar will display 4:50 (3:40 + the progress of the current song). Each song keeps on adding on top, until the next or previous button is hit, then it resets to 0:00. The length of the song also doesn't update with every song.

![monstercat visualizer problem](https://user-images.githubusercontent.com/31833706/30254776-15f3d086-966b-11e7-9503-bf3b3f46392f.png)

**Comment by AMDSY3D** [comment]
Here is the code:

[Rainmeter]
Group=SongInfo
Update=50

; = IMPORTANT =
; = For configuring the rainmeter skin, right-click the visualizer and click on "Open settings".
; = You can also open the variables.ini file located in:
; = "My Documents\Rainmeter\Skins\Monstercat Visualizer\@Resources"

; Small context menu when you right-click the skin
ContextTitle=" Open settings"
ContextAction=[!ActivateConfig "#ROOTCONFIG#\Settings" "general.ini"]
ContextTitle2=" Open variables file"
ContextAction2=["#@#variables.ini"]
ContextTitle3=" Toggle background"
ContextAction3=[!ToggleConfig "#ROOTCONFIG#\Background" "Background.ini"]

[Metadata]
Name=Monstercat Visualizer for Rainmeter
Author=marcopixel
License=MIT License
Information=An realtime audio visualizer for Rainmeter similar to the ones used in the Monstercat videos.

[Variables]
; Includes the variables used for the skin.
@include=#@#variables.ini

; Include media player and styling measures.
@include2=#@#include\Measure#MPMode#.inc
@include3=#@#include\MeasureStyling.inc

; Meter Cover - shows cover and song controls on hover
[MeterCoverDropShadow]
Meter=Image
X=(11*#ScaleSongInformation#)
Y=(4*#ScaleSongInformation#)
W=(400*#ScaleSongInformation#)
H=(400*#ScaleSongInformation#)
MouseOverAction=[!ShowMeterGroup "MediaControls"]
MouseLeaveAction=[!HideMeterGroup "MediaControls"]
SolidColor=#DropShadowColor#
Group=GroupShadowMeters

[MeterCoverBG]
Meter=Image
X=(7*#ScaleSongInformation#)
Y=0
W=(400*#ScaleSongInformation#)
H=(400*#ScaleSongInformation#)
MouseOverAction=[!ShowMeterGroup "MediaControls"]
MouseLeaveAction=[!HideMeterGroup "MediaControls"]
SolidColor=#Color#
Group=GroupDynamicColors

[MeterMonstercatCover]
Meter=IMAGE
ImageName=#@#images\nocover.png
X=(7*#ScaleSongInformation#)
Y=0r
W=(400*#ScaleSongInformation#)
H=(400*#ScaleSongInformation#)
MouseOverAction=[!ShowMeterGroup "MediaControls"]
MouseLeaveAction=[!HideMeterGroup "MediaControls"]
PreserveAspectRatio=2

[MeterCover]
Meter=IMAGE
MeasureName=MeasureCover
X=(7*#ScaleSongInformation#)
Y=0r
W=(400*#ScaleSongInformation#)
H=(400*#ScaleSongInformation#)
MouseOverAction=[!ShowMeterGroup "MediaControls"]
MouseLeaveAction=[!HideMeterGroup "MediaControls"]
UpdateDivider=10
Hidden=#ShowMonstercatCover#
[MeterPlayerOverlay]
Meter=IMAGE
X=(7*#ScaleSongInformation#)
Y=0r
W=(400*#ScaleSongInformation#)
H=(400*#ScaleSongInformation#)
SolidColor=0,0,0,200
Hidden=1
Group=MediaControls

[MeterPrevious]
Meter=IMAGE
ImageName=#@#images\previous.png
X=(30*#ScaleSongInformation#)
Y=(130*#ScaleSongInformation#)r
W=(96*#ScaleSongInformation#)
H=(96*#ScaleSongInformation#)
LeftMouseUpAction=[!CommandMeasure MeasureState "Previous"]
Hidden=1
Group=MediaControls

[MeterPlayPause]
Meter=IMAGE
X=(40*#ScaleSongInformation#)R
Y=0r
W=(96*#ScaleSongInformation#)
H=(96*#ScaleSongInformation#)
LeftMouseUpAction=[!CommandMeasure MeasureState "PlayPause"]
ImageName=#@#images\[MeasureStateButton].png
DynamicVariables=1
Hidden=1
Group=MediaControls

[MeterNext]
Meter=IMAGE
ImageName=#@#images\Next.png
X=(40*#ScaleSongInformation#)R
Y=0r
W=(96*#ScaleSongInformation#)
H=(96*#ScaleSongInformation#)
LeftMouseUpAction=[!CommandMeasure MeasureState "Next"]
Hidden=1
Group=MediaControls

[MeterPosition]
Meter=STRING
MeasureName=MeasurePosition
X=(34*#ScaleSongInformation#)
Y=(170*#ScaleSongInformation#)r
FontFace=#Font2#
FontSize=(40*#ScaleSongInformation#)
AntiAlias=1
ClipString=1
Text="%1"
Hidden=1
FontColor=255,255,255
Group=MediaControls

[MeterDividier]
Meter=STRING
MeterStyle=MeterPosition
X=(98*#ScaleSongInformation#)
Y=0r
Text="-"
Hidden=1
Group=MediaControls

[MeterDuration]
Meter=STRING
MeterStyle=MeterPosition
MeasureName=MeasureDuration
X=(75*#ScaleSongInformation#)R
Y=0r
Text="%1"
Hidden=1
Group=MediaControls

**Comment by tjhrulz** [comment]
We don't need the code posted here as that provides us with nothing. 
Please provide us with what music player you are using as well as what version of the skin you are on.

**Comment by AMDSY3D** [comment]
GPMDP with v1.8.1

**Comment by tjhrulz** [comment]
This is a bug with the GPMDP playback API, you will have to wait until they release their patch for it. I will keep this issue open until then.
