### ISSUE TITLE
Cover and Title information not working with iTunes 12.7 [BUG]

### ISSUE THREAD

**Issue by MaxRubbel** [MarcoPixel/Monstercat-Visualizer#95]
Hello, When I change the song on iTunes the information of the cover and title/singer does not change.

System:
Rainmeter 4.1.0 beta r2873 64-bit (Sep 11 2017)
Windows 10 Home 64-bit (build 15063)
iTunes 12.7
Monstercat-Visualizer 1.8.1

Log:

[Rainmeter Log.pdf](https://github.com/MarcoPixel/Monstercat-Visualizer/files/1301189/Rainmeter.Log.pdf)

**Comment by tjhrulz** [comment]
This is a known bug with Rainmeter. Apple seems to be starting to remove support for the COM API that Rainmeter uses as all event based triggers are not working. I plan on having a hotfix in the next version of Rainmeter but it may come at a CPU hit. Go either yell at Apple or downgrade in the meantime.

**Comment by tjhrulz** [comment]
Fixed with https://github.com/rainmeter/rainmeter/commit/a90d6a28d6e6f776752f0b50988f54d2b4968136 should be included in the next release candidate or 4.1 final.
