### ISSUE TITLE
Left Side of Visualizer Not Working?

### ISSUE THREAD

**Issue by pipsternick** [MarcoPixel/Monstercat-Visualizer#96]
I have no idea why, but when I finally downloaded the newest version of the visualizer, the left side no longer responds to the kick of songs; some bars are permanently floored, it seems. Any thoughts on what the problem could be? Thanks so much.
![screenshot 1](https://user-images.githubusercontent.com/32085741/30575330-9885ea56-9cc5-11e7-8bbe-a2ed6327b63f.png)

**Comment by MarcoPixel** [comment]
Decrease sensitivity and increase height, it should be working as the latest version didn't change that much to break the skin.

**Comment by pipsternick** [comment]
Ok so separate comment: In messing around with it today and decreasing sensitivity and increasing height like you said, I figured out that the left side is only floored when I don't have headphones or a speaker plugged into the audio jack, which kinda seemed weird to me, but hey. Everything works perfectly with headphones in, but for whatever reason the computer speakers don't seem to allow that left side to work.

**Comment by Matter-Shifter** [comment]
It seem we're likely having the same problem. It happened due to a 'wizard' app enhances the audio so that we listen using speaker to any sound will make better sound to us.

**Comment by MarcoPixel** [comment]
Closed because of inactivity.
