### ISSUE TITLE
Left title song information doesnt go further than this

### ISSUE THREAD

**Issue by RealAnTiHeRo** [MarcoPixel/Monstercat-Visualizer#98]
After i installed the new version of the visualizer, the left song information doesnt go further than this( look at the screeshot), this wasnt the case in previous versions. Any thing i can do? ![afbeelding](https://user-images.githubusercontent.com/32430008/31053275-1aee9794-a69a-11e7-8c99-9d0a63f8a185.png)

**Comment by MarcoPixel** [comment]
Disable "Clip song information" under General settings. This should fix it.

**Comment by tjhrulz** [comment]
I think he might have been talking about the skin itself being too wide. To fix that either decrease the song information scale, or decrease the number & size of bars in the Visualizer or right click and under the settings overflow disable keep on screen.

**Comment by MarcoPixel** [comment]
Closed because of inactivity.
